; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Where sifive-u74 forces a count that does not remove the copies that shift
; chains need at the backedge, a count that does is used instead.
; RUN: opt -S -passes=loop-unroll -mtriple=riscv64 -mcpu=sifive-u74 \
; RUN:   -unroll-partial-threshold=8 < %s | FileCheck %s --check-prefix=SMALL
; RUN: opt -S -passes=loop-unroll -mtriple=riscv64 -mcpu=sifive-u74 \
; RUN:   -unroll-partial-threshold=17 < %s | FileCheck %s --check-prefix=MEDIUM
; RUN: opt -S -passes=loop-unroll -mtriple=riscv64 -mcpu=sifive-u74 \
; RUN:   -unroll-allow-remainder=false -unroll-max-count=7 < %s \
; RUN:   | FileCheck %s --check-prefix=NOREM

; Reversing a list: a chain whose values live for three iterations. With a
; size limit of 8, the forced count is 2, and 3 is used instead.
define ptr @reverse(ptr %list) {
; SMALL-LABEL: define ptr @reverse(
; SMALL-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; SMALL-NEXT:  [[ENTRY:.*]]:
; SMALL-NEXT:    br label %[[LOOP:.*]]
; SMALL:       [[LOOP]]:
; SMALL-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_2:%.*]], %[[LOOP_2:.*]] ]
; SMALL-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_2]] ]
; SMALL-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 8
; SMALL-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; SMALL-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; SMALL-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; SMALL:       [[LOOP_1]]:
; SMALL-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 8
; SMALL-NEXT:    store ptr [[CUR]], ptr [[NEXT]], align 8
; SMALL-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; SMALL-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2]]
; SMALL:       [[LOOP_2]]:
; SMALL-NEXT:    [[NEXT_2]] = load ptr, ptr [[NEXT_1]], align 8
; SMALL-NEXT:    store ptr [[NEXT]], ptr [[NEXT_1]], align 8
; SMALL-NEXT:    [[DONE_2:%.*]] = icmp eq ptr [[NEXT_2]], null
; SMALL-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; SMALL:       [[EXIT]]:
; SMALL-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ [[NEXT]], %[[LOOP_1]] ], [ [[NEXT_1]], %[[LOOP_2]] ]
; SMALL-NEXT:    ret ptr [[CUR_LCSSA]]
;
; MEDIUM-LABEL: define ptr @reverse(
; MEDIUM-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; MEDIUM-NEXT:  [[ENTRY:.*]]:
; MEDIUM-NEXT:    br label %[[LOOP:.*]]
; MEDIUM:       [[LOOP]]:
; MEDIUM-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_3:%.*]], %[[LOOP_3:.*]] ]
; MEDIUM-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[NEXT_2:%.*]], %[[LOOP_3]] ]
; MEDIUM-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 8
; MEDIUM-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; MEDIUM-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; MEDIUM-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; MEDIUM:       [[LOOP_1]]:
; MEDIUM-NEXT:    [[NEXT_1:%.*]] = load ptr, ptr [[NEXT]], align 8
; MEDIUM-NEXT:    store ptr [[CUR]], ptr [[NEXT]], align 8
; MEDIUM-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; MEDIUM-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2:.*]]
; MEDIUM:       [[LOOP_2]]:
; MEDIUM-NEXT:    [[NEXT_2]] = load ptr, ptr [[NEXT_1]], align 8
; MEDIUM-NEXT:    store ptr [[NEXT]], ptr [[NEXT_1]], align 8
; MEDIUM-NEXT:    [[DONE_2:%.*]] = icmp eq ptr [[NEXT_2]], null
; MEDIUM-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP_3]]
; MEDIUM:       [[LOOP_3]]:
; MEDIUM-NEXT:    [[NEXT_3]] = load ptr, ptr [[NEXT_2]], align 8
; MEDIUM-NEXT:    store ptr [[NEXT_1]], ptr [[NEXT_2]], align 8
; MEDIUM-NEXT:    [[DONE_3:%.*]] = icmp eq ptr [[NEXT_3]], null
; MEDIUM-NEXT:    br i1 [[DONE_3]], label %[[EXIT]], label %[[LOOP]]
; MEDIUM:       [[EXIT]]:
; MEDIUM-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ [[NEXT]], %[[LOOP_1]] ], [ [[NEXT_1]], %[[LOOP_2]] ], [ [[NEXT_2]], %[[LOOP_3]] ]
; MEDIUM-NEXT:    ret ptr [[CUR_LCSSA]]
;
; NOREM-LABEL: define ptr @reverse(
; NOREM-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; NOREM-NEXT:  [[ENTRY:.*]]:
; NOREM-NEXT:    br label %[[LOOP:.*]]
; NOREM:       [[LOOP]]:
; NOREM-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; NOREM-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR]], %[[LOOP]] ]
; NOREM-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; NOREM-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; NOREM-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; NOREM-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; NOREM:       [[EXIT]]:
; NOREM-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ]
; NOREM-NEXT:    ret ptr [[CUR_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %prev = phi ptr [ null, %entry ], [ %cur, %loop ]
  %next = load ptr, ptr %cur
  store ptr %prev, ptr %cur
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret ptr %cur
}

; Rotating three values: a cycle that needs a multiple of three. With a size
; limit of 8, the forced count is 2, and 3 is used instead; with a size limit of
; 17, the forced count is 4, and is rounded down to 3.
define void @rotate(ptr %p, ptr %q, ptr %r, ptr %out) {
; SMALL-LABEL: define void @rotate(
; SMALL-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; SMALL-NEXT:  [[ENTRY:.*:]]
; SMALL-NEXT:    br label %[[LOOP:.*]]
; SMALL:       [[LOOP]]:
; SMALL-NEXT:    [[V:%.*]] = load i64, ptr [[P]], align 8
; SMALL-NEXT:    store i64 [[V]], ptr [[OUT]], align 8
; SMALL-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V]], 0
; SMALL-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; SMALL:       [[LOOP_1]]:
; SMALL-NEXT:    [[V_1:%.*]] = load i64, ptr [[Q]], align 8
; SMALL-NEXT:    store i64 [[V_1]], ptr [[OUT]], align 8
; SMALL-NEXT:    [[DONE_1:%.*]] = icmp eq i64 [[V_1]], 0
; SMALL-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2:.*]]
; SMALL:       [[LOOP_2]]:
; SMALL-NEXT:    [[V_2:%.*]] = load i64, ptr [[R]], align 8
; SMALL-NEXT:    store i64 [[V_2]], ptr [[OUT]], align 8
; SMALL-NEXT:    [[DONE_2:%.*]] = icmp eq i64 [[V_2]], 0
; SMALL-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; SMALL:       [[EXIT]]:
; SMALL-NEXT:    ret void
;
; MEDIUM-LABEL: define void @rotate(
; MEDIUM-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; MEDIUM-NEXT:  [[ENTRY:.*:]]
; MEDIUM-NEXT:    br label %[[LOOP:.*]]
; MEDIUM:       [[LOOP]]:
; MEDIUM-NEXT:    [[V:%.*]] = load i64, ptr [[P]], align 8
; MEDIUM-NEXT:    store i64 [[V]], ptr [[OUT]], align 8
; MEDIUM-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V]], 0
; MEDIUM-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; MEDIUM:       [[LOOP_1]]:
; MEDIUM-NEXT:    [[V_1:%.*]] = load i64, ptr [[Q]], align 8
; MEDIUM-NEXT:    store i64 [[V_1]], ptr [[OUT]], align 8
; MEDIUM-NEXT:    [[DONE_1:%.*]] = icmp eq i64 [[V_1]], 0
; MEDIUM-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2:.*]]
; MEDIUM:       [[LOOP_2]]:
; MEDIUM-NEXT:    [[V_2:%.*]] = load i64, ptr [[R]], align 8
; MEDIUM-NEXT:    store i64 [[V_2]], ptr [[OUT]], align 8
; MEDIUM-NEXT:    [[DONE_2:%.*]] = icmp eq i64 [[V_2]], 0
; MEDIUM-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; MEDIUM:       [[EXIT]]:
; MEDIUM-NEXT:    ret void
;
; NOREM-LABEL: define void @rotate(
; NOREM-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; NOREM-NEXT:  [[ENTRY:.*]]:
; NOREM-NEXT:    br label %[[LOOP:.*]]
; NOREM:       [[LOOP]]:
; NOREM-NEXT:    [[A:%.*]] = phi ptr [ [[P]], %[[ENTRY]] ], [ [[B:%.*]], %[[LOOP]] ]
; NOREM-NEXT:    [[B]] = phi ptr [ [[Q]], %[[ENTRY]] ], [ [[C:%.*]], %[[LOOP]] ]
; NOREM-NEXT:    [[C]] = phi ptr [ [[R]], %[[ENTRY]] ], [ [[A]], %[[LOOP]] ]
; NOREM-NEXT:    [[V:%.*]] = load i64, ptr [[A]], align 8
; NOREM-NEXT:    store i64 [[V]], ptr [[OUT]], align 8
; NOREM-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V]], 0
; NOREM-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; NOREM:       [[EXIT]]:
; NOREM-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %a = phi ptr [ %p, %entry ], [ %b, %loop ]
  %b = phi ptr [ %q, %entry ], [ %c, %loop ]
  %c = phi ptr [ %r, %entry ], [ %a, %loop ]
  %v = load i64, ptr %a
  store i64 %v, ptr %out
  %done = icmp eq i64 %v, 0
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Reversing a list up to a count: runtime unrolling is chosen, but no remainder
; loop can be made for a loop with two exits. With a size limit of 17, the
; forced count of 2 is replaced by 3, keeping every exit.
define ptr @reverse_until(ptr %list, i64 %n) {
; SMALL-LABEL: define ptr @reverse_until(
; SMALL-SAME: ptr [[LIST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; SMALL-NEXT:  [[ENTRY:.*]]:
; SMALL-NEXT:    br label %[[LOOP:.*]]
; SMALL:       [[LOOP]]:
; SMALL-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LATCH:.*]] ]
; SMALL-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LATCH]] ]
; SMALL-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR]], %[[LATCH]] ]
; SMALL-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; SMALL-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; SMALL-NEXT:    [[END:%.*]] = icmp eq ptr [[NEXT]], null
; SMALL-NEXT:    br i1 [[END]], label %[[EXIT:.*]], label %[[LATCH]]
; SMALL:       [[LATCH]]:
; SMALL-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; SMALL-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; SMALL-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]]
; SMALL:       [[EXIT]]:
; SMALL-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LATCH]] ], [ [[CUR]], %[[LOOP]] ]
; SMALL-NEXT:    ret ptr [[CUR_LCSSA]]
;
; MEDIUM-LABEL: define ptr @reverse_until(
; MEDIUM-SAME: ptr [[LIST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; MEDIUM-NEXT:  [[ENTRY:.*]]:
; MEDIUM-NEXT:    br label %[[LOOP:.*]]
; MEDIUM:       [[LOOP]]:
; MEDIUM-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT_2:%.*]], %[[LATCH_2:.*]] ]
; MEDIUM-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_2:%.*]], %[[LATCH_2]] ]
; MEDIUM-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LATCH_2]] ]
; MEDIUM-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 8
; MEDIUM-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; MEDIUM-NEXT:    [[END:%.*]] = icmp eq ptr [[NEXT]], null
; MEDIUM-NEXT:    br i1 [[END]], label %[[EXIT:.*]], label %[[LATCH:.*]]
; MEDIUM:       [[LATCH]]:
; MEDIUM-NEXT:    [[I_NEXT:%.*]] = add i64 [[I]], 1
; MEDIUM-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; MEDIUM-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP_1:.*]]
; MEDIUM:       [[LOOP_1]]:
; MEDIUM-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 8
; MEDIUM-NEXT:    store ptr [[CUR]], ptr [[NEXT]], align 8
; MEDIUM-NEXT:    [[END_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; MEDIUM-NEXT:    br i1 [[END_1]], label %[[EXIT]], label %[[LATCH_1:.*]]
; MEDIUM:       [[LATCH_1]]:
; MEDIUM-NEXT:    [[I_NEXT_1:%.*]] = add i64 [[I]], 2
; MEDIUM-NEXT:    [[DONE_1:%.*]] = icmp eq i64 [[I_NEXT_1]], [[N]]
; MEDIUM-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2:.*]]
; MEDIUM:       [[LOOP_2]]:
; MEDIUM-NEXT:    [[NEXT_2]] = load ptr, ptr [[NEXT_1]], align 8
; MEDIUM-NEXT:    store ptr [[NEXT]], ptr [[NEXT_1]], align 8
; MEDIUM-NEXT:    [[END_2:%.*]] = icmp eq ptr [[NEXT_2]], null
; MEDIUM-NEXT:    br i1 [[END_2]], label %[[EXIT]], label %[[LATCH_2]]
; MEDIUM:       [[LATCH_2]]:
; MEDIUM-NEXT:    [[I_NEXT_2]] = add i64 [[I]], 3
; MEDIUM-NEXT:    [[DONE_2:%.*]] = icmp eq i64 [[I_NEXT_2]], [[N]]
; MEDIUM-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; MEDIUM:       [[EXIT]]:
; MEDIUM-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LATCH]] ], [ [[CUR]], %[[LOOP]] ], [ [[NEXT]], %[[LOOP_1]] ], [ [[NEXT]], %[[LATCH_1]] ], [ [[NEXT_1]], %[[LOOP_2]] ], [ [[NEXT_1]], %[[LATCH_2]] ]
; MEDIUM-NEXT:    ret ptr [[CUR_LCSSA]]
;
; NOREM-LABEL: define ptr @reverse_until(
; NOREM-SAME: ptr [[LIST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; NOREM-NEXT:  [[ENTRY:.*]]:
; NOREM-NEXT:    br label %[[LOOP:.*]]
; NOREM:       [[LOOP]]:
; NOREM-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LATCH:.*]] ]
; NOREM-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LATCH]] ]
; NOREM-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR]], %[[LATCH]] ]
; NOREM-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; NOREM-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; NOREM-NEXT:    [[END:%.*]] = icmp eq ptr [[NEXT]], null
; NOREM-NEXT:    br i1 [[END]], label %[[EXIT:.*]], label %[[LATCH]]
; NOREM:       [[LATCH]]:
; NOREM-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; NOREM-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; NOREM-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]]
; NOREM:       [[EXIT]]:
; NOREM-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LATCH]] ], [ [[CUR]], %[[LOOP]] ]
; NOREM-NEXT:    ret ptr [[CUR_LCSSA]]
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %latch ]
  %cur = phi ptr [ %list, %entry ], [ %next, %latch ]
  %prev = phi ptr [ null, %entry ], [ %cur, %latch ]
  %next = load ptr, ptr %cur
  store ptr %prev, ptr %cur
  %end = icmp eq ptr %next, null
  br i1 %end, label %exit, label %latch

latch:
  %i.next = add i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret ptr %cur
}

; Swapping two pointers eight times a count. With remainders disallowed and
; counts limited to 7, the forced count of 7 rounded down to a multiple of two
; would not divide the trip multiple of 8, and 2 is used instead.
define void @ping_pong_8n(ptr %src, ptr %dst, i64 %n) {
; SMALL-LABEL: define void @ping_pong_8n(
; SMALL-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; SMALL-NEXT:  [[ENTRY:.*]]:
; SMALL-NEXT:    [[N8:%.*]] = shl nuw i64 [[N]], 3
; SMALL-NEXT:    br label %[[LOOP:.*]]
; SMALL:       [[LOOP]]:
; SMALL-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; SMALL-NEXT:    [[FROM:%.*]] = phi ptr [ [[SRC]], %[[ENTRY]] ], [ [[TO:%.*]], %[[LOOP]] ]
; SMALL-NEXT:    [[TO]] = phi ptr [ [[DST]], %[[ENTRY]] ], [ [[FROM]], %[[LOOP]] ]
; SMALL-NEXT:    [[V:%.*]] = load i64, ptr [[FROM]], align 8
; SMALL-NEXT:    [[W:%.*]] = add i64 [[V]], 1
; SMALL-NEXT:    store i64 [[W]], ptr [[TO]], align 8
; SMALL-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; SMALL-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N8]]
; SMALL-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; SMALL:       [[EXIT]]:
; SMALL-NEXT:    ret void
;
; MEDIUM-LABEL: define void @ping_pong_8n(
; MEDIUM-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; MEDIUM-NEXT:  [[ENTRY:.*]]:
; MEDIUM-NEXT:    [[N8:%.*]] = shl nuw i64 [[N]], 3
; MEDIUM-NEXT:    br label %[[LOOP:.*]]
; MEDIUM:       [[LOOP]]:
; MEDIUM-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT_1:%.*]], %[[LOOP]] ]
; MEDIUM-NEXT:    [[V:%.*]] = load i64, ptr [[SRC]], align 8
; MEDIUM-NEXT:    [[W:%.*]] = add i64 [[V]], 1
; MEDIUM-NEXT:    store i64 [[W]], ptr [[DST]], align 8
; MEDIUM-NEXT:    [[V_1:%.*]] = load i64, ptr [[DST]], align 8
; MEDIUM-NEXT:    [[W_1:%.*]] = add i64 [[V_1]], 1
; MEDIUM-NEXT:    store i64 [[W_1]], ptr [[SRC]], align 8
; MEDIUM-NEXT:    [[I_NEXT_1]] = add nuw i64 [[I]], 2
; MEDIUM-NEXT:    [[DONE_1:%.*]] = icmp eq i64 [[I_NEXT_1]], [[N8]]
; MEDIUM-NEXT:    br i1 [[DONE_1]], label %[[EXIT:.*]], label %[[LOOP]]
; MEDIUM:       [[EXIT]]:
; MEDIUM-NEXT:    ret void
;
; NOREM-LABEL: define void @ping_pong_8n(
; NOREM-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; NOREM-NEXT:  [[ENTRY:.*]]:
; NOREM-NEXT:    [[N8:%.*]] = shl nuw i64 [[N]], 3
; NOREM-NEXT:    br label %[[LOOP:.*]]
; NOREM:       [[LOOP]]:
; NOREM-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT_1:%.*]], %[[LOOP]] ]
; NOREM-NEXT:    [[V:%.*]] = load i64, ptr [[SRC]], align 8
; NOREM-NEXT:    [[W:%.*]] = add i64 [[V]], 1
; NOREM-NEXT:    store i64 [[W]], ptr [[DST]], align 8
; NOREM-NEXT:    [[V_1:%.*]] = load i64, ptr [[DST]], align 8
; NOREM-NEXT:    [[W_1:%.*]] = add i64 [[V_1]], 1
; NOREM-NEXT:    store i64 [[W_1]], ptr [[SRC]], align 8
; NOREM-NEXT:    [[I_NEXT_1]] = add nuw i64 [[I]], 2
; NOREM-NEXT:    [[DONE_1:%.*]] = icmp eq i64 [[I_NEXT_1]], [[N8]]
; NOREM-NEXT:    br i1 [[DONE_1]], label %[[EXIT:.*]], label %[[LOOP]]
; NOREM:       [[EXIT]]:
; NOREM-NEXT:    ret void
;
entry:
  %n8 = shl nuw i64 %n, 3
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %from = phi ptr [ %src, %entry ], [ %to, %loop ]
  %to = phi ptr [ %dst, %entry ], [ %from, %loop ]
  %v = load i64, ptr %from
  %w = add i64 %v, 1
  store i64 %w, ptr %to
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, %n8
  br i1 %done, label %exit, label %loop

exit:
  ret void
}
