; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=loop-unroll -mtriple=riscv64 -mattr=-unroll-shift-chains < %s \
; RUN:   | FileCheck %s --check-prefix=DEFAULT
; RUN: opt -S -passes=loop-unroll -mtriple=riscv64 -mattr=+unroll-shift-chains < %s \
; RUN:   | FileCheck %s --check-prefix=CHAIN

; Reversing a list rotates three values through the loop: the next node, the
; current one and the previous one. Each iteration needs two copies at the
; backedge to move them along; unrolled by three, the rotation is the identity
; and the copies disappear.
define ptr @reverse(ptr %list) {
; DEFAULT-LABEL: define ptr @reverse(
; DEFAULT-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    [[EMPTY:%.*]] = icmp eq ptr [[LIST]], null
; DEFAULT-NEXT:    br i1 [[EMPTY]], label %[[EXIT:.*]], label %[[LOOP_PREHEADER:.*]]
; DEFAULT:       [[LOOP_PREHEADER]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[CUR:%.*]] = phi ptr [ [[NEXT:%.*]], %[[LOOP]] ], [ [[LIST]], %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ null, %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; DEFAULT-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT_LOOPEXIT]]:
; DEFAULT-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ]
; DEFAULT-NEXT:    br label %[[EXIT]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    [[RESULT:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; DEFAULT-NEXT:    ret ptr [[RESULT]]
;
; CHAIN-LABEL: define ptr @reverse(
; CHAIN-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    [[EMPTY:%.*]] = icmp eq ptr [[LIST]], null
; CHAIN-NEXT:    br i1 [[EMPTY]], label %[[EXIT:.*]], label %[[LOOP_PREHEADER:.*]]
; CHAIN:       [[LOOP_PREHEADER]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[LOOP_PREHEADER]] ], [ [[NEXT_2:%.*]], %[[LOOP_2:.*]] ]
; CHAIN-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[LOOP_PREHEADER]] ], [ [[NEXT_1:%.*]], %[[LOOP_2]] ]
; CHAIN-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 8
; CHAIN-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP_1:.*]]
; CHAIN:       [[LOOP_1]]:
; CHAIN-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 8
; CHAIN-NEXT:    store ptr [[CUR]], ptr [[NEXT]], align 8
; CHAIN-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHAIN-NEXT:    br i1 [[DONE_1]], label %[[EXIT_LOOPEXIT]], label %[[LOOP_2]]
; CHAIN:       [[LOOP_2]]:
; CHAIN-NEXT:    [[NEXT_2]] = load ptr, ptr [[NEXT_1]], align 8
; CHAIN-NEXT:    store ptr [[NEXT]], ptr [[NEXT_1]], align 8
; CHAIN-NEXT:    [[DONE_2:%.*]] = icmp eq ptr [[NEXT_2]], null
; CHAIN-NEXT:    br i1 [[DONE_2]], label %[[EXIT_LOOPEXIT]], label %[[LOOP]]
; CHAIN:       [[EXIT_LOOPEXIT]]:
; CHAIN-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ [[NEXT]], %[[LOOP_1]] ], [ [[NEXT_1]], %[[LOOP_2]] ]
; CHAIN-NEXT:    br label %[[EXIT]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    [[RESULT:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHAIN-NEXT:    ret ptr [[RESULT]]
;
entry:
  %empty = icmp eq ptr %list, null
  br i1 %empty, label %exit, label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %prev = phi ptr [ null, %entry ], [ %cur, %loop ]
  %next = load ptr, ptr %cur
  store ptr %prev, ptr %cur
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  %result = phi ptr [ null, %entry ], [ %cur, %loop ]
  ret ptr %result
}

; The same chain in a body too large to be forced is left to the defaults.
define ptr @reverse_and_sum(ptr %list, ptr %sum) {
; DEFAULT-LABEL: define ptr @reverse_and_sum(
; DEFAULT-SAME: ptr [[LIST:%.*]], ptr [[SUM:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    [[EMPTY:%.*]] = icmp eq ptr [[LIST]], null
; DEFAULT-NEXT:    br i1 [[EMPTY]], label %[[EXIT:.*]], label %[[LOOP_PREHEADER:.*]]
; DEFAULT:       [[LOOP_PREHEADER]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[CUR:%.*]] = phi ptr [ [[NEXT:%.*]], %[[LOOP]] ], [ [[LIST]], %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ null, %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[ACC:%.*]] = phi i64 [ [[ACC_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; DEFAULT-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; DEFAULT-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 8
; DEFAULT-NEXT:    [[A:%.*]] = load i64, ptr [[FIELD]], align 8
; DEFAULT-NEXT:    [[FIELD2:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 16
; DEFAULT-NEXT:    [[B:%.*]] = load i64, ptr [[FIELD2]], align 8
; DEFAULT-NEXT:    [[FIELD3:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 24
; DEFAULT-NEXT:    [[C:%.*]] = load i64, ptr [[FIELD3]], align 8
; DEFAULT-NEXT:    [[AB:%.*]] = mul i64 [[A]], [[B]]
; DEFAULT-NEXT:    [[ABC:%.*]] = mul i64 [[AB]], [[C]]
; DEFAULT-NEXT:    [[X:%.*]] = xor i64 [[ABC]], [[ACC]]
; DEFAULT-NEXT:    [[Y:%.*]] = udiv i64 [[X]], [[A]]
; DEFAULT-NEXT:    [[ACC_NEXT]] = add i64 [[Y]], [[AB]]
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT_LOOPEXIT]]:
; DEFAULT-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i64 [ [[ACC_NEXT]], %[[LOOP]] ]
; DEFAULT-NEXT:    br label %[[EXIT]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    [[RESULT:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; DEFAULT-NEXT:    [[TOTAL:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; DEFAULT-NEXT:    store i64 [[TOTAL]], ptr [[SUM]], align 8
; DEFAULT-NEXT:    ret ptr [[RESULT]]
;
; CHAIN-LABEL: define ptr @reverse_and_sum(
; CHAIN-SAME: ptr [[LIST:%.*]], ptr [[SUM:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    [[EMPTY:%.*]] = icmp eq ptr [[LIST]], null
; CHAIN-NEXT:    br i1 [[EMPTY]], label %[[EXIT:.*]], label %[[LOOP_PREHEADER:.*]]
; CHAIN:       [[LOOP_PREHEADER]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[CUR:%.*]] = phi ptr [ [[NEXT:%.*]], %[[LOOP]] ], [ [[LIST]], %[[LOOP_PREHEADER]] ]
; CHAIN-NEXT:    [[PREV:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ null, %[[LOOP_PREHEADER]] ]
; CHAIN-NEXT:    [[ACC:%.*]] = phi i64 [ [[ACC_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHAIN-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; CHAIN-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; CHAIN-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 8
; CHAIN-NEXT:    [[A:%.*]] = load i64, ptr [[FIELD]], align 8
; CHAIN-NEXT:    [[FIELD2:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 16
; CHAIN-NEXT:    [[B:%.*]] = load i64, ptr [[FIELD2]], align 8
; CHAIN-NEXT:    [[FIELD3:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 24
; CHAIN-NEXT:    [[C:%.*]] = load i64, ptr [[FIELD3]], align 8
; CHAIN-NEXT:    [[AB:%.*]] = mul i64 [[A]], [[B]]
; CHAIN-NEXT:    [[ABC:%.*]] = mul i64 [[AB]], [[C]]
; CHAIN-NEXT:    [[X:%.*]] = xor i64 [[ABC]], [[ACC]]
; CHAIN-NEXT:    [[Y:%.*]] = udiv i64 [[X]], [[A]]
; CHAIN-NEXT:    [[ACC_NEXT]] = add i64 [[Y]], [[AB]]
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT_LOOPEXIT]]:
; CHAIN-NEXT:    [[CUR_LCSSA:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ]
; CHAIN-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i64 [ [[ACC_NEXT]], %[[LOOP]] ]
; CHAIN-NEXT:    br label %[[EXIT]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    [[RESULT:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHAIN-NEXT:    [[TOTAL:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHAIN-NEXT:    store i64 [[TOTAL]], ptr [[SUM]], align 8
; CHAIN-NEXT:    ret ptr [[RESULT]]
;
entry:
  %empty = icmp eq ptr %list, null
  br i1 %empty, label %exit, label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %prev = phi ptr [ null, %entry ], [ %cur, %loop ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %loop ]
  %next = load ptr, ptr %cur
  store ptr %prev, ptr %cur
  %field = getelementptr inbounds i8, ptr %cur, i64 8
  %a = load i64, ptr %field
  %field2 = getelementptr inbounds i8, ptr %cur, i64 16
  %b = load i64, ptr %field2
  %field3 = getelementptr inbounds i8, ptr %cur, i64 24
  %c = load i64, ptr %field3
  %ab = mul i64 %a, %b
  %abc = mul i64 %ab, %c
  %x = xor i64 %abc, %acc
  %y = udiv i64 %x, %a
  %acc.next = add i64 %y, %ab
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  %result = phi ptr [ null, %entry ], [ %cur, %loop ]
  %total = phi i64 [ 0, %entry ], [ %acc.next, %loop ]
  store i64 %total, ptr %sum
  ret ptr %result
}

; A plain induction variable is not a shift chain.
define void @clear(ptr %p, i64 %n) {
; DEFAULT-LABEL: define void @clear(
; DEFAULT-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    [[EMPTY:%.*]] = icmp eq i64 [[N]], 0
; DEFAULT-NEXT:    br i1 [[EMPTY]], label %[[EXIT:.*]], label %[[LOOP_PREHEADER:.*]]
; DEFAULT:       [[LOOP_PREHEADER]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; DEFAULT-NEXT:    store i64 0, ptr [[ADDR]], align 8
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT_LOOPEXIT]]:
; DEFAULT-NEXT:    br label %[[EXIT]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @clear(
; CHAIN-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*:]]
; CHAIN-NEXT:    [[EMPTY:%.*]] = icmp eq i64 [[N]], 0
; CHAIN-NEXT:    br i1 [[EMPTY]], label %[[EXIT:.*]], label %[[LOOP_PREHEADER:.*]]
; CHAIN:       [[LOOP_PREHEADER]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHAIN-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHAIN-NEXT:    store i64 0, ptr [[ADDR]], align 8
; CHAIN-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT_LOOPEXIT]]:
; CHAIN-NEXT:    br label %[[EXIT]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  %empty = icmp eq i64 %n, 0
  br i1 %empty, label %exit, label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  store i64 0, ptr %addr
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Fibonacci shifts two values along a chain, but the one it drops is dead by
; the time the new one is computed, so the three values only ever need two
; registers and the rotation comes back after two iterations, not three.
define i64 @fib(i64 %n) {
; DEFAULT-LABEL: define i64 @fib(
; DEFAULT-SAME: i64 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[A:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[B:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[B]] = phi i64 [ 1, %[[ENTRY]] ], [ [[C:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[C]] = add i64 [[A]], [[B]]
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    [[C_LCSSA:%.*]] = phi i64 [ [[C]], %[[LOOP]] ]
; DEFAULT-NEXT:    ret i64 [[C_LCSSA]]
;
; CHAIN-LABEL: define i64 @fib(
; CHAIN-SAME: i64 [[N:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; CHAIN-NEXT:    [[XTRAITER:%.*]] = and i64 [[N]], 1
; CHAIN-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[TMP0]], 1
; CHAIN-NEXT:    br i1 [[TMP1]], label %[[LOOP_EPIL_PREHEADER:.*]], label %[[ENTRY_NEW:.*]]
; CHAIN:       [[ENTRY_NEW]]:
; CHAIN-NEXT:    [[UNROLL_ITER:%.*]] = sub i64 [[N]], [[XTRAITER]]
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY_NEW]] ], [ [[I_NEXT_1:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[A:%.*]] = phi i64 [ 0, %[[ENTRY_NEW]] ], [ [[C:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[B:%.*]] = phi i64 [ 1, %[[ENTRY_NEW]] ], [ [[C_1:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[NITER:%.*]] = phi i64 [ 0, %[[ENTRY_NEW]] ], [ [[NITER_NEXT_1:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[C]] = add i64 [[A]], [[B]]
; CHAIN-NEXT:    [[C_1]] = add i64 [[B]], [[C]]
; CHAIN-NEXT:    [[I_NEXT_1]] = add nuw i64 [[I]], 2
; CHAIN-NEXT:    [[NITER_NEXT_1]] = add i64 [[NITER]], 2
; CHAIN-NEXT:    [[NITER_NCMP_1:%.*]] = icmp eq i64 [[NITER_NEXT_1]], [[UNROLL_ITER]]
; CHAIN-NEXT:    br i1 [[NITER_NCMP_1]], label %[[EXIT_UNR_LCSSA:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT_UNR_LCSSA]]:
; CHAIN-NEXT:    [[C_LCSSA_PH:%.*]] = phi i64 [ [[C_1]], %[[LOOP]] ]
; CHAIN-NEXT:    [[A_UNR:%.*]] = phi i64 [ [[C]], %[[LOOP]] ]
; CHAIN-NEXT:    [[B_UNR:%.*]] = phi i64 [ [[C_1]], %[[LOOP]] ]
; CHAIN-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i64 [[XTRAITER]], 0
; CHAIN-NEXT:    br i1 [[LCMP_MOD]], label %[[LOOP_EPIL_PREHEADER]], label %[[EXIT:.*]]
; CHAIN:       [[LOOP_EPIL_PREHEADER]]:
; CHAIN-NEXT:    [[A_EPIL_INIT:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[A_UNR]], %[[EXIT_UNR_LCSSA]] ]
; CHAIN-NEXT:    [[B_EPIL_INIT:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[B_UNR]], %[[EXIT_UNR_LCSSA]] ]
; CHAIN-NEXT:    [[LCMP_MOD2:%.*]] = icmp ne i64 [[XTRAITER]], 0
; CHAIN-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD2]])
; CHAIN-NEXT:    br label %[[LOOP_EPIL:.*]]
; CHAIN:       [[LOOP_EPIL]]:
; CHAIN-NEXT:    [[C_EPIL:%.*]] = add i64 [[A_EPIL_INIT]], [[B_EPIL_INIT]]
; CHAIN-NEXT:    br label %[[EXIT]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    [[C_LCSSA:%.*]] = phi i64 [ [[C_LCSSA_PH]], %[[EXIT_UNR_LCSSA]] ], [ [[C_EPIL]], %[[LOOP_EPIL]] ]
; CHAIN-NEXT:    ret i64 [[C_LCSSA]]
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %a = phi i64 [ 0, %entry ], [ %b, %loop ]
  %b = phi i64 [ 1, %entry ], [ %c, %loop ]
  %c = add i64 %a, %b
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret i64 %c
}

; A chain of one phi is a shift too when its old value is still needed after
; the new one is loaded: the two alternate between two registers.
define void @mark(ptr %list) {
; DEFAULT-LABEL: define void @mark(
; DEFAULT-SAME: ptr [[LIST:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; DEFAULT-NEXT:    [[FLAG:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 8
; DEFAULT-NEXT:    store i8 1, ptr [[FLAG]], align 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @mark(
; CHAIN-SAME: ptr [[LIST:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHAIN-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 8
; CHAIN-NEXT:    [[FLAG:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 8
; CHAIN-NEXT:    store i8 1, ptr [[FLAG]], align 1
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHAIN:       [[LOOP_1]]:
; CHAIN-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 8
; CHAIN-NEXT:    [[FLAG_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i64 8
; CHAIN-NEXT:    store i8 1, ptr [[FLAG_1]], align 1
; CHAIN-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHAIN-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %next = load ptr, ptr %cur
  %flag = getelementptr inbounds i8, ptr %cur, i64 8
  store i8 1, ptr %flag
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Two phis swapping each iteration are a cycle with a period of two, not a
; chain of two with a period of three: unrolled by three, they would still be
; swapped at the backedge.
define void @ping_pong(ptr %src, ptr %dst, i64 %n) {
; DEFAULT-LABEL: define void @ping_pong(
; DEFAULT-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[FROM:%.*]] = phi ptr [ [[SRC]], %[[ENTRY]] ], [ [[TO:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[TO]] = phi ptr [ [[DST]], %[[ENTRY]] ], [ [[FROM]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[V:%.*]] = load i64, ptr [[FROM]], align 8
; DEFAULT-NEXT:    [[W:%.*]] = add i64 [[V]], 1
; DEFAULT-NEXT:    store i64 [[W]], ptr [[TO]], align 8
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @ping_pong(
; CHAIN-SAME: ptr [[SRC:%.*]], ptr [[DST:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; CHAIN-NEXT:    [[XTRAITER:%.*]] = and i64 [[N]], 1
; CHAIN-NEXT:    [[TMP1:%.*]] = icmp ult i64 [[TMP0]], 1
; CHAIN-NEXT:    br i1 [[TMP1]], label %[[LOOP_EPIL_PREHEADER:.*]], label %[[ENTRY_NEW:.*]]
; CHAIN:       [[ENTRY_NEW]]:
; CHAIN-NEXT:    [[UNROLL_ITER:%.*]] = sub i64 [[N]], [[XTRAITER]]
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY_NEW]] ], [ [[I_NEXT_1:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[NITER:%.*]] = phi i64 [ 0, %[[ENTRY_NEW]] ], [ [[NITER_NEXT_1:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[V:%.*]] = load i64, ptr [[SRC]], align 8
; CHAIN-NEXT:    [[W:%.*]] = add i64 [[V]], 1
; CHAIN-NEXT:    store i64 [[W]], ptr [[DST]], align 8
; CHAIN-NEXT:    [[V_1:%.*]] = load i64, ptr [[DST]], align 8
; CHAIN-NEXT:    [[W_1:%.*]] = add i64 [[V_1]], 1
; CHAIN-NEXT:    store i64 [[W_1]], ptr [[SRC]], align 8
; CHAIN-NEXT:    [[I_NEXT_1]] = add nuw i64 [[I]], 2
; CHAIN-NEXT:    [[NITER_NEXT_1]] = add i64 [[NITER]], 2
; CHAIN-NEXT:    [[NITER_NCMP_1:%.*]] = icmp eq i64 [[NITER_NEXT_1]], [[UNROLL_ITER]]
; CHAIN-NEXT:    br i1 [[NITER_NCMP_1]], label %[[EXIT_UNR_LCSSA:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT_UNR_LCSSA]]:
; CHAIN-NEXT:    [[FROM_UNR:%.*]] = phi ptr [ [[SRC]], %[[LOOP]] ]
; CHAIN-NEXT:    [[TO_UNR:%.*]] = phi ptr [ [[DST]], %[[LOOP]] ]
; CHAIN-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i64 [[XTRAITER]], 0
; CHAIN-NEXT:    br i1 [[LCMP_MOD]], label %[[LOOP_EPIL_PREHEADER]], label %[[EXIT:.*]]
; CHAIN:       [[LOOP_EPIL_PREHEADER]]:
; CHAIN-NEXT:    [[FROM_EPIL_INIT:%.*]] = phi ptr [ [[SRC]], %[[ENTRY]] ], [ [[FROM_UNR]], %[[EXIT_UNR_LCSSA]] ]
; CHAIN-NEXT:    [[TO_EPIL_INIT:%.*]] = phi ptr [ [[DST]], %[[ENTRY]] ], [ [[TO_UNR]], %[[EXIT_UNR_LCSSA]] ]
; CHAIN-NEXT:    [[LCMP_MOD1:%.*]] = icmp ne i64 [[XTRAITER]], 0
; CHAIN-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD1]])
; CHAIN-NEXT:    br label %[[LOOP_EPIL:.*]]
; CHAIN:       [[LOOP_EPIL]]:
; CHAIN-NEXT:    [[V_EPIL:%.*]] = load i64, ptr [[FROM_EPIL_INIT]], align 8
; CHAIN-NEXT:    [[W_EPIL:%.*]] = add i64 [[V_EPIL]], 1
; CHAIN-NEXT:    store i64 [[W_EPIL]], ptr [[TO_EPIL_INIT]], align 8
; CHAIN-NEXT:    br label %[[EXIT]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %from = phi ptr [ %src, %entry ], [ %to, %loop ]
  %to = phi ptr [ %dst, %entry ], [ %from, %loop ]
  %v = load i64, ptr %from
  %w = add i64 %v, 1
  store i64 %w, ptr %to
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; An induction variable used after its next value is computed is left alone:
; loop strength reduction decides what it costs, not the order here.
define void @fill(ptr %p, i64 %n) {
; DEFAULT-LABEL: define void @fill(
; DEFAULT-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; DEFAULT-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; DEFAULT-NEXT:    store i64 [[I]], ptr [[ADDR]], align 8
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @fill(
; CHAIN-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHAIN-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHAIN-NEXT:    store i64 [[I]], ptr [[ADDR]], align 8
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %i.next = add nuw i64 %i, 1
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  store i64 %i, ptr %addr
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; A chain of a type scalar evolution cannot describe is not an induction
; variable, and is unrolled like any other.
define double @halve(double %x, ptr %out) {
; DEFAULT-LABEL: define double @halve(
; DEFAULT-SAME: double [[X:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[V:%.*]] = phi double [ [[X]], %[[ENTRY]] ], [ [[HALF:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[HALF]] = fmul double [[V]], 5.000000e-01
; DEFAULT-NEXT:    store double [[V]], ptr [[OUT]], align 8
; DEFAULT-NEXT:    [[DONE:%.*]] = fcmp olt double [[HALF]], 1.000000e+00
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    [[HALF_LCSSA:%.*]] = phi double [ [[HALF]], %[[LOOP]] ]
; DEFAULT-NEXT:    ret double [[HALF_LCSSA]]
;
; CHAIN-LABEL: define double @halve(
; CHAIN-SAME: double [[X:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[V:%.*]] = phi double [ [[X]], %[[ENTRY]] ], [ [[HALF_1:%.*]], %[[LOOP_1:.*]] ]
; CHAIN-NEXT:    [[HALF:%.*]] = fmul double [[V]], 5.000000e-01
; CHAIN-NEXT:    store double [[V]], ptr [[OUT]], align 8
; CHAIN-NEXT:    [[DONE:%.*]] = fcmp olt double [[HALF]], 1.000000e+00
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHAIN:       [[LOOP_1]]:
; CHAIN-NEXT:    [[HALF_1]] = fmul double [[HALF]], 5.000000e-01
; CHAIN-NEXT:    store double [[HALF]], ptr [[OUT]], align 8
; CHAIN-NEXT:    [[DONE_1:%.*]] = fcmp olt double [[HALF_1]], 1.000000e+00
; CHAIN-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    [[HALF_LCSSA:%.*]] = phi double [ [[HALF]], %[[LOOP]] ], [ [[HALF_1]], %[[LOOP_1]] ]
; CHAIN-NEXT:    ret double [[HALF_LCSSA]]
;
entry:
  br label %loop

loop:
  %v = phi double [ %x, %entry ], [ %half, %loop ]
  %half = fmul double %v, 5.000000e-01
  store double %v, ptr %out
  %done = fcmp olt double %half, 1.000000e+00
  br i1 %done, label %exit, label %loop

exit:
  ret double %half
}

; Searching a list uses the current node before loading the next one, which
; can then take its register, so there is nothing to remove.
define ptr @find(ptr %list, i64 %key) {
; DEFAULT-LABEL: define ptr @find(
; DEFAULT-SAME: ptr [[LIST:%.*]], i64 [[KEY:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LATCH:.*]] ]
; DEFAULT-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 8
; DEFAULT-NEXT:    [[VAL:%.*]] = load i64, ptr [[FIELD]], align 8
; DEFAULT-NEXT:    [[FOUND:%.*]] = icmp eq i64 [[VAL]], [[KEY]]
; DEFAULT-NEXT:    br i1 [[FOUND]], label %[[EXIT:.*]], label %[[LATCH]]
; DEFAULT:       [[LATCH]]:
; DEFAULT-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    [[RESULT:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ null, %[[LATCH]] ]
; DEFAULT-NEXT:    ret ptr [[RESULT]]
;
; CHAIN-LABEL: define ptr @find(
; CHAIN-SAME: ptr [[LIST:%.*]], i64 [[KEY:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LATCH:.*]] ]
; CHAIN-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i64 8
; CHAIN-NEXT:    [[VAL:%.*]] = load i64, ptr [[FIELD]], align 8
; CHAIN-NEXT:    [[FOUND:%.*]] = icmp eq i64 [[VAL]], [[KEY]]
; CHAIN-NEXT:    br i1 [[FOUND]], label %[[EXIT:.*]], label %[[LATCH]]
; CHAIN:       [[LATCH]]:
; CHAIN-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    [[RESULT:%.*]] = phi ptr [ [[CUR]], %[[LOOP]] ], [ null, %[[LATCH]] ]
; CHAIN-NEXT:    ret ptr [[RESULT]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %latch ]
  %field = getelementptr inbounds i8, ptr %cur, i64 8
  %val = load i64, ptr %field
  %found = icmp eq i64 %val, %key
  br i1 %found, label %exit, label %latch

latch:
  %next = load ptr, ptr %cur
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  %result = phi ptr [ %cur, %loop ], [ null, %latch ]
  ret ptr %result
}

; With a constant trip count that is not a multiple of the period, the count
; would be lowered to one that divides it, which leaves the rotation in place.
define void @shift_by_1000(ptr %p) {
; DEFAULT-LABEL: define void @shift_by_1000(
; DEFAULT-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[CUR:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[CUR]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; DEFAULT-NEXT:    [[V]] = load i64, ptr [[ADDR]], align 8
; DEFAULT-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 8
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], 1000
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @shift_by_1000(
; CHAIN-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[CUR:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[CUR]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHAIN-NEXT:    [[V]] = load i64, ptr [[ADDR]], align 8
; CHAIN-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 8
; CHAIN-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], 1000
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %prev = phi i64 [ 0, %entry ], [ %cur, %loop ]
  %cur = phi i64 [ 1, %entry ], [ %v, %loop ]
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  %v = load i64, ptr %addr
  store i64 %prev, ptr %addr
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, 1000
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; The same loop with a trip count that is a multiple of three.
define void @shift_by_999(ptr %p) {
; DEFAULT-LABEL: define void @shift_by_999(
; DEFAULT-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[CUR:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[CUR]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; DEFAULT-NEXT:    [[V]] = load i64, ptr [[ADDR]], align 8
; DEFAULT-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 8
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], 999
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @shift_by_999(
; CHAIN-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT_2:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[V_1:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[CUR:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V_2:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHAIN-NEXT:    [[V:%.*]] = load i64, ptr [[ADDR]], align 8
; CHAIN-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 8
; CHAIN-NEXT:    [[I_NEXT:%.*]] = add nuw nsw i64 [[I]], 1
; CHAIN-NEXT:    [[ADDR_1:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I_NEXT]]
; CHAIN-NEXT:    [[V_1]] = load i64, ptr [[ADDR_1]], align 8
; CHAIN-NEXT:    store i64 [[CUR]], ptr [[ADDR_1]], align 8
; CHAIN-NEXT:    [[I_NEXT_1:%.*]] = add nuw nsw i64 [[I]], 2
; CHAIN-NEXT:    [[ADDR_2:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I_NEXT_1]]
; CHAIN-NEXT:    [[V_2]] = load i64, ptr [[ADDR_2]], align 8
; CHAIN-NEXT:    store i64 [[V]], ptr [[ADDR_2]], align 8
; CHAIN-NEXT:    [[I_NEXT_2]] = add nuw nsw i64 [[I]], 3
; CHAIN-NEXT:    [[DONE_2:%.*]] = icmp eq i64 [[I_NEXT_2]], 999
; CHAIN-NEXT:    br i1 [[DONE_2]], label %[[EXIT:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %prev = phi i64 [ 0, %entry ], [ %cur, %loop ]
  %cur = phi i64 [ 1, %entry ], [ %v, %loop ]
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  %v = load i64, ptr %addr
  store i64 %prev, ptr %addr
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, 999
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; With a trip count only known at run time, the remainder of a division by
; three would cost more than the copies.
define void @shift_by_n(ptr %p, i64 %n) {
; DEFAULT-LABEL: define void @shift_by_n(
; DEFAULT-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[CUR:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[CUR]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; DEFAULT-NEXT:    [[V]] = load i64, ptr [[ADDR]], align 8
; DEFAULT-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 8
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @shift_by_n(
; CHAIN-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[CUR:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[CUR]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V:%.*]], %[[LOOP]] ]
; CHAIN-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHAIN-NEXT:    [[V]] = load i64, ptr [[ADDR]], align 8
; CHAIN-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 8
; CHAIN-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %prev = phi i64 [ 0, %entry ], [ %cur, %loop ]
  %cur = phi i64 [ 1, %entry ], [ %v, %loop ]
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  %v = load i64, ptr %addr
  store i64 %prev, ptr %addr
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Three phis rotating among themselves are a cycle with a period of three.
define void @rotate(ptr %p, ptr %q, ptr %r, ptr %out) {
; DEFAULT-LABEL: define void @rotate(
; DEFAULT-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[A:%.*]] = phi ptr [ [[P]], %[[ENTRY]] ], [ [[B:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[B]] = phi ptr [ [[Q]], %[[ENTRY]] ], [ [[C:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[C]] = phi ptr [ [[R]], %[[ENTRY]] ], [ [[A]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[V:%.*]] = load i64, ptr [[A]], align 8
; DEFAULT-NEXT:    store i64 [[V]], ptr [[OUT]], align 8
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V]], 0
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @rotate(
; CHAIN-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*:]]
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[V:%.*]] = load i64, ptr [[P]], align 8
; CHAIN-NEXT:    store i64 [[V]], ptr [[OUT]], align 8
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V]], 0
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; CHAIN:       [[LOOP_1]]:
; CHAIN-NEXT:    [[V_1:%.*]] = load i64, ptr [[Q]], align 8
; CHAIN-NEXT:    store i64 [[V_1]], ptr [[OUT]], align 8
; CHAIN-NEXT:    [[DONE_1:%.*]] = icmp eq i64 [[V_1]], 0
; CHAIN-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2:.*]]
; CHAIN:       [[LOOP_2]]:
; CHAIN-NEXT:    [[V_2:%.*]] = load i64, ptr [[R]], align 8
; CHAIN-NEXT:    store i64 [[V_2]], ptr [[OUT]], align 8
; CHAIN-NEXT:    [[DONE_2:%.*]] = icmp eq i64 [[V_2]], 0
; CHAIN-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %a = phi ptr [ %p, %entry ], [ %b, %loop ]
  %b = phi ptr [ %q, %entry ], [ %c, %loop ]
  %c = phi ptr [ %r, %entry ], [ %a, %loop ]
  %v = load i64, ptr %a
  store i64 %v, ptr %out
  %done = icmp eq i64 %v, 0
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; A swap and a chain of period three would need six copies of the body, so the
; loop is unrolled by the longer period and the swap is left alone.
define ptr @reverse_and_swap(ptr %list, ptr %x, ptr %y) {
; DEFAULT-LABEL: define ptr @reverse_and_swap(
; DEFAULT-SAME: ptr [[LIST:%.*]], ptr [[X:%.*]], ptr [[Y:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[CUR]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[FROM:%.*]] = phi ptr [ [[X]], %[[ENTRY]] ], [ [[TO:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[TO]] = phi ptr [ [[Y]], %[[ENTRY]] ], [ [[FROM]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 8
; DEFAULT-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; DEFAULT-NEXT:    store ptr [[CUR]], ptr [[FROM]], align 8
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    [[TO_LCSSA:%.*]] = phi ptr [ [[TO]], %[[LOOP]] ]
; DEFAULT-NEXT:    ret ptr [[TO_LCSSA]]
;
; CHAIN-LABEL: define ptr @reverse_and_swap(
; CHAIN-SAME: ptr [[LIST:%.*]], ptr [[X:%.*]], ptr [[Y:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_2:%.*]], %[[LOOP_2:.*]] ]
; CHAIN-NEXT:    [[PREV:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_2]] ]
; CHAIN-NEXT:    [[FROM:%.*]] = phi ptr [ [[X]], %[[ENTRY]] ], [ [[TO:%.*]], %[[LOOP_2]] ]
; CHAIN-NEXT:    [[TO]] = phi ptr [ [[Y]], %[[ENTRY]] ], [ [[FROM]], %[[LOOP_2]] ]
; CHAIN-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 8
; CHAIN-NEXT:    store ptr [[PREV]], ptr [[CUR]], align 8
; CHAIN-NEXT:    store ptr [[CUR]], ptr [[FROM]], align 8
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; CHAIN:       [[LOOP_1]]:
; CHAIN-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 8
; CHAIN-NEXT:    store ptr [[CUR]], ptr [[NEXT]], align 8
; CHAIN-NEXT:    store ptr [[NEXT]], ptr [[TO]], align 8
; CHAIN-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHAIN-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2]]
; CHAIN:       [[LOOP_2]]:
; CHAIN-NEXT:    [[NEXT_2]] = load ptr, ptr [[NEXT_1]], align 8
; CHAIN-NEXT:    store ptr [[NEXT]], ptr [[NEXT_1]], align 8
; CHAIN-NEXT:    store ptr [[NEXT_1]], ptr [[FROM]], align 8
; CHAIN-NEXT:    [[DONE_2:%.*]] = icmp eq ptr [[NEXT_2]], null
; CHAIN-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    [[TO_LCSSA:%.*]] = phi ptr [ [[TO]], %[[LOOP]] ], [ [[FROM]], %[[LOOP_1]] ], [ [[TO]], %[[LOOP_2]] ]
; CHAIN-NEXT:    ret ptr [[TO_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %prev = phi ptr [ null, %entry ], [ %cur, %loop ]
  %from = phi ptr [ %x, %entry ], [ %to, %loop ]
  %to = phi ptr [ %y, %entry ], [ %from, %loop ]
  %next = load ptr, ptr %cur
  store ptr %prev, ptr %cur
  store ptr %cur, ptr %from
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret ptr %to
}

; A value that comes from outside the loop does not rotate.
define void @keep(ptr %list, ptr %x) {
; DEFAULT-LABEL: define void @keep(
; DEFAULT-SAME: ptr [[LIST:%.*]], ptr [[X:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[LOOP_PEEL_BEGIN:.*]]
; DEFAULT:       [[LOOP_PEEL_BEGIN]]:
; DEFAULT-NEXT:    br label %[[LOOP_PEEL:.*]]
; DEFAULT:       [[LOOP_PEEL]]:
; DEFAULT-NEXT:    [[V_PEEL:%.*]] = load i64, ptr [[LIST]], align 8
; DEFAULT-NEXT:    store ptr null, ptr [[LIST]], align 8
; DEFAULT-NEXT:    [[DONE_PEEL:%.*]] = icmp eq i64 [[V_PEEL]], 0
; DEFAULT-NEXT:    br i1 [[DONE_PEEL]], label %[[EXIT:.*]], label %[[LOOP_PEEL_NEXT:.*]]
; DEFAULT:       [[LOOP_PEEL_NEXT]]:
; DEFAULT-NEXT:    br label %[[LOOP_PEEL2:.*]]
; DEFAULT:       [[LOOP_PEEL2]]:
; DEFAULT-NEXT:    [[V_PEEL3:%.*]] = load i64, ptr [[X]], align 8
; DEFAULT-NEXT:    store ptr [[LIST]], ptr [[X]], align 8
; DEFAULT-NEXT:    [[DONE_PEEL4:%.*]] = icmp eq i64 [[V_PEEL3]], 0
; DEFAULT-NEXT:    br i1 [[DONE_PEEL4]], label %[[EXIT]], label %[[LOOP_PEEL_NEXT1:.*]]
; DEFAULT:       [[LOOP_PEEL_NEXT1]]:
; DEFAULT-NEXT:    br label %[[LOOP_PEEL_NEXT5:.*]]
; DEFAULT:       [[LOOP_PEEL_NEXT5]]:
; DEFAULT-NEXT:    br label %[[ENTRY_PEEL_NEWPH:.*]]
; DEFAULT:       [[ENTRY_PEEL_NEWPH]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[V:%.*]] = load i64, ptr [[X]], align 8
; DEFAULT-NEXT:    store ptr [[X]], ptr [[X]], align 8
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V]], 0
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP0:![0-9]+]]
; DEFAULT:       [[EXIT_LOOPEXIT]]:
; DEFAULT-NEXT:    br label %[[EXIT]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @keep(
; CHAIN-SAME: ptr [[LIST:%.*]], ptr [[X:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*:]]
; CHAIN-NEXT:    br label %[[LOOP_PEEL_BEGIN:.*]]
; CHAIN:       [[LOOP_PEEL_BEGIN]]:
; CHAIN-NEXT:    br label %[[LOOP_PEEL:.*]]
; CHAIN:       [[LOOP_PEEL]]:
; CHAIN-NEXT:    [[V_PEEL:%.*]] = load i64, ptr [[LIST]], align 8
; CHAIN-NEXT:    store ptr null, ptr [[LIST]], align 8
; CHAIN-NEXT:    [[DONE_PEEL:%.*]] = icmp eq i64 [[V_PEEL]], 0
; CHAIN-NEXT:    br i1 [[DONE_PEEL]], label %[[EXIT:.*]], label %[[LOOP_PEEL_NEXT:.*]]
; CHAIN:       [[LOOP_PEEL_NEXT]]:
; CHAIN-NEXT:    br label %[[LOOP_PEEL2:.*]]
; CHAIN:       [[LOOP_PEEL2]]:
; CHAIN-NEXT:    [[V_PEEL3:%.*]] = load i64, ptr [[X]], align 8
; CHAIN-NEXT:    store ptr [[LIST]], ptr [[X]], align 8
; CHAIN-NEXT:    [[DONE_PEEL4:%.*]] = icmp eq i64 [[V_PEEL3]], 0
; CHAIN-NEXT:    br i1 [[DONE_PEEL4]], label %[[EXIT]], label %[[LOOP_PEEL_NEXT1:.*]]
; CHAIN:       [[LOOP_PEEL_NEXT1]]:
; CHAIN-NEXT:    br label %[[LOOP_PEEL_NEXT5:.*]]
; CHAIN:       [[LOOP_PEEL_NEXT5]]:
; CHAIN-NEXT:    br label %[[ENTRY_PEEL_NEWPH:.*]]
; CHAIN:       [[ENTRY_PEEL_NEWPH]]:
; CHAIN-NEXT:    br label %[[LOOP:.*]]
; CHAIN:       [[LOOP]]:
; CHAIN-NEXT:    [[V:%.*]] = load i64, ptr [[X]], align 8
; CHAIN-NEXT:    store ptr [[X]], ptr [[X]], align 8
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V]], 0
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP]], !llvm.loop [[LOOP0:![0-9]+]]
; CHAIN:       [[EXIT_LOOPEXIT]]:
; CHAIN-NEXT:    br label %[[EXIT]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %x, %loop ]
  %prev = phi ptr [ null, %entry ], [ %cur, %loop ]
  %v = load i64, ptr %cur
  store ptr %prev, ptr %cur
  %done = icmp eq i64 %v, 0
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Unrolling an outer loop would copy the inner one to save a swap.
define void @outer(ptr %p, ptr %q, i64 %n, i64 %m) {
; DEFAULT-LABEL: define void @outer(
; DEFAULT-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i64 [[N:%.*]], i64 [[M:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    br label %[[OUTER:.*]]
; DEFAULT:       [[OUTER]]:
; DEFAULT-NEXT:    [[A:%.*]] = phi ptr [ [[P]], %[[ENTRY]] ], [ [[B:%.*]], %[[OUTER_LATCH:.*]] ]
; DEFAULT-NEXT:    [[B]] = phi ptr [ [[Q]], %[[ENTRY]] ], [ [[A]], %[[OUTER_LATCH]] ]
; DEFAULT-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[J_NEXT:%.*]], %[[OUTER_LATCH]] ]
; DEFAULT-NEXT:    br label %[[INNER:.*]]
; DEFAULT:       [[INNER]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[I_NEXT:%.*]], %[[INNER]] ]
; DEFAULT-NEXT:    [[SRC:%.*]] = getelementptr i64, ptr [[A]], i64 [[I]]
; DEFAULT-NEXT:    [[V:%.*]] = load i64, ptr [[SRC]], align 8
; DEFAULT-NEXT:    [[DST:%.*]] = getelementptr i64, ptr [[B]], i64 [[I]]
; DEFAULT-NEXT:    store i64 [[V]], ptr [[DST]], align 8
; DEFAULT-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; DEFAULT-NEXT:    [[INNER_DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[M]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE]], label %[[OUTER_LATCH]], label %[[INNER]]
; DEFAULT:       [[OUTER_LATCH]]:
; DEFAULT-NEXT:    [[J_NEXT]] = add i64 [[J]], 1
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i64 [[J_NEXT]], [[N]]
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[OUTER]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; CHAIN-LABEL: define void @outer(
; CHAIN-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i64 [[N:%.*]], i64 [[M:%.*]]) #[[ATTR0]] {
; CHAIN-NEXT:  [[ENTRY:.*]]:
; CHAIN-NEXT:    br label %[[OUTER:.*]]
; CHAIN:       [[OUTER]]:
; CHAIN-NEXT:    [[A:%.*]] = phi ptr [ [[P]], %[[ENTRY]] ], [ [[B:%.*]], %[[OUTER_LATCH:.*]] ]
; CHAIN-NEXT:    [[B]] = phi ptr [ [[Q]], %[[ENTRY]] ], [ [[A]], %[[OUTER_LATCH]] ]
; CHAIN-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[J_NEXT:%.*]], %[[OUTER_LATCH]] ]
; CHAIN-NEXT:    br label %[[INNER:.*]]
; CHAIN:       [[INNER]]:
; CHAIN-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[OUTER]] ], [ [[I_NEXT:%.*]], %[[INNER]] ]
; CHAIN-NEXT:    [[SRC:%.*]] = getelementptr i64, ptr [[A]], i64 [[I]]
; CHAIN-NEXT:    [[V:%.*]] = load i64, ptr [[SRC]], align 8
; CHAIN-NEXT:    [[DST:%.*]] = getelementptr i64, ptr [[B]], i64 [[I]]
; CHAIN-NEXT:    store i64 [[V]], ptr [[DST]], align 8
; CHAIN-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHAIN-NEXT:    [[INNER_DONE:%.*]] = icmp eq i64 [[I_NEXT]], [[M]]
; CHAIN-NEXT:    br i1 [[INNER_DONE]], label %[[OUTER_LATCH]], label %[[INNER]]
; CHAIN:       [[OUTER_LATCH]]:
; CHAIN-NEXT:    [[J_NEXT]] = add i64 [[J]], 1
; CHAIN-NEXT:    [[DONE:%.*]] = icmp eq i64 [[J_NEXT]], [[N]]
; CHAIN-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[OUTER]]
; CHAIN:       [[EXIT]]:
; CHAIN-NEXT:    ret void
;
entry:
  br label %outer

outer:
  %a = phi ptr [ %p, %entry ], [ %b, %outer.latch ]
  %b = phi ptr [ %q, %entry ], [ %a, %outer.latch ]
  %j = phi i64 [ 0, %entry ], [ %j.next, %outer.latch ]
  br label %inner

inner:
  %i = phi i64 [ 0, %outer ], [ %i.next, %inner ]
  %src = getelementptr i64, ptr %a, i64 %i
  %v = load i64, ptr %src
  %dst = getelementptr i64, ptr %b, i64 %i
  store i64 %v, ptr %dst
  %i.next = add i64 %i, 1
  %inner.done = icmp eq i64 %i.next, %m
  br i1 %inner.done, label %outer.latch, label %inner

outer.latch:
  %j.next = add i64 %j, 1
  %done = icmp eq i64 %j.next, %n
  br i1 %done, label %exit, label %outer

exit:
  ret void
}
;.
; DEFAULT: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; DEFAULT: [[META1]] = !{!"llvm.loop.peeled.count", i32 2}
;.
; CHAIN: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHAIN: [[META1]] = !{!"llvm.loop.peeled.count", i32 2}
;.
