; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; A loop that the count removing the copies of its shift chains would unroll
; completely is left to full unrolling, even where full unrolling turns it down.
; RUN: opt -S -passes=loop-unroll -unroll-shift-chains -unroll-full-max-count=2 \
; RUN:   < %s | FileCheck %s

; A chain whose values live for three iterations, in a loop that runs three
; times.
define void @shift_by_3(ptr %p) {
; CHECK-LABEL: define void @shift_by_3(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[CUR:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CUR]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHECK-NEXT:    [[V]] = load i64, ptr [[ADDR]], align 4
; CHECK-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT]] = add nuw i64 [[I]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], 3
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %prev = phi i64 [ 0, %entry ], [ %cur, %loop ]
  %cur = phi i64 [ 1, %entry ], [ %v, %loop ]
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  %v = load i64, ptr %addr
  store i64 %prev, ptr %addr
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, 3
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; The same loop running four times is unrolled by three, keeping the exit that
; can be taken, rather than completely by four.
define void @shift_by_4(ptr %p) {
; CHECK-LABEL: define void @shift_by_4(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT_2:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[V_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[CUR:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V_2:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[ADDR]], align 4
; CHECK-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT:%.*]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[I_NEXT]], 4
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[ADDR_1:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I_NEXT]]
; CHECK-NEXT:    [[V_1]] = load i64, ptr [[ADDR_1]], align 4
; CHECK-NEXT:    store i64 [[CUR]], ptr [[ADDR_1]], align 4
; CHECK-NEXT:    [[I_NEXT_1:%.*]] = add nuw nsw i64 [[I]], 2
; CHECK-NEXT:    [[ADDR_2:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I_NEXT_1]]
; CHECK-NEXT:    [[V_2]] = load i64, ptr [[ADDR_2]], align 4
; CHECK-NEXT:    store i64 [[V]], ptr [[ADDR_2]], align 4
; CHECK-NEXT:    [[I_NEXT_2]] = add nuw nsw i64 [[I]], 3
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %prev = phi i64 [ 0, %entry ], [ %cur, %loop ]
  %cur = phi i64 [ 1, %entry ], [ %v, %loop ]
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  %v = load i64, ptr %addr
  store i64 %prev, ptr %addr
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, 4
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; The same loop running six times is unrolled by three.
define void @shift_by_6(ptr %p) {
; CHECK-LABEL: define void @shift_by_6(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_NEXT_2:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PREV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[V_1:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CUR:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[V_2:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I]]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[ADDR]], align 4
; CHECK-NEXT:    store i64 [[PREV]], ptr [[ADDR]], align 4
; CHECK-NEXT:    [[I_NEXT:%.*]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[ADDR_1:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I_NEXT]]
; CHECK-NEXT:    [[V_1]] = load i64, ptr [[ADDR_1]], align 4
; CHECK-NEXT:    store i64 [[CUR]], ptr [[ADDR_1]], align 4
; CHECK-NEXT:    [[I_NEXT_1:%.*]] = add nuw nsw i64 [[I]], 2
; CHECK-NEXT:    [[ADDR_2:%.*]] = getelementptr inbounds i64, ptr [[P]], i64 [[I_NEXT_1]]
; CHECK-NEXT:    [[V_2]] = load i64, ptr [[ADDR_2]], align 4
; CHECK-NEXT:    store i64 [[V]], ptr [[ADDR_2]], align 4
; CHECK-NEXT:    [[I_NEXT_2]] = add nuw nsw i64 [[I]], 3
; CHECK-NEXT:    [[DONE_2:%.*]] = icmp eq i64 [[I_NEXT_2]], 6
; CHECK-NEXT:    br i1 [[DONE_2]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %prev = phi i64 [ 0, %entry ], [ %cur, %loop ]
  %cur = phi i64 [ 1, %entry ], [ %v, %loop ]
  %addr = getelementptr inbounds i64, ptr %p, i64 %i
  %v = load i64, ptr %addr
  store i64 %prev, ptr %addr
  %i.next = add nuw i64 %i, 1
  %done = icmp eq i64 %i.next, 6
  br i1 %done, label %exit, label %loop

exit:
  ret void
}
