; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; A word loaded from the node a list walk drops, next to the word loaded for the
; next node, is loaded together with it by LDRD, so it does not keep the node
; live, and the walk needs no copy. Other loads from the node do.
; RUN: opt -S -passes=loop-unroll -mtriple=armv8r -unroll-shift-chains < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,V7
; RUN: opt -S -passes=loop-unroll -mtriple=thumbv8r -unroll-shift-chains < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,V7
; Before ARMv7, LDRD needs a doubleword alignment under strict alignment.
; RUN: opt -S -passes=loop-unroll -mtriple=armv6 -unroll-shift-chains < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,V6
; There is no LDRD before ARMv5TE, or in Thumb1.
; RUN: opt -S -passes=loop-unroll -mtriple=armv5t -unroll-shift-chains < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,V5
; RUN: opt -S -passes=loop-unroll -mtriple=thumbv5te -unroll-shift-chains < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,V5

target datalayout = "e-m:e-p:32:32-p1:64:64:64:64-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"

define i32 @sum(ptr %list) {
; V7-LABEL: define i32 @sum(
; V7-SAME: ptr [[LIST:%.*]]) {
; V7-NEXT:  [[ENTRY:.*]]:
; V7-NEXT:    br label %[[LOOP:.*]]
; V7:       [[LOOP]]:
; V7-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; V7-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP]] ]
; V7-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 4
; V7-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; V7-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; V7-NEXT:    [[ACC_NEXT]] = add i32 [[ACC]], [[V]]
; V7-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; V7-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; V7:       [[EXIT]]:
; V7-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ]
; V7-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
; V6-LABEL: define i32 @sum(
; V6-SAME: ptr [[LIST:%.*]]) {
; V6-NEXT:  [[ENTRY:.*]]:
; V6-NEXT:    br label %[[LOOP:.*]]
; V6:       [[LOOP]]:
; V6-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; V6-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP]] ]
; V6-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 4
; V6-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; V6-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; V6-NEXT:    [[ACC_NEXT]] = add i32 [[ACC]], [[V]]
; V6-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; V6-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; V6:       [[EXIT]]:
; V6-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ]
; V6-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
; V5-LABEL: define i32 @sum(
; V5-SAME: ptr [[LIST:%.*]]) {
; V5-NEXT:  [[ENTRY:.*]]:
; V5-NEXT:    br label %[[LOOP:.*]]
; V5:       [[LOOP]]:
; V5-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; V5-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; V5-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; V5-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; V5-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; V5-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; V5-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; V5-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; V5:       [[LOOP_1]]:
; V5-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; V5-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; V5-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; V5-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; V5-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; V5-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; V5:       [[EXIT]]:
; V5-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; V5-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %next = load ptr, ptr %cur, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load i32, ptr %field, align 4
  %acc.next = add i32 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; The same, with strict alignment.
define i32 @sum_strict(ptr %list) #0 {
; V7-LABEL: define i32 @sum_strict(
; V7-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; V7-NEXT:  [[ENTRY:.*]]:
; V7-NEXT:    br label %[[LOOP:.*]]
; V7:       [[LOOP]]:
; V7-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT:%.*]], %[[LOOP]] ]
; V7-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT:%.*]], %[[LOOP]] ]
; V7-NEXT:    [[NEXT]] = load ptr, ptr [[CUR]], align 4
; V7-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; V7-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; V7-NEXT:    [[ACC_NEXT]] = add i32 [[ACC]], [[V]]
; V7-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; V7-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP]]
; V7:       [[EXIT]]:
; V7-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ]
; V7-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
; V6-LABEL: define i32 @sum_strict(
; V6-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; V6-NEXT:  [[ENTRY:.*]]:
; V6-NEXT:    br label %[[LOOP:.*]]
; V6:       [[LOOP]]:
; V6-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; V6-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; V6-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; V6-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; V6-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; V6-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; V6-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; V6-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; V6:       [[LOOP_1]]:
; V6-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; V6-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; V6-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; V6-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; V6-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; V6-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; V6:       [[EXIT]]:
; V6-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; V6-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
; V5-LABEL: define i32 @sum_strict(
; V5-SAME: ptr [[LIST:%.*]]) #[[ATTR0:[0-9]+]] {
; V5-NEXT:  [[ENTRY:.*]]:
; V5-NEXT:    br label %[[LOOP:.*]]
; V5:       [[LOOP]]:
; V5-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; V5-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; V5-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; V5-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; V5-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; V5-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; V5-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; V5-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; V5:       [[LOOP_1]]:
; V5-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; V5-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; V5-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; V5-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; V5-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; V5-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; V5:       [[EXIT]]:
; V5-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; V5-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %next = load ptr, ptr %cur, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load i32, ptr %field, align 4
  %acc.next = add i32 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; The word is not next to the next pointer.
define i32 @sum_far(ptr %list) {
; CHECK-LABEL: define i32 @sum_far(
; CHECK-SAME: ptr [[LIST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 12
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 12
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %next = load ptr, ptr %cur, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 12
  %v = load i32, ptr %field, align 4
  %acc.next = add i32 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; The field next to the next pointer is not a word.
define i32 @sum_narrow(ptr %list) {
; CHECK-LABEL: define i32 @sum_narrow(
; CHECK-SAME: ptr [[LIST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; CHECK-NEXT:    [[V:%.*]] = load i16, ptr [[FIELD]], align 2
; CHECK-NEXT:    [[W:%.*]] = zext i16 [[V]] to i32
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[W]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; CHECK-NEXT:    [[V_1:%.*]] = load i16, ptr [[FIELD_1]], align 2
; CHECK-NEXT:    [[W_1:%.*]] = zext i16 [[V_1]] to i32
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[W_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %next = load ptr, ptr %cur, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load i16, ptr %field, align 2
  %w = zext i16 %v to i32
  %acc.next = add i32 %acc, %w
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; A store between the two loads keeps them apart.
define i32 @sum_stored(ptr %list, ptr %out) {
; CHECK-LABEL: define i32 @sum_stored(
; CHECK-SAME: ptr [[LIST:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; CHECK-NEXT:    store i32 [[ACC]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; CHECK-NEXT:    store i32 [[ACC_NEXT]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %next = load ptr, ptr %cur, align 4
  store i32 %acc, ptr %out, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load i32, ptr %field, align 4
  %acc.next = add i32 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; LDRD needs the lower of the two words to be aligned to a word.
define i32 @sum_unaligned(ptr %list) {
; CHECK-LABEL: define i32 @sum_unaligned(
; CHECK-SAME: ptr [[LIST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 2
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 2
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %next = load ptr, ptr %cur, align 2
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load i32, ptr %field, align 4
  %acc.next = add i32 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; Only one of two words next to the next pointer is loaded with it; the other
; keeps the node live.
define i32 @sum_both_sides(ptr %list) {
; CHECK-LABEL: define i32 @sum_both_sides(
; CHECK-SAME: ptr [[LIST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[NEXT_ADDR:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[NEXT_ADDR]], align 4
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[CUR]], align 4
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 8
; CHECK-NEXT:    [[W:%.*]] = load i32, ptr [[FIELD]], align 4
; CHECK-NEXT:    [[VW:%.*]] = add i32 [[V]], [[W]]
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[VW]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[NEXT_ADDR_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT_ADDR_1]], align 4
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[NEXT]], align 4
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 8
; CHECK-NEXT:    [[W_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; CHECK-NEXT:    [[VW_1:%.*]] = add i32 [[V_1]], [[W_1]]
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[VW_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %next.addr = getelementptr inbounds i8, ptr %cur, i32 4
  %next = load ptr, ptr %next.addr, align 4
  %v = load i32, ptr %cur, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 8
  %w = load i32, ptr %field, align 4
  %vw = add i32 %v, %w
  %acc.next = add i32 %acc, %vw
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; Loads through different address spaces are not loaded together.
define i32 @sum_cast(ptr %list) {
; CHECK-LABEL: define i32 @sum_cast(
; CHECK-SAME: ptr [[LIST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[CUR_CAST:%.*]] = addrspacecast ptr [[CUR]] to ptr addrspace(1)
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr addrspace(1) [[CUR_CAST]], align 4
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[CUR_CAST_1:%.*]] = addrspacecast ptr [[NEXT]] to ptr addrspace(1)
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr addrspace(1) [[CUR_CAST_1]], align 4
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %cur.cast = addrspacecast ptr %cur to ptr addrspace(1)
  %next = load ptr, ptr addrspace(1) %cur.cast, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load i32, ptr %field, align 4
  %acc.next = add i32 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; LDRD loads only integer registers, not the floating-point ones a float is
; loaded into.
define void @copy_float(ptr %list, ptr %out) #1 {
; CHECK-LABEL: define void @copy_float(
; CHECK-SAME: ptr [[LIST:%.*]], ptr [[OUT:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; CHECK-NEXT:    [[V:%.*]] = load float, ptr [[FIELD]], align 4
; CHECK-NEXT:    [[ABS:%.*]] = call float @llvm.fabs.f32(float [[V]])
; CHECK-NEXT:    store float [[ABS]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; CHECK-NEXT:    [[V_1:%.*]] = load float, ptr [[FIELD_1]], align 4
; CHECK-NEXT:    [[ABS_1:%.*]] = call float @llvm.fabs.f32(float [[V_1]])
; CHECK-NEXT:    store float [[ABS_1]], ptr [[OUT]], align 4
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %next = load ptr, ptr %cur, align 4
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load float, ptr %field, align 4
  %abs = call float @llvm.fabs.f32(float %v)
  store float %abs, ptr %out, align 4
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

; Loads in different blocks are not paired.
define i32 @sum_split(ptr %list) {
; CHECK-LABEL: define i32 @sum_split(
; CHECK-SAME: ptr [[LIST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LATCH_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LATCH_1]] ]
; CHECK-NEXT:    [[NEXT:%.*]] = load ptr, ptr [[CUR]], align 4
; CHECK-NEXT:    br label %[[LATCH:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 4
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[FIELD]], align 4
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i32 [[ACC]], [[V]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[NEXT_1]] = load ptr, ptr [[NEXT]], align 4
; CHECK-NEXT:    br label %[[LATCH_1]]
; CHECK:       [[LATCH_1]]:
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 4
; CHECK-NEXT:    [[V_1:%.*]] = load i32, ptr [[FIELD_1]], align 4
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i32 [[ACC_NEXT]], [[V_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i32 [ [[ACC_NEXT]], %[[LATCH]] ], [ [[ACC_NEXT_1]], %[[LATCH_1]] ]
; CHECK-NEXT:    ret i32 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %latch ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %latch ]
  %next = load ptr, ptr %cur, align 4
  br label %latch

latch:
  %field = getelementptr inbounds i8, ptr %cur, i32 4
  %v = load i32, ptr %field, align 4
  %acc.next = add i32 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i32 %acc.next
}

; LDRD loads two words, not two doublewords.
define i64 @sum_wide(ptr %list) {
; CHECK-LABEL: define i64 @sum_wide(
; CHECK-SAME: ptr [[LIST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[CUR:%.*]] = phi ptr [ [[LIST]], %[[ENTRY]] ], [ [[NEXT_1:%.*]], %[[LOOP_1:.*]] ]
; CHECK-NEXT:    [[ACC:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[ACC_NEXT_1:%.*]], %[[LOOP_1]] ]
; CHECK-NEXT:    [[RAW:%.*]] = load i64, ptr [[CUR]], align 8
; CHECK-NEXT:    [[RAW_LOW:%.*]] = trunc i64 [[RAW]] to i32
; CHECK-NEXT:    [[NEXT:%.*]] = inttoptr i32 [[RAW_LOW]] to ptr
; CHECK-NEXT:    [[FIELD:%.*]] = getelementptr inbounds i8, ptr [[CUR]], i32 8
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[FIELD]], align 8
; CHECK-NEXT:    [[ACC_NEXT:%.*]] = add i64 [[ACC]], [[V]]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq ptr [[NEXT]], null
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1]]
; CHECK:       [[LOOP_1]]:
; CHECK-NEXT:    [[RAW_1:%.*]] = load i64, ptr [[NEXT]], align 8
; CHECK-NEXT:    [[RAW_LOW_1:%.*]] = trunc i64 [[RAW_1]] to i32
; CHECK-NEXT:    [[NEXT_1]] = inttoptr i32 [[RAW_LOW_1]] to ptr
; CHECK-NEXT:    [[FIELD_1:%.*]] = getelementptr inbounds i8, ptr [[NEXT]], i32 8
; CHECK-NEXT:    [[V_1:%.*]] = load i64, ptr [[FIELD_1]], align 8
; CHECK-NEXT:    [[ACC_NEXT_1]] = add i64 [[ACC_NEXT]], [[V_1]]
; CHECK-NEXT:    [[DONE_1:%.*]] = icmp eq ptr [[NEXT_1]], null
; CHECK-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = phi i64 [ [[ACC_NEXT]], %[[LOOP]] ], [ [[ACC_NEXT_1]], %[[LOOP_1]] ]
; CHECK-NEXT:    ret i64 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %cur = phi ptr [ %list, %entry ], [ %next, %loop ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %loop ]
  %raw = load i64, ptr %cur, align 8
  %raw.low = trunc i64 %raw to i32
  %next = inttoptr i32 %raw.low to ptr
  %field = getelementptr inbounds i8, ptr %cur, i32 8
  %v = load i64, ptr %field, align 8
  %acc.next = add i64 %acc, %v
  %done = icmp eq ptr %next, null
  br i1 %done, label %exit, label %loop

exit:
  ret i64 %acc.next
}

declare float @llvm.fabs.f32(float)

attributes #0 = { "target-features"="+strict-align" }
attributes #1 = { "target-features"="+vfp2" }
