; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; Loops that are better tail predicated or run as low overhead loops are left
; rolled even though they have shift chains, which forcing it on would unroll,
; while another loop is unrolled for its shift chains on the same core.
; RUN: opt -S -passes=loop-unroll -mtriple=thumbv8.1m.main -mcpu=cortex-m55 < %s \
; RUN:   | FileCheck %s --check-prefix=DEFAULT
; RUN: opt -S -passes=loop-unroll -mtriple=thumbv8.1m.main -mcpu=cortex-m55 \
; RUN:   -unroll-shift-chains < %s | FileCheck %s --check-prefix=FORCED

; A tail-predicated loop keeps the previous vector for the next iteration.
define void @delta(ptr noalias %src, ptr noalias %dst, i32 %n) {
; DEFAULT-LABEL: define void @delta(
; DEFAULT-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    [[ANY:%.*]] = icmp sgt i32 [[N]], 0
; DEFAULT-NEXT:    br i1 [[ANY]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; DEFAULT:       [[LOOP_PREHEADER]]:
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[COUNT:%.*]] = phi i32 [ [[COUNT_NEXT:%.*]], %[[LOOP]] ], [ [[N]], %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[S:%.*]] = phi ptr [ [[S_NEXT:%.*]], %[[LOOP]] ], [ [[SRC]], %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[D:%.*]] = phi ptr [ [[D_NEXT:%.*]], %[[LOOP]] ], [ [[DST]], %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi <4 x i32> [ [[CUR:%.*]], %[[LOOP]] ], [ zeroinitializer, %[[LOOP_PREHEADER]] ]
; DEFAULT-NEXT:    [[MASK:%.*]] = call <4 x i1> @llvm.arm.mve.vctp32(i32 [[COUNT]])
; DEFAULT-NEXT:    [[CUR]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[S]], <4 x i1> [[MASK]], <4 x i32> zeroinitializer)
; DEFAULT-NEXT:    [[DIFF:%.*]] = sub <4 x i32> [[CUR]], [[PREV]]
; DEFAULT-NEXT:    call void @llvm.masked.store.v4i32.p0(<4 x i32> [[DIFF]], ptr align 4 [[D]], <4 x i1> [[MASK]])
; DEFAULT-NEXT:    [[S_NEXT]] = getelementptr inbounds i8, ptr [[S]], i32 16
; DEFAULT-NEXT:    [[D_NEXT]] = getelementptr inbounds i8, ptr [[D]], i32 16
; DEFAULT-NEXT:    [[COUNT_NEXT]] = sub i32 [[COUNT]], 4
; DEFAULT-NEXT:    [[MORE:%.*]] = icmp sgt i32 [[COUNT_NEXT]], 0
; DEFAULT-NEXT:    br i1 [[MORE]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; DEFAULT:       [[EXIT_LOOPEXIT]]:
; DEFAULT-NEXT:    br label %[[EXIT]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; FORCED-LABEL: define void @delta(
; FORCED-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; FORCED-NEXT:  [[ENTRY:.*:]]
; FORCED-NEXT:    [[ANY:%.*]] = icmp sgt i32 [[N]], 0
; FORCED-NEXT:    br i1 [[ANY]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; FORCED:       [[LOOP_PREHEADER]]:
; FORCED-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; FORCED-NEXT:    [[TMP1:%.*]] = lshr i32 [[TMP0]], 2
; FORCED-NEXT:    [[TMP2:%.*]] = add nuw nsw i32 [[TMP1]], 1
; FORCED-NEXT:    [[XTRAITER:%.*]] = and i32 [[TMP2]], 1
; FORCED-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i32 [[XTRAITER]], 0
; FORCED-NEXT:    br i1 [[LCMP_MOD]], label %[[LOOP_PROL_PREHEADER:.*]], label %[[LOOP_PROL_LOOPEXIT:.*]]
; FORCED:       [[LOOP_PROL_PREHEADER]]:
; FORCED-NEXT:    br label %[[LOOP_PROL:.*]]
; FORCED:       [[LOOP_PROL]]:
; FORCED-NEXT:    [[MASK_PROL:%.*]] = call <4 x i1> @llvm.arm.mve.vctp32(i32 [[N]])
; FORCED-NEXT:    [[CUR_PROL:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[SRC]], <4 x i1> [[MASK_PROL]], <4 x i32> zeroinitializer)
; FORCED-NEXT:    call void @llvm.masked.store.v4i32.p0(<4 x i32> [[CUR_PROL]], ptr align 4 [[DST]], <4 x i1> [[MASK_PROL]])
; FORCED-NEXT:    [[S_NEXT_PROL:%.*]] = getelementptr inbounds i8, ptr [[SRC]], i32 16
; FORCED-NEXT:    [[D_NEXT_PROL:%.*]] = getelementptr inbounds i8, ptr [[DST]], i32 16
; FORCED-NEXT:    [[COUNT_NEXT_PROL:%.*]] = sub i32 [[N]], 4
; FORCED-NEXT:    br label %[[LOOP_PROL_LOOPEXIT]]
; FORCED:       [[LOOP_PROL_LOOPEXIT]]:
; FORCED-NEXT:    [[COUNT_UNR:%.*]] = phi i32 [ [[N]], %[[LOOP_PREHEADER]] ], [ [[COUNT_NEXT_PROL]], %[[LOOP_PROL]] ]
; FORCED-NEXT:    [[S_UNR:%.*]] = phi ptr [ [[SRC]], %[[LOOP_PREHEADER]] ], [ [[S_NEXT_PROL]], %[[LOOP_PROL]] ]
; FORCED-NEXT:    [[D_UNR:%.*]] = phi ptr [ [[DST]], %[[LOOP_PREHEADER]] ], [ [[D_NEXT_PROL]], %[[LOOP_PROL]] ]
; FORCED-NEXT:    [[PREV_UNR:%.*]] = phi <4 x i32> [ zeroinitializer, %[[LOOP_PREHEADER]] ], [ [[CUR_PROL]], %[[LOOP_PROL]] ]
; FORCED-NEXT:    [[TMP3:%.*]] = icmp ult i32 [[TMP1]], 1
; FORCED-NEXT:    br i1 [[TMP3]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP_PREHEADER_NEW:.*]]
; FORCED:       [[LOOP_PREHEADER_NEW]]:
; FORCED-NEXT:    br label %[[LOOP:.*]]
; FORCED:       [[LOOP]]:
; FORCED-NEXT:    [[COUNT:%.*]] = phi i32 [ [[COUNT_UNR]], %[[LOOP_PREHEADER_NEW]] ], [ [[COUNT_NEXT_1:%.*]], %[[LOOP]] ]
; FORCED-NEXT:    [[S:%.*]] = phi ptr [ [[S_UNR]], %[[LOOP_PREHEADER_NEW]] ], [ [[S_NEXT_1:%.*]], %[[LOOP]] ]
; FORCED-NEXT:    [[D:%.*]] = phi ptr [ [[D_UNR]], %[[LOOP_PREHEADER_NEW]] ], [ [[D_NEXT_1:%.*]], %[[LOOP]] ]
; FORCED-NEXT:    [[PREV:%.*]] = phi <4 x i32> [ [[PREV_UNR]], %[[LOOP_PREHEADER_NEW]] ], [ [[CUR_1:%.*]], %[[LOOP]] ]
; FORCED-NEXT:    [[MASK:%.*]] = call <4 x i1> @llvm.arm.mve.vctp32(i32 [[COUNT]])
; FORCED-NEXT:    [[CUR:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[S]], <4 x i1> [[MASK]], <4 x i32> zeroinitializer)
; FORCED-NEXT:    [[DIFF:%.*]] = sub <4 x i32> [[CUR]], [[PREV]]
; FORCED-NEXT:    call void @llvm.masked.store.v4i32.p0(<4 x i32> [[DIFF]], ptr align 4 [[D]], <4 x i1> [[MASK]])
; FORCED-NEXT:    [[S_NEXT:%.*]] = getelementptr inbounds i8, ptr [[S]], i32 16
; FORCED-NEXT:    [[D_NEXT:%.*]] = getelementptr inbounds i8, ptr [[D]], i32 16
; FORCED-NEXT:    [[COUNT_NEXT:%.*]] = sub i32 [[COUNT]], 4
; FORCED-NEXT:    [[MASK_1:%.*]] = call <4 x i1> @llvm.arm.mve.vctp32(i32 [[COUNT_NEXT]])
; FORCED-NEXT:    [[CUR_1]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[S_NEXT]], <4 x i1> [[MASK_1]], <4 x i32> zeroinitializer)
; FORCED-NEXT:    [[DIFF_1:%.*]] = sub <4 x i32> [[CUR_1]], [[CUR]]
; FORCED-NEXT:    call void @llvm.masked.store.v4i32.p0(<4 x i32> [[DIFF_1]], ptr align 4 [[D_NEXT]], <4 x i1> [[MASK_1]])
; FORCED-NEXT:    [[S_NEXT_1]] = getelementptr inbounds i8, ptr [[S_NEXT]], i32 16
; FORCED-NEXT:    [[D_NEXT_1]] = getelementptr inbounds i8, ptr [[D_NEXT]], i32 16
; FORCED-NEXT:    [[COUNT_NEXT_1]] = sub i32 [[COUNT_NEXT]], 4
; FORCED-NEXT:    [[MORE_1:%.*]] = icmp sgt i32 [[COUNT_NEXT_1]], 0
; FORCED-NEXT:    br i1 [[MORE_1]], label %[[LOOP]], label %[[EXIT_LOOPEXIT_UNR_LCSSA:.*]]
; FORCED:       [[EXIT_LOOPEXIT_UNR_LCSSA]]:
; FORCED-NEXT:    br label %[[EXIT_LOOPEXIT]]
; FORCED:       [[EXIT_LOOPEXIT]]:
; FORCED-NEXT:    br label %[[EXIT]]
; FORCED:       [[EXIT]]:
; FORCED-NEXT:    ret void
;
entry:
  %any = icmp sgt i32 %n, 0
  br i1 %any, label %loop, label %exit

loop:
  %count = phi i32 [ %n, %entry ], [ %count.next, %loop ]
  %s = phi ptr [ %src, %entry ], [ %s.next, %loop ]
  %d = phi ptr [ %dst, %entry ], [ %d.next, %loop ]
  %prev = phi <4 x i32> [ zeroinitializer, %entry ], [ %cur, %loop ]
  %mask = call <4 x i1> @llvm.arm.mve.vctp32(i32 %count)
  %cur = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr %s, i32 4, <4 x i1> %mask, <4 x i32> zeroinitializer)
  %diff = sub <4 x i32> %cur, %prev
  call void @llvm.masked.store.v4i32.p0(<4 x i32> %diff, ptr %d, i32 4, <4 x i1> %mask)
  %s.next = getelementptr inbounds i8, ptr %s, i32 16
  %d.next = getelementptr inbounds i8, ptr %d, i32 16
  %count.next = sub i32 %count, 4
  %more = icmp sgt i32 %count.next, 0
  br i1 %more, label %loop, label %exit

exit:
  ret void
}

; The innermost loop of a triangular nest is kept rolled to run as a low
; overhead loop.
define void @triangle(ptr noalias %x, ptr noalias %y, i32 %n) {
; DEFAULT-LABEL: define void @triangle(
; DEFAULT-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], i32 [[N:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*]]:
; DEFAULT-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; DEFAULT-NEXT:    [[TMP1:%.*]] = add i32 [[N]], -2
; DEFAULT-NEXT:    [[XTRAITER:%.*]] = and i32 [[TMP0]], 3
; DEFAULT-NEXT:    [[TMP2:%.*]] = icmp ult i32 [[TMP1]], 3
; DEFAULT-NEXT:    br i1 [[TMP2]], label %[[OUTER_EPIL_PREHEADER:.*]], label %[[ENTRY_NEW:.*]]
; DEFAULT:       [[ENTRY_NEW]]:
; DEFAULT-NEXT:    [[UNROLL_ITER:%.*]] = sub i32 [[TMP0]], [[XTRAITER]]
; DEFAULT-NEXT:    br label %[[OUTER:.*]]
; DEFAULT:       [[OUTER]]:
; DEFAULT-NEXT:    [[J:%.*]] = phi i32 [ 1, %[[ENTRY_NEW]] ], [ [[J_NEXT_3:%.*]], %[[OUTER_LATCH_3:.*]] ]
; DEFAULT-NEXT:    [[NITER:%.*]] = phi i32 [ 0, %[[ENTRY_NEW]] ], [ [[NITER_NEXT_3:%.*]], %[[OUTER_LATCH_3]] ]
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[OUTER]] ], [ [[I_NEXT:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[PREV:%.*]] = phi i32 [ 0, %[[OUTER]] ], [ [[CUR:%.*]], %[[LOOP]] ]
; DEFAULT-NEXT:    [[PX:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I]]
; DEFAULT-NEXT:    [[CUR]] = load i32, ptr [[PX]], align 4
; DEFAULT-NEXT:    [[PREV3:%.*]] = mul i32 [[PREV]], 3
; DEFAULT-NEXT:    [[SUM:%.*]] = add i32 [[CUR]], [[PREV3]]
; DEFAULT-NEXT:    [[PY:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I]]
; DEFAULT-NEXT:    store i32 [[SUM]], ptr [[PY]], align 4
; DEFAULT-NEXT:    [[I_NEXT]] = add nuw nsw i32 [[I]], 1
; DEFAULT-NEXT:    [[INNER_DONE:%.*]] = icmp eq i32 [[I_NEXT]], [[J]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE]], label %[[OUTER_LATCH:.*]], label %[[LOOP]]
; DEFAULT:       [[OUTER_LATCH]]:
; DEFAULT-NEXT:    [[J_NEXT:%.*]] = add nuw nsw i32 [[J]], 1
; DEFAULT-NEXT:    br label %[[LOOP_1:.*]]
; DEFAULT:       [[LOOP_1]]:
; DEFAULT-NEXT:    [[I_1:%.*]] = phi i32 [ 0, %[[OUTER_LATCH]] ], [ [[I_NEXT_1:%.*]], %[[LOOP_1]] ]
; DEFAULT-NEXT:    [[PREV_1:%.*]] = phi i32 [ 0, %[[OUTER_LATCH]] ], [ [[CUR_1:%.*]], %[[LOOP_1]] ]
; DEFAULT-NEXT:    [[PX_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_1]]
; DEFAULT-NEXT:    [[CUR_1]] = load i32, ptr [[PX_1]], align 4
; DEFAULT-NEXT:    [[PREV3_1:%.*]] = mul i32 [[PREV_1]], 3
; DEFAULT-NEXT:    [[SUM_1:%.*]] = add i32 [[CUR_1]], [[PREV3_1]]
; DEFAULT-NEXT:    [[PY_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_1]]
; DEFAULT-NEXT:    store i32 [[SUM_1]], ptr [[PY_1]], align 4
; DEFAULT-NEXT:    [[I_NEXT_1]] = add nuw nsw i32 [[I_1]], 1
; DEFAULT-NEXT:    [[INNER_DONE_1:%.*]] = icmp eq i32 [[I_NEXT_1]], [[J_NEXT]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE_1]], label %[[OUTER_LATCH_1:.*]], label %[[LOOP_1]]
; DEFAULT:       [[OUTER_LATCH_1]]:
; DEFAULT-NEXT:    [[J_NEXT_1:%.*]] = add nuw nsw i32 [[J]], 2
; DEFAULT-NEXT:    br label %[[LOOP_2:.*]]
; DEFAULT:       [[LOOP_2]]:
; DEFAULT-NEXT:    [[I_2:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_1]] ], [ [[I_NEXT_2:%.*]], %[[LOOP_2]] ]
; DEFAULT-NEXT:    [[PREV_2:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_1]] ], [ [[CUR_2:%.*]], %[[LOOP_2]] ]
; DEFAULT-NEXT:    [[PX_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_2]]
; DEFAULT-NEXT:    [[CUR_2]] = load i32, ptr [[PX_2]], align 4
; DEFAULT-NEXT:    [[PREV3_2:%.*]] = mul i32 [[PREV_2]], 3
; DEFAULT-NEXT:    [[SUM_2:%.*]] = add i32 [[CUR_2]], [[PREV3_2]]
; DEFAULT-NEXT:    [[PY_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_2]]
; DEFAULT-NEXT:    store i32 [[SUM_2]], ptr [[PY_2]], align 4
; DEFAULT-NEXT:    [[I_NEXT_2]] = add nuw nsw i32 [[I_2]], 1
; DEFAULT-NEXT:    [[INNER_DONE_2:%.*]] = icmp eq i32 [[I_NEXT_2]], [[J_NEXT_1]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE_2]], label %[[OUTER_LATCH_2:.*]], label %[[LOOP_2]]
; DEFAULT:       [[OUTER_LATCH_2]]:
; DEFAULT-NEXT:    [[J_NEXT_2:%.*]] = add nuw nsw i32 [[J]], 3
; DEFAULT-NEXT:    br label %[[LOOP_3:.*]]
; DEFAULT:       [[LOOP_3]]:
; DEFAULT-NEXT:    [[I_3:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_2]] ], [ [[I_NEXT_3:%.*]], %[[LOOP_3]] ]
; DEFAULT-NEXT:    [[PREV_3:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_2]] ], [ [[CUR_3:%.*]], %[[LOOP_3]] ]
; DEFAULT-NEXT:    [[PX_3:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_3]]
; DEFAULT-NEXT:    [[CUR_3]] = load i32, ptr [[PX_3]], align 4
; DEFAULT-NEXT:    [[PREV3_3:%.*]] = mul i32 [[PREV_3]], 3
; DEFAULT-NEXT:    [[SUM_3:%.*]] = add i32 [[CUR_3]], [[PREV3_3]]
; DEFAULT-NEXT:    [[PY_3:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_3]]
; DEFAULT-NEXT:    store i32 [[SUM_3]], ptr [[PY_3]], align 4
; DEFAULT-NEXT:    [[I_NEXT_3]] = add nuw nsw i32 [[I_3]], 1
; DEFAULT-NEXT:    [[INNER_DONE_3:%.*]] = icmp eq i32 [[I_NEXT_3]], [[J_NEXT_2]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE_3]], label %[[OUTER_LATCH_3]], label %[[LOOP_3]]
; DEFAULT:       [[OUTER_LATCH_3]]:
; DEFAULT-NEXT:    [[J_NEXT_3]] = add nuw nsw i32 [[J]], 4
; DEFAULT-NEXT:    [[NITER_NEXT_3]] = add i32 [[NITER]], 4
; DEFAULT-NEXT:    [[NITER_NCMP_3:%.*]] = icmp eq i32 [[NITER_NEXT_3]], [[UNROLL_ITER]]
; DEFAULT-NEXT:    br i1 [[NITER_NCMP_3]], label %[[EXIT_UNR_LCSSA:.*]], label %[[OUTER]]
; DEFAULT:       [[EXIT_UNR_LCSSA]]:
; DEFAULT-NEXT:    [[J_UNR:%.*]] = phi i32 [ [[J_NEXT_3]], %[[OUTER_LATCH_3]] ]
; DEFAULT-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i32 [[XTRAITER]], 0
; DEFAULT-NEXT:    br i1 [[LCMP_MOD]], label %[[OUTER_EPIL_PREHEADER]], label %[[EXIT:.*]]
; DEFAULT:       [[OUTER_EPIL_PREHEADER]]:
; DEFAULT-NEXT:    [[J_EPIL_INIT:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[J_UNR]], %[[EXIT_UNR_LCSSA]] ]
; DEFAULT-NEXT:    [[LCMP_MOD1:%.*]] = icmp ne i32 [[XTRAITER]], 0
; DEFAULT-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD1]])
; DEFAULT-NEXT:    br label %[[OUTER_EPIL:.*]]
; DEFAULT:       [[OUTER_EPIL]]:
; DEFAULT-NEXT:    br label %[[LOOP_EPIL:.*]]
; DEFAULT:       [[LOOP_EPIL]]:
; DEFAULT-NEXT:    [[I_EPIL:%.*]] = phi i32 [ 0, %[[OUTER_EPIL]] ], [ [[I_NEXT_EPIL:%.*]], %[[LOOP_EPIL]] ]
; DEFAULT-NEXT:    [[PREV_EPIL:%.*]] = phi i32 [ 0, %[[OUTER_EPIL]] ], [ [[CUR_EPIL:%.*]], %[[LOOP_EPIL]] ]
; DEFAULT-NEXT:    [[PX_EPIL:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL]]
; DEFAULT-NEXT:    [[CUR_EPIL]] = load i32, ptr [[PX_EPIL]], align 4
; DEFAULT-NEXT:    [[PREV3_EPIL:%.*]] = mul i32 [[PREV_EPIL]], 3
; DEFAULT-NEXT:    [[SUM_EPIL:%.*]] = add i32 [[CUR_EPIL]], [[PREV3_EPIL]]
; DEFAULT-NEXT:    [[PY_EPIL:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL]]
; DEFAULT-NEXT:    store i32 [[SUM_EPIL]], ptr [[PY_EPIL]], align 4
; DEFAULT-NEXT:    [[I_NEXT_EPIL]] = add nuw nsw i32 [[I_EPIL]], 1
; DEFAULT-NEXT:    [[INNER_DONE_EPIL:%.*]] = icmp eq i32 [[I_NEXT_EPIL]], [[J_EPIL_INIT]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE_EPIL]], label %[[OUTER_LATCH_EPIL:.*]], label %[[LOOP_EPIL]]
; DEFAULT:       [[OUTER_LATCH_EPIL]]:
; DEFAULT-NEXT:    [[J_NEXT_EPIL:%.*]] = add nuw nsw i32 [[J_EPIL_INIT]], 1
; DEFAULT-NEXT:    [[EPIL_ITER_CMP:%.*]] = icmp ne i32 1, [[XTRAITER]]
; DEFAULT-NEXT:    br i1 [[EPIL_ITER_CMP]], label %[[OUTER_EPIL_1:.*]], label %[[EXIT_EPILOG_LCSSA:.*]]
; DEFAULT:       [[OUTER_EPIL_1]]:
; DEFAULT-NEXT:    br label %[[LOOP_EPIL_1:.*]]
; DEFAULT:       [[LOOP_EPIL_1]]:
; DEFAULT-NEXT:    [[I_EPIL_1:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_1]] ], [ [[I_NEXT_EPIL_1:%.*]], %[[LOOP_EPIL_1]] ]
; DEFAULT-NEXT:    [[PREV_EPIL_1:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_1]] ], [ [[CUR_EPIL_1:%.*]], %[[LOOP_EPIL_1]] ]
; DEFAULT-NEXT:    [[PX_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_1]]
; DEFAULT-NEXT:    [[CUR_EPIL_1]] = load i32, ptr [[PX_EPIL_1]], align 4
; DEFAULT-NEXT:    [[PREV3_EPIL_1:%.*]] = mul i32 [[PREV_EPIL_1]], 3
; DEFAULT-NEXT:    [[SUM_EPIL_1:%.*]] = add i32 [[CUR_EPIL_1]], [[PREV3_EPIL_1]]
; DEFAULT-NEXT:    [[PY_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_1]]
; DEFAULT-NEXT:    store i32 [[SUM_EPIL_1]], ptr [[PY_EPIL_1]], align 4
; DEFAULT-NEXT:    [[I_NEXT_EPIL_1]] = add nuw nsw i32 [[I_EPIL_1]], 1
; DEFAULT-NEXT:    [[INNER_DONE_EPIL_1:%.*]] = icmp eq i32 [[I_NEXT_EPIL_1]], [[J_NEXT_EPIL]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE_EPIL_1]], label %[[OUTER_LATCH_EPIL_1:.*]], label %[[LOOP_EPIL_1]]
; DEFAULT:       [[OUTER_LATCH_EPIL_1]]:
; DEFAULT-NEXT:    [[J_NEXT_EPIL_1:%.*]] = add nuw nsw i32 [[J_EPIL_INIT]], 2
; DEFAULT-NEXT:    [[EPIL_ITER_CMP_1:%.*]] = icmp ne i32 2, [[XTRAITER]]
; DEFAULT-NEXT:    br i1 [[EPIL_ITER_CMP_1]], label %[[OUTER_EPIL_2:.*]], label %[[EXIT_EPILOG_LCSSA]]
; DEFAULT:       [[OUTER_EPIL_2]]:
; DEFAULT-NEXT:    br label %[[LOOP_EPIL_2:.*]]
; DEFAULT:       [[LOOP_EPIL_2]]:
; DEFAULT-NEXT:    [[I_EPIL_2:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_2]] ], [ [[I_NEXT_EPIL_2:%.*]], %[[LOOP_EPIL_2]] ]
; DEFAULT-NEXT:    [[PREV_EPIL_2:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_2]] ], [ [[CUR_EPIL_2:%.*]], %[[LOOP_EPIL_2]] ]
; DEFAULT-NEXT:    [[PX_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_2]]
; DEFAULT-NEXT:    [[CUR_EPIL_2]] = load i32, ptr [[PX_EPIL_2]], align 4
; DEFAULT-NEXT:    [[PREV3_EPIL_2:%.*]] = mul i32 [[PREV_EPIL_2]], 3
; DEFAULT-NEXT:    [[SUM_EPIL_2:%.*]] = add i32 [[CUR_EPIL_2]], [[PREV3_EPIL_2]]
; DEFAULT-NEXT:    [[PY_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_2]]
; DEFAULT-NEXT:    store i32 [[SUM_EPIL_2]], ptr [[PY_EPIL_2]], align 4
; DEFAULT-NEXT:    [[I_NEXT_EPIL_2]] = add nuw nsw i32 [[I_EPIL_2]], 1
; DEFAULT-NEXT:    [[INNER_DONE_EPIL_2:%.*]] = icmp eq i32 [[I_NEXT_EPIL_2]], [[J_NEXT_EPIL_1]]
; DEFAULT-NEXT:    br i1 [[INNER_DONE_EPIL_2]], label %[[OUTER_LATCH_EPIL_2:.*]], label %[[LOOP_EPIL_2]]
; DEFAULT:       [[OUTER_LATCH_EPIL_2]]:
; DEFAULT-NEXT:    br label %[[EXIT_EPILOG_LCSSA]]
; DEFAULT:       [[EXIT_EPILOG_LCSSA]]:
; DEFAULT-NEXT:    br label %[[EXIT]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; FORCED-LABEL: define void @triangle(
; FORCED-SAME: ptr noalias [[X:%.*]], ptr noalias [[Y:%.*]], i32 [[N:%.*]]) #[[ATTR0]] {
; FORCED-NEXT:  [[ENTRY:.*]]:
; FORCED-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; FORCED-NEXT:    [[TMP1:%.*]] = add i32 [[N]], -2
; FORCED-NEXT:    [[XTRAITER2:%.*]] = and i32 [[TMP0]], 3
; FORCED-NEXT:    [[TMP2:%.*]] = icmp ult i32 [[TMP1]], 3
; FORCED-NEXT:    br i1 [[TMP2]], label %[[OUTER_EPIL_PREHEADER:.*]], label %[[ENTRY_NEW:.*]]
; FORCED:       [[ENTRY_NEW]]:
; FORCED-NEXT:    [[UNROLL_ITER11:%.*]] = sub i32 [[TMP0]], [[XTRAITER2]]
; FORCED-NEXT:    br label %[[OUTER:.*]]
; FORCED:       [[OUTER]]:
; FORCED-NEXT:    [[INDVAR:%.*]] = phi i32 [ 0, %[[ENTRY_NEW]] ], [ [[INDVAR_NEXT_3:%.*]], %[[OUTER_LATCH_3:.*]] ]
; FORCED-NEXT:    [[J:%.*]] = phi i32 [ 1, %[[ENTRY_NEW]] ], [ [[J_NEXT_3:%.*]], %[[OUTER_LATCH_3]] ]
; FORCED-NEXT:    [[NITER12:%.*]] = phi i32 [ 0, %[[ENTRY_NEW]] ], [ [[NITER12_NEXT_3:%.*]], %[[OUTER_LATCH_3]] ]
; FORCED-NEXT:    [[TMP3:%.*]] = icmp ult i32 [[INDVAR]], 1
; FORCED-NEXT:    br i1 [[TMP3]], label %[[LOOP_EPIL_PREHEADER:.*]], label %[[OUTER_NEW:.*]]
; FORCED:       [[OUTER_NEW]]:
; FORCED-NEXT:    [[UNROLL_ITER:%.*]] = sub nuw nsw i32 [[J]], 1
; FORCED-NEXT:    br label %[[LOOP:.*]]
; FORCED:       [[LOOP]]:
; FORCED-NEXT:    [[I:%.*]] = phi i32 [ 0, %[[OUTER_NEW]] ], [ [[I_NEXT_1:%.*]], %[[LOOP]] ]
; FORCED-NEXT:    [[PREV:%.*]] = phi i32 [ 0, %[[OUTER_NEW]] ], [ [[CUR_1:%.*]], %[[LOOP]] ]
; FORCED-NEXT:    [[NITER:%.*]] = phi i32 [ 0, %[[OUTER_NEW]] ], [ [[NITER_NEXT_1:%.*]], %[[LOOP]] ]
; FORCED-NEXT:    [[PX:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I]]
; FORCED-NEXT:    [[CUR:%.*]] = load i32, ptr [[PX]], align 4
; FORCED-NEXT:    [[PREV3:%.*]] = mul i32 [[PREV]], 3
; FORCED-NEXT:    [[SUM:%.*]] = add i32 [[CUR]], [[PREV3]]
; FORCED-NEXT:    [[PY:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I]]
; FORCED-NEXT:    store i32 [[SUM]], ptr [[PY]], align 4
; FORCED-NEXT:    [[I_NEXT:%.*]] = add nuw nsw i32 [[I]], 1
; FORCED-NEXT:    [[PX_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_NEXT]]
; FORCED-NEXT:    [[CUR_1]] = load i32, ptr [[PX_1]], align 4
; FORCED-NEXT:    [[PREV3_1:%.*]] = mul i32 [[CUR]], 3
; FORCED-NEXT:    [[SUM_1:%.*]] = add i32 [[CUR_1]], [[PREV3_1]]
; FORCED-NEXT:    [[PY_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_NEXT]]
; FORCED-NEXT:    store i32 [[SUM_1]], ptr [[PY_1]], align 4
; FORCED-NEXT:    [[I_NEXT_1]] = add nuw nsw i32 [[I]], 2
; FORCED-NEXT:    [[NITER_NEXT_1]] = add i32 [[NITER]], 2
; FORCED-NEXT:    [[NITER_NCMP_1:%.*]] = icmp eq i32 [[NITER_NEXT_1]], [[UNROLL_ITER]]
; FORCED-NEXT:    br i1 [[NITER_NCMP_1]], label %[[OUTER_LATCH_UNR_LCSSA:.*]], label %[[LOOP]]
; FORCED:       [[OUTER_LATCH_UNR_LCSSA]]:
; FORCED-NEXT:    [[I_UNR:%.*]] = phi i32 [ [[I_NEXT_1]], %[[LOOP]] ]
; FORCED-NEXT:    [[PREV_UNR:%.*]] = phi i32 [ [[CUR_1]], %[[LOOP]] ]
; FORCED-NEXT:    br i1 true, label %[[LOOP_EPIL_PREHEADER]], label %[[OUTER_LATCH:.*]]
; FORCED:       [[LOOP_EPIL_PREHEADER]]:
; FORCED-NEXT:    [[I_EPIL_INIT:%.*]] = phi i32 [ 0, %[[OUTER]] ], [ [[I_UNR]], %[[OUTER_LATCH_UNR_LCSSA]] ]
; FORCED-NEXT:    [[PREV_EPIL_INIT:%.*]] = phi i32 [ 0, %[[OUTER]] ], [ [[PREV_UNR]], %[[OUTER_LATCH_UNR_LCSSA]] ]
; FORCED-NEXT:    br label %[[LOOP_EPIL:.*]]
; FORCED:       [[LOOP_EPIL]]:
; FORCED-NEXT:    [[PX_EPIL:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_INIT]]
; FORCED-NEXT:    [[CUR_EPIL:%.*]] = load i32, ptr [[PX_EPIL]], align 4
; FORCED-NEXT:    [[PREV3_EPIL:%.*]] = mul i32 [[PREV_EPIL_INIT]], 3
; FORCED-NEXT:    [[SUM_EPIL:%.*]] = add i32 [[CUR_EPIL]], [[PREV3_EPIL]]
; FORCED-NEXT:    [[PY_EPIL:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_INIT]]
; FORCED-NEXT:    store i32 [[SUM_EPIL]], ptr [[PY_EPIL]], align 4
; FORCED-NEXT:    br label %[[OUTER_LATCH]]
; FORCED:       [[OUTER_LATCH]]:
; FORCED-NEXT:    [[J_NEXT:%.*]] = add nuw nsw i32 [[J]], 1
; FORCED-NEXT:    br i1 false, label %[[LOOP_EPIL_PREHEADER_1:.*]], label %[[OUTER_NEW_1:.*]]
; FORCED:       [[OUTER_NEW_1]]:
; FORCED-NEXT:    br label %[[LOOP_1:.*]]
; FORCED:       [[LOOP_1]]:
; FORCED-NEXT:    [[I_1:%.*]] = phi i32 [ 0, %[[OUTER_NEW_1]] ], [ [[I_NEXT_1_1:%.*]], %[[LOOP_1]] ]
; FORCED-NEXT:    [[PREV_1:%.*]] = phi i32 [ 0, %[[OUTER_NEW_1]] ], [ [[CUR_1_1:%.*]], %[[LOOP_1]] ]
; FORCED-NEXT:    [[NITER_1:%.*]] = phi i32 [ 0, %[[OUTER_NEW_1]] ], [ [[NITER_NEXT_1_1:%.*]], %[[LOOP_1]] ]
; FORCED-NEXT:    [[PX_113:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_1]]
; FORCED-NEXT:    [[CUR_114:%.*]] = load i32, ptr [[PX_113]], align 4
; FORCED-NEXT:    [[PREV3_115:%.*]] = mul i32 [[PREV_1]], 3
; FORCED-NEXT:    [[SUM_116:%.*]] = add i32 [[CUR_114]], [[PREV3_115]]
; FORCED-NEXT:    [[PY_117:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_1]]
; FORCED-NEXT:    store i32 [[SUM_116]], ptr [[PY_117]], align 4
; FORCED-NEXT:    [[I_NEXT_118:%.*]] = add nuw nsw i32 [[I_1]], 1
; FORCED-NEXT:    [[PX_1_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_NEXT_118]]
; FORCED-NEXT:    [[CUR_1_1]] = load i32, ptr [[PX_1_1]], align 4
; FORCED-NEXT:    [[PREV3_1_1:%.*]] = mul i32 [[CUR_114]], 3
; FORCED-NEXT:    [[SUM_1_1:%.*]] = add i32 [[CUR_1_1]], [[PREV3_1_1]]
; FORCED-NEXT:    [[PY_1_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_NEXT_118]]
; FORCED-NEXT:    store i32 [[SUM_1_1]], ptr [[PY_1_1]], align 4
; FORCED-NEXT:    [[I_NEXT_1_1]] = add nuw nsw i32 [[I_1]], 2
; FORCED-NEXT:    [[NITER_NEXT_1_1]] = add i32 [[NITER_1]], 2
; FORCED-NEXT:    [[NITER_NCMP_1_1:%.*]] = icmp eq i32 [[NITER_NEXT_1_1]], [[J_NEXT]]
; FORCED-NEXT:    br i1 [[NITER_NCMP_1_1]], label %[[OUTER_LATCH_UNR_LCSSA_1:.*]], label %[[LOOP_1]]
; FORCED:       [[OUTER_LATCH_UNR_LCSSA_1]]:
; FORCED-NEXT:    [[I_UNR_1:%.*]] = phi i32 [ [[I_NEXT_1_1]], %[[LOOP_1]] ]
; FORCED-NEXT:    [[PREV_UNR_1:%.*]] = phi i32 [ [[CUR_1_1]], %[[LOOP_1]] ]
; FORCED-NEXT:    br i1 false, label %[[LOOP_EPIL_PREHEADER_1]], label %[[OUTER_LATCH_1:.*]]
; FORCED:       [[LOOP_EPIL_PREHEADER_1]]:
; FORCED-NEXT:    [[I_EPIL_INIT_1:%.*]] = phi i32 [ 0, %[[OUTER_LATCH]] ], [ [[I_UNR_1]], %[[OUTER_LATCH_UNR_LCSSA_1]] ]
; FORCED-NEXT:    [[PREV_EPIL_INIT_1:%.*]] = phi i32 [ 0, %[[OUTER_LATCH]] ], [ [[PREV_UNR_1]], %[[OUTER_LATCH_UNR_LCSSA_1]] ]
; FORCED-NEXT:    call void @llvm.assume(i1 false)
; FORCED-NEXT:    br label %[[LOOP_EPIL_1:.*]]
; FORCED:       [[LOOP_EPIL_1]]:
; FORCED-NEXT:    [[PX_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_INIT_1]]
; FORCED-NEXT:    [[CUR_EPIL_1:%.*]] = load i32, ptr [[PX_EPIL_1]], align 4
; FORCED-NEXT:    [[PREV3_EPIL_1:%.*]] = mul i32 [[PREV_EPIL_INIT_1]], 3
; FORCED-NEXT:    [[SUM_EPIL_1:%.*]] = add i32 [[CUR_EPIL_1]], [[PREV3_EPIL_1]]
; FORCED-NEXT:    [[PY_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_INIT_1]]
; FORCED-NEXT:    store i32 [[SUM_EPIL_1]], ptr [[PY_EPIL_1]], align 4
; FORCED-NEXT:    br label %[[OUTER_LATCH_1]]
; FORCED:       [[OUTER_LATCH_1]]:
; FORCED-NEXT:    [[J_NEXT_1:%.*]] = add nuw nsw i32 [[J]], 2
; FORCED-NEXT:    br i1 false, label %[[LOOP_EPIL_PREHEADER_2:.*]], label %[[OUTER_NEW_2:.*]]
; FORCED:       [[OUTER_NEW_2]]:
; FORCED-NEXT:    [[UNROLL_ITER_2:%.*]] = sub nuw nsw i32 [[J_NEXT_1]], 1
; FORCED-NEXT:    br label %[[LOOP_2:.*]]
; FORCED:       [[LOOP_2]]:
; FORCED-NEXT:    [[I_2:%.*]] = phi i32 [ 0, %[[OUTER_NEW_2]] ], [ [[I_NEXT_1_2:%.*]], %[[LOOP_2]] ]
; FORCED-NEXT:    [[PREV_2:%.*]] = phi i32 [ 0, %[[OUTER_NEW_2]] ], [ [[CUR_1_2:%.*]], %[[LOOP_2]] ]
; FORCED-NEXT:    [[NITER_2:%.*]] = phi i32 [ 0, %[[OUTER_NEW_2]] ], [ [[NITER_NEXT_1_2:%.*]], %[[LOOP_2]] ]
; FORCED-NEXT:    [[PX_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_2]]
; FORCED-NEXT:    [[CUR_2:%.*]] = load i32, ptr [[PX_2]], align 4
; FORCED-NEXT:    [[PREV3_2:%.*]] = mul i32 [[PREV_2]], 3
; FORCED-NEXT:    [[SUM_2:%.*]] = add i32 [[CUR_2]], [[PREV3_2]]
; FORCED-NEXT:    [[PY_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_2]]
; FORCED-NEXT:    store i32 [[SUM_2]], ptr [[PY_2]], align 4
; FORCED-NEXT:    [[I_NEXT_2:%.*]] = add nuw nsw i32 [[I_2]], 1
; FORCED-NEXT:    [[PX_1_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_NEXT_2]]
; FORCED-NEXT:    [[CUR_1_2]] = load i32, ptr [[PX_1_2]], align 4
; FORCED-NEXT:    [[PREV3_1_2:%.*]] = mul i32 [[CUR_2]], 3
; FORCED-NEXT:    [[SUM_1_2:%.*]] = add i32 [[CUR_1_2]], [[PREV3_1_2]]
; FORCED-NEXT:    [[PY_1_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_NEXT_2]]
; FORCED-NEXT:    store i32 [[SUM_1_2]], ptr [[PY_1_2]], align 4
; FORCED-NEXT:    [[I_NEXT_1_2]] = add nuw nsw i32 [[I_2]], 2
; FORCED-NEXT:    [[NITER_NEXT_1_2]] = add i32 [[NITER_2]], 2
; FORCED-NEXT:    [[NITER_NCMP_1_2:%.*]] = icmp eq i32 [[NITER_NEXT_1_2]], [[UNROLL_ITER_2]]
; FORCED-NEXT:    br i1 [[NITER_NCMP_1_2]], label %[[OUTER_LATCH_UNR_LCSSA_2:.*]], label %[[LOOP_2]]
; FORCED:       [[OUTER_LATCH_UNR_LCSSA_2]]:
; FORCED-NEXT:    [[I_UNR_2:%.*]] = phi i32 [ [[I_NEXT_1_2]], %[[LOOP_2]] ]
; FORCED-NEXT:    [[PREV_UNR_2:%.*]] = phi i32 [ [[CUR_1_2]], %[[LOOP_2]] ]
; FORCED-NEXT:    br i1 true, label %[[LOOP_EPIL_PREHEADER_2]], label %[[OUTER_LATCH_2:.*]]
; FORCED:       [[LOOP_EPIL_PREHEADER_2]]:
; FORCED-NEXT:    [[I_EPIL_INIT_2:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_1]] ], [ [[I_UNR_2]], %[[OUTER_LATCH_UNR_LCSSA_2]] ]
; FORCED-NEXT:    [[PREV_EPIL_INIT_2:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_1]] ], [ [[PREV_UNR_2]], %[[OUTER_LATCH_UNR_LCSSA_2]] ]
; FORCED-NEXT:    br label %[[LOOP_EPIL_2:.*]]
; FORCED:       [[LOOP_EPIL_2]]:
; FORCED-NEXT:    [[PX_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_INIT_2]]
; FORCED-NEXT:    [[CUR_EPIL_2:%.*]] = load i32, ptr [[PX_EPIL_2]], align 4
; FORCED-NEXT:    [[PREV3_EPIL_2:%.*]] = mul i32 [[PREV_EPIL_INIT_2]], 3
; FORCED-NEXT:    [[SUM_EPIL_2:%.*]] = add i32 [[CUR_EPIL_2]], [[PREV3_EPIL_2]]
; FORCED-NEXT:    [[PY_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_INIT_2]]
; FORCED-NEXT:    store i32 [[SUM_EPIL_2]], ptr [[PY_EPIL_2]], align 4
; FORCED-NEXT:    br label %[[OUTER_LATCH_2]]
; FORCED:       [[OUTER_LATCH_2]]:
; FORCED-NEXT:    [[J_NEXT_2:%.*]] = add nuw nsw i32 [[J]], 3
; FORCED-NEXT:    br i1 false, label %[[LOOP_EPIL_PREHEADER_3:.*]], label %[[OUTER_NEW_3:.*]]
; FORCED:       [[OUTER_NEW_3]]:
; FORCED-NEXT:    br label %[[LOOP_3:.*]]
; FORCED:       [[LOOP_3]]:
; FORCED-NEXT:    [[I_3:%.*]] = phi i32 [ 0, %[[OUTER_NEW_3]] ], [ [[I_NEXT_1_3:%.*]], %[[LOOP_3]] ]
; FORCED-NEXT:    [[PREV_3:%.*]] = phi i32 [ 0, %[[OUTER_NEW_3]] ], [ [[CUR_1_3:%.*]], %[[LOOP_3]] ]
; FORCED-NEXT:    [[NITER_3:%.*]] = phi i32 [ 0, %[[OUTER_NEW_3]] ], [ [[NITER_NEXT_1_3:%.*]], %[[LOOP_3]] ]
; FORCED-NEXT:    [[PX_3:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_3]]
; FORCED-NEXT:    [[CUR_3:%.*]] = load i32, ptr [[PX_3]], align 4
; FORCED-NEXT:    [[PREV3_3:%.*]] = mul i32 [[PREV_3]], 3
; FORCED-NEXT:    [[SUM_3:%.*]] = add i32 [[CUR_3]], [[PREV3_3]]
; FORCED-NEXT:    [[PY_3:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_3]]
; FORCED-NEXT:    store i32 [[SUM_3]], ptr [[PY_3]], align 4
; FORCED-NEXT:    [[I_NEXT_3:%.*]] = add nuw nsw i32 [[I_3]], 1
; FORCED-NEXT:    [[PX_1_3:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_NEXT_3]]
; FORCED-NEXT:    [[CUR_1_3]] = load i32, ptr [[PX_1_3]], align 4
; FORCED-NEXT:    [[PREV3_1_3:%.*]] = mul i32 [[CUR_3]], 3
; FORCED-NEXT:    [[SUM_1_3:%.*]] = add i32 [[CUR_1_3]], [[PREV3_1_3]]
; FORCED-NEXT:    [[PY_1_3:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_NEXT_3]]
; FORCED-NEXT:    store i32 [[SUM_1_3]], ptr [[PY_1_3]], align 4
; FORCED-NEXT:    [[I_NEXT_1_3]] = add nuw nsw i32 [[I_3]], 2
; FORCED-NEXT:    [[NITER_NEXT_1_3]] = add i32 [[NITER_3]], 2
; FORCED-NEXT:    [[NITER_NCMP_1_3:%.*]] = icmp eq i32 [[NITER_NEXT_1_3]], [[J_NEXT_2]]
; FORCED-NEXT:    br i1 [[NITER_NCMP_1_3]], label %[[OUTER_LATCH_UNR_LCSSA_3:.*]], label %[[LOOP_3]]
; FORCED:       [[OUTER_LATCH_UNR_LCSSA_3]]:
; FORCED-NEXT:    [[I_UNR_3:%.*]] = phi i32 [ [[I_NEXT_1_3]], %[[LOOP_3]] ]
; FORCED-NEXT:    [[PREV_UNR_3:%.*]] = phi i32 [ [[CUR_1_3]], %[[LOOP_3]] ]
; FORCED-NEXT:    br i1 false, label %[[LOOP_EPIL_PREHEADER_3]], label %[[OUTER_LATCH_3]]
; FORCED:       [[LOOP_EPIL_PREHEADER_3]]:
; FORCED-NEXT:    [[I_EPIL_INIT_3:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_2]] ], [ [[I_UNR_3]], %[[OUTER_LATCH_UNR_LCSSA_3]] ]
; FORCED-NEXT:    [[PREV_EPIL_INIT_3:%.*]] = phi i32 [ 0, %[[OUTER_LATCH_2]] ], [ [[PREV_UNR_3]], %[[OUTER_LATCH_UNR_LCSSA_3]] ]
; FORCED-NEXT:    call void @llvm.assume(i1 false)
; FORCED-NEXT:    br label %[[LOOP_EPIL_3:.*]]
; FORCED:       [[LOOP_EPIL_3]]:
; FORCED-NEXT:    [[PX_EPIL_3:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_INIT_3]]
; FORCED-NEXT:    [[CUR_EPIL_3:%.*]] = load i32, ptr [[PX_EPIL_3]], align 4
; FORCED-NEXT:    [[PREV3_EPIL_3:%.*]] = mul i32 [[PREV_EPIL_INIT_3]], 3
; FORCED-NEXT:    [[SUM_EPIL_3:%.*]] = add i32 [[CUR_EPIL_3]], [[PREV3_EPIL_3]]
; FORCED-NEXT:    [[PY_EPIL_3:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_INIT_3]]
; FORCED-NEXT:    store i32 [[SUM_EPIL_3]], ptr [[PY_EPIL_3]], align 4
; FORCED-NEXT:    br label %[[OUTER_LATCH_3]]
; FORCED:       [[OUTER_LATCH_3]]:
; FORCED-NEXT:    [[J_NEXT_3]] = add nuw nsw i32 [[J]], 4
; FORCED-NEXT:    [[INDVAR_NEXT_3]] = add i32 [[INDVAR]], 4
; FORCED-NEXT:    [[NITER12_NEXT_3]] = add i32 [[NITER12]], 4
; FORCED-NEXT:    [[NITER12_NCMP_3:%.*]] = icmp eq i32 [[NITER12_NEXT_3]], [[UNROLL_ITER11]]
; FORCED-NEXT:    br i1 [[NITER12_NCMP_3]], label %[[EXIT_UNR_LCSSA:.*]], label %[[OUTER]]
; FORCED:       [[EXIT_UNR_LCSSA]]:
; FORCED-NEXT:    [[INDVAR_UNR:%.*]] = phi i32 [ [[INDVAR_NEXT_3]], %[[OUTER_LATCH_3]] ]
; FORCED-NEXT:    [[J_UNR:%.*]] = phi i32 [ [[J_NEXT_3]], %[[OUTER_LATCH_3]] ]
; FORCED-NEXT:    [[LCMP_MOD9:%.*]] = icmp ne i32 [[XTRAITER2]], 0
; FORCED-NEXT:    br i1 [[LCMP_MOD9]], label %[[OUTER_EPIL_PREHEADER]], label %[[EXIT:.*]]
; FORCED:       [[OUTER_EPIL_PREHEADER]]:
; FORCED-NEXT:    [[INDVAR_EPIL_INIT:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INDVAR_UNR]], %[[EXIT_UNR_LCSSA]] ]
; FORCED-NEXT:    [[J_EPIL_INIT:%.*]] = phi i32 [ 1, %[[ENTRY]] ], [ [[J_UNR]], %[[EXIT_UNR_LCSSA]] ]
; FORCED-NEXT:    [[LCMP_MOD10:%.*]] = icmp ne i32 [[XTRAITER2]], 0
; FORCED-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD10]])
; FORCED-NEXT:    br label %[[OUTER_EPIL:.*]]
; FORCED:       [[OUTER_EPIL]]:
; FORCED-NEXT:    [[XTRAITER_EPIL:%.*]] = and i32 [[J_EPIL_INIT]], 1
; FORCED-NEXT:    [[TMP4:%.*]] = icmp ult i32 [[INDVAR_EPIL_INIT]], 1
; FORCED-NEXT:    br i1 [[TMP4]], label %[[LOOP_EPIL_PREHEADER_EPIL:.*]], label %[[OUTER_NEW_EPIL:.*]]
; FORCED:       [[OUTER_NEW_EPIL]]:
; FORCED-NEXT:    [[UNROLL_ITER_EPIL:%.*]] = sub i32 [[J_EPIL_INIT]], [[XTRAITER_EPIL]]
; FORCED-NEXT:    br label %[[LOOP_EPIL3:.*]]
; FORCED:       [[LOOP_EPIL3]]:
; FORCED-NEXT:    [[I_EPIL:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL]] ], [ [[I_NEXT_1_EPIL:%.*]], %[[LOOP_EPIL3]] ]
; FORCED-NEXT:    [[PREV_EPIL:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL]] ], [ [[CUR_1_EPIL:%.*]], %[[LOOP_EPIL3]] ]
; FORCED-NEXT:    [[NITER_EPIL:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL]] ], [ [[NITER_NEXT_1_EPIL:%.*]], %[[LOOP_EPIL3]] ]
; FORCED-NEXT:    [[PX_EPIL4:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL]]
; FORCED-NEXT:    [[CUR_EPIL5:%.*]] = load i32, ptr [[PX_EPIL4]], align 4
; FORCED-NEXT:    [[PREV3_EPIL6:%.*]] = mul i32 [[PREV_EPIL]], 3
; FORCED-NEXT:    [[SUM_EPIL7:%.*]] = add i32 [[CUR_EPIL5]], [[PREV3_EPIL6]]
; FORCED-NEXT:    [[PY_EPIL8:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL]]
; FORCED-NEXT:    store i32 [[SUM_EPIL7]], ptr [[PY_EPIL8]], align 4
; FORCED-NEXT:    [[I_NEXT_EPIL:%.*]] = add nuw nsw i32 [[I_EPIL]], 1
; FORCED-NEXT:    [[PX_1_EPIL:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_NEXT_EPIL]]
; FORCED-NEXT:    [[CUR_1_EPIL]] = load i32, ptr [[PX_1_EPIL]], align 4
; FORCED-NEXT:    [[PREV3_1_EPIL:%.*]] = mul i32 [[CUR_EPIL5]], 3
; FORCED-NEXT:    [[SUM_1_EPIL:%.*]] = add i32 [[CUR_1_EPIL]], [[PREV3_1_EPIL]]
; FORCED-NEXT:    [[PY_1_EPIL:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_NEXT_EPIL]]
; FORCED-NEXT:    store i32 [[SUM_1_EPIL]], ptr [[PY_1_EPIL]], align 4
; FORCED-NEXT:    [[I_NEXT_1_EPIL]] = add nuw nsw i32 [[I_EPIL]], 2
; FORCED-NEXT:    [[NITER_NEXT_1_EPIL]] = add i32 [[NITER_EPIL]], 2
; FORCED-NEXT:    [[NITER_NCMP_1_EPIL:%.*]] = icmp eq i32 [[NITER_NEXT_1_EPIL]], [[UNROLL_ITER_EPIL]]
; FORCED-NEXT:    br i1 [[NITER_NCMP_1_EPIL]], label %[[OUTER_LATCH_UNR_LCSSA_EPIL:.*]], label %[[LOOP_EPIL3]]
; FORCED:       [[OUTER_LATCH_UNR_LCSSA_EPIL]]:
; FORCED-NEXT:    [[I_UNR_EPIL:%.*]] = phi i32 [ [[I_NEXT_1_EPIL]], %[[LOOP_EPIL3]] ]
; FORCED-NEXT:    [[PREV_UNR_EPIL:%.*]] = phi i32 [ [[CUR_1_EPIL]], %[[LOOP_EPIL3]] ]
; FORCED-NEXT:    [[LCMP_MOD_EPIL:%.*]] = icmp ne i32 [[XTRAITER_EPIL]], 0
; FORCED-NEXT:    br i1 [[LCMP_MOD_EPIL]], label %[[LOOP_EPIL_PREHEADER_EPIL]], label %[[OUTER_LATCH_EPIL:.*]]
; FORCED:       [[LOOP_EPIL_PREHEADER_EPIL]]:
; FORCED-NEXT:    [[I_EPIL_INIT_EPIL:%.*]] = phi i32 [ 0, %[[OUTER_EPIL]] ], [ [[I_UNR_EPIL]], %[[OUTER_LATCH_UNR_LCSSA_EPIL]] ]
; FORCED-NEXT:    [[PREV_EPIL_INIT_EPIL:%.*]] = phi i32 [ 0, %[[OUTER_EPIL]] ], [ [[PREV_UNR_EPIL]], %[[OUTER_LATCH_UNR_LCSSA_EPIL]] ]
; FORCED-NEXT:    [[LCMP_MOD1_EPIL:%.*]] = icmp ne i32 [[XTRAITER_EPIL]], 0
; FORCED-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD1_EPIL]])
; FORCED-NEXT:    br label %[[LOOP_EPIL_EPIL:.*]]
; FORCED:       [[LOOP_EPIL_EPIL]]:
; FORCED-NEXT:    [[PX_EPIL_EPIL:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_INIT_EPIL]]
; FORCED-NEXT:    [[CUR_EPIL_EPIL:%.*]] = load i32, ptr [[PX_EPIL_EPIL]], align 4
; FORCED-NEXT:    [[PREV3_EPIL_EPIL:%.*]] = mul i32 [[PREV_EPIL_INIT_EPIL]], 3
; FORCED-NEXT:    [[SUM_EPIL_EPIL:%.*]] = add i32 [[CUR_EPIL_EPIL]], [[PREV3_EPIL_EPIL]]
; FORCED-NEXT:    [[PY_EPIL_EPIL:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_INIT_EPIL]]
; FORCED-NEXT:    store i32 [[SUM_EPIL_EPIL]], ptr [[PY_EPIL_EPIL]], align 4
; FORCED-NEXT:    br label %[[OUTER_LATCH_EPIL]]
; FORCED:       [[OUTER_LATCH_EPIL]]:
; FORCED-NEXT:    [[J_NEXT_EPIL:%.*]] = add nuw nsw i32 [[J_EPIL_INIT]], 1
; FORCED-NEXT:    [[INDVAR_NEXT_EPIL:%.*]] = add i32 [[INDVAR_EPIL_INIT]], 1
; FORCED-NEXT:    [[EPIL_ITER_CMP:%.*]] = icmp ne i32 1, [[XTRAITER2]]
; FORCED-NEXT:    br i1 [[EPIL_ITER_CMP]], label %[[OUTER_EPIL_1:.*]], label %[[EXIT_EPILOG_LCSSA:.*]]
; FORCED:       [[OUTER_EPIL_1]]:
; FORCED-NEXT:    [[XTRAITER_EPIL_1:%.*]] = and i32 [[J_NEXT_EPIL]], 1
; FORCED-NEXT:    [[TMP5:%.*]] = icmp ult i32 [[INDVAR_NEXT_EPIL]], 1
; FORCED-NEXT:    br i1 [[TMP5]], label %[[LOOP_EPIL_PREHEADER_EPIL_1:.*]], label %[[OUTER_NEW_EPIL_1:.*]]
; FORCED:       [[OUTER_NEW_EPIL_1]]:
; FORCED-NEXT:    [[UNROLL_ITER_EPIL_1:%.*]] = sub i32 [[J_NEXT_EPIL]], [[XTRAITER_EPIL_1]]
; FORCED-NEXT:    br label %[[LOOP_EPIL3_1:.*]]
; FORCED:       [[LOOP_EPIL3_1]]:
; FORCED-NEXT:    [[I_EPIL_1:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL_1]] ], [ [[I_NEXT_1_EPIL_1:%.*]], %[[LOOP_EPIL3_1]] ]
; FORCED-NEXT:    [[PREV_EPIL_1:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL_1]] ], [ [[CUR_1_EPIL_1:%.*]], %[[LOOP_EPIL3_1]] ]
; FORCED-NEXT:    [[NITER_EPIL_1:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL_1]] ], [ [[NITER_NEXT_1_EPIL_1:%.*]], %[[LOOP_EPIL3_1]] ]
; FORCED-NEXT:    [[PX_EPIL4_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_1]]
; FORCED-NEXT:    [[CUR_EPIL5_1:%.*]] = load i32, ptr [[PX_EPIL4_1]], align 4
; FORCED-NEXT:    [[PREV3_EPIL6_1:%.*]] = mul i32 [[PREV_EPIL_1]], 3
; FORCED-NEXT:    [[SUM_EPIL7_1:%.*]] = add i32 [[CUR_EPIL5_1]], [[PREV3_EPIL6_1]]
; FORCED-NEXT:    [[PY_EPIL8_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_1]]
; FORCED-NEXT:    store i32 [[SUM_EPIL7_1]], ptr [[PY_EPIL8_1]], align 4
; FORCED-NEXT:    [[I_NEXT_EPIL_1:%.*]] = add nuw nsw i32 [[I_EPIL_1]], 1
; FORCED-NEXT:    [[PX_1_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_NEXT_EPIL_1]]
; FORCED-NEXT:    [[CUR_1_EPIL_1]] = load i32, ptr [[PX_1_EPIL_1]], align 4
; FORCED-NEXT:    [[PREV3_1_EPIL_1:%.*]] = mul i32 [[CUR_EPIL5_1]], 3
; FORCED-NEXT:    [[SUM_1_EPIL_1:%.*]] = add i32 [[CUR_1_EPIL_1]], [[PREV3_1_EPIL_1]]
; FORCED-NEXT:    [[PY_1_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_NEXT_EPIL_1]]
; FORCED-NEXT:    store i32 [[SUM_1_EPIL_1]], ptr [[PY_1_EPIL_1]], align 4
; FORCED-NEXT:    [[I_NEXT_1_EPIL_1]] = add nuw nsw i32 [[I_EPIL_1]], 2
; FORCED-NEXT:    [[NITER_NEXT_1_EPIL_1]] = add i32 [[NITER_EPIL_1]], 2
; FORCED-NEXT:    [[NITER_NCMP_1_EPIL_1:%.*]] = icmp eq i32 [[NITER_NEXT_1_EPIL_1]], [[UNROLL_ITER_EPIL_1]]
; FORCED-NEXT:    br i1 [[NITER_NCMP_1_EPIL_1]], label %[[OUTER_LATCH_UNR_LCSSA_EPIL_1:.*]], label %[[LOOP_EPIL3_1]]
; FORCED:       [[OUTER_LATCH_UNR_LCSSA_EPIL_1]]:
; FORCED-NEXT:    [[I_UNR_EPIL_1:%.*]] = phi i32 [ [[I_NEXT_1_EPIL_1]], %[[LOOP_EPIL3_1]] ]
; FORCED-NEXT:    [[PREV_UNR_EPIL_1:%.*]] = phi i32 [ [[CUR_1_EPIL_1]], %[[LOOP_EPIL3_1]] ]
; FORCED-NEXT:    [[LCMP_MOD_EPIL_1:%.*]] = icmp ne i32 [[XTRAITER_EPIL_1]], 0
; FORCED-NEXT:    br i1 [[LCMP_MOD_EPIL_1]], label %[[LOOP_EPIL_PREHEADER_EPIL_1]], label %[[OUTER_LATCH_EPIL_1:.*]]
; FORCED:       [[LOOP_EPIL_PREHEADER_EPIL_1]]:
; FORCED-NEXT:    [[I_EPIL_INIT_EPIL_1:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_1]] ], [ [[I_UNR_EPIL_1]], %[[OUTER_LATCH_UNR_LCSSA_EPIL_1]] ]
; FORCED-NEXT:    [[PREV_EPIL_INIT_EPIL_1:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_1]] ], [ [[PREV_UNR_EPIL_1]], %[[OUTER_LATCH_UNR_LCSSA_EPIL_1]] ]
; FORCED-NEXT:    [[LCMP_MOD1_EPIL_1:%.*]] = icmp ne i32 [[XTRAITER_EPIL_1]], 0
; FORCED-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD1_EPIL_1]])
; FORCED-NEXT:    br label %[[LOOP_EPIL_EPIL_1:.*]]
; FORCED:       [[LOOP_EPIL_EPIL_1]]:
; FORCED-NEXT:    [[PX_EPIL_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_INIT_EPIL_1]]
; FORCED-NEXT:    [[CUR_EPIL_EPIL_1:%.*]] = load i32, ptr [[PX_EPIL_EPIL_1]], align 4
; FORCED-NEXT:    [[PREV3_EPIL_EPIL_1:%.*]] = mul i32 [[PREV_EPIL_INIT_EPIL_1]], 3
; FORCED-NEXT:    [[SUM_EPIL_EPIL_1:%.*]] = add i32 [[CUR_EPIL_EPIL_1]], [[PREV3_EPIL_EPIL_1]]
; FORCED-NEXT:    [[PY_EPIL_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_INIT_EPIL_1]]
; FORCED-NEXT:    store i32 [[SUM_EPIL_EPIL_1]], ptr [[PY_EPIL_EPIL_1]], align 4
; FORCED-NEXT:    br label %[[OUTER_LATCH_EPIL_1]]
; FORCED:       [[OUTER_LATCH_EPIL_1]]:
; FORCED-NEXT:    [[J_NEXT_EPIL_1:%.*]] = add nuw nsw i32 [[J_EPIL_INIT]], 2
; FORCED-NEXT:    [[INDVAR_NEXT_EPIL_1:%.*]] = add i32 [[INDVAR_EPIL_INIT]], 2
; FORCED-NEXT:    [[EPIL_ITER_CMP_1:%.*]] = icmp ne i32 2, [[XTRAITER2]]
; FORCED-NEXT:    br i1 [[EPIL_ITER_CMP_1]], label %[[OUTER_EPIL_2:.*]], label %[[EXIT_EPILOG_LCSSA]]
; FORCED:       [[OUTER_EPIL_2]]:
; FORCED-NEXT:    [[XTRAITER_EPIL_2:%.*]] = and i32 [[J_NEXT_EPIL_1]], 1
; FORCED-NEXT:    [[TMP6:%.*]] = icmp ult i32 [[INDVAR_NEXT_EPIL_1]], 1
; FORCED-NEXT:    br i1 [[TMP6]], label %[[LOOP_EPIL_PREHEADER_EPIL_2:.*]], label %[[OUTER_NEW_EPIL_2:.*]]
; FORCED:       [[OUTER_NEW_EPIL_2]]:
; FORCED-NEXT:    [[UNROLL_ITER_EPIL_2:%.*]] = sub i32 [[J_NEXT_EPIL_1]], [[XTRAITER_EPIL_2]]
; FORCED-NEXT:    br label %[[LOOP_EPIL3_2:.*]]
; FORCED:       [[LOOP_EPIL3_2]]:
; FORCED-NEXT:    [[I_EPIL_2:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL_2]] ], [ [[I_NEXT_1_EPIL_2:%.*]], %[[LOOP_EPIL3_2]] ]
; FORCED-NEXT:    [[PREV_EPIL_2:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL_2]] ], [ [[CUR_1_EPIL_2:%.*]], %[[LOOP_EPIL3_2]] ]
; FORCED-NEXT:    [[NITER_EPIL_2:%.*]] = phi i32 [ 0, %[[OUTER_NEW_EPIL_2]] ], [ [[NITER_NEXT_1_EPIL_2:%.*]], %[[LOOP_EPIL3_2]] ]
; FORCED-NEXT:    [[PX_EPIL4_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_2]]
; FORCED-NEXT:    [[CUR_EPIL5_2:%.*]] = load i32, ptr [[PX_EPIL4_2]], align 4
; FORCED-NEXT:    [[PREV3_EPIL6_2:%.*]] = mul i32 [[PREV_EPIL_2]], 3
; FORCED-NEXT:    [[SUM_EPIL7_2:%.*]] = add i32 [[CUR_EPIL5_2]], [[PREV3_EPIL6_2]]
; FORCED-NEXT:    [[PY_EPIL8_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_2]]
; FORCED-NEXT:    store i32 [[SUM_EPIL7_2]], ptr [[PY_EPIL8_2]], align 4
; FORCED-NEXT:    [[I_NEXT_EPIL_2:%.*]] = add nuw nsw i32 [[I_EPIL_2]], 1
; FORCED-NEXT:    [[PX_1_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_NEXT_EPIL_2]]
; FORCED-NEXT:    [[CUR_1_EPIL_2]] = load i32, ptr [[PX_1_EPIL_2]], align 4
; FORCED-NEXT:    [[PREV3_1_EPIL_2:%.*]] = mul i32 [[CUR_EPIL5_2]], 3
; FORCED-NEXT:    [[SUM_1_EPIL_2:%.*]] = add i32 [[CUR_1_EPIL_2]], [[PREV3_1_EPIL_2]]
; FORCED-NEXT:    [[PY_1_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_NEXT_EPIL_2]]
; FORCED-NEXT:    store i32 [[SUM_1_EPIL_2]], ptr [[PY_1_EPIL_2]], align 4
; FORCED-NEXT:    [[I_NEXT_1_EPIL_2]] = add nuw nsw i32 [[I_EPIL_2]], 2
; FORCED-NEXT:    [[NITER_NEXT_1_EPIL_2]] = add i32 [[NITER_EPIL_2]], 2
; FORCED-NEXT:    [[NITER_NCMP_1_EPIL_2:%.*]] = icmp eq i32 [[NITER_NEXT_1_EPIL_2]], [[UNROLL_ITER_EPIL_2]]
; FORCED-NEXT:    br i1 [[NITER_NCMP_1_EPIL_2]], label %[[OUTER_LATCH_UNR_LCSSA_EPIL_2:.*]], label %[[LOOP_EPIL3_2]]
; FORCED:       [[OUTER_LATCH_UNR_LCSSA_EPIL_2]]:
; FORCED-NEXT:    [[I_UNR_EPIL_2:%.*]] = phi i32 [ [[I_NEXT_1_EPIL_2]], %[[LOOP_EPIL3_2]] ]
; FORCED-NEXT:    [[PREV_UNR_EPIL_2:%.*]] = phi i32 [ [[CUR_1_EPIL_2]], %[[LOOP_EPIL3_2]] ]
; FORCED-NEXT:    [[LCMP_MOD_EPIL_2:%.*]] = icmp ne i32 [[XTRAITER_EPIL_2]], 0
; FORCED-NEXT:    br i1 [[LCMP_MOD_EPIL_2]], label %[[LOOP_EPIL_PREHEADER_EPIL_2]], label %[[OUTER_LATCH_EPIL_2:.*]]
; FORCED:       [[LOOP_EPIL_PREHEADER_EPIL_2]]:
; FORCED-NEXT:    [[I_EPIL_INIT_EPIL_2:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_2]] ], [ [[I_UNR_EPIL_2]], %[[OUTER_LATCH_UNR_LCSSA_EPIL_2]] ]
; FORCED-NEXT:    [[PREV_EPIL_INIT_EPIL_2:%.*]] = phi i32 [ 0, %[[OUTER_EPIL_2]] ], [ [[PREV_UNR_EPIL_2]], %[[OUTER_LATCH_UNR_LCSSA_EPIL_2]] ]
; FORCED-NEXT:    [[LCMP_MOD1_EPIL_2:%.*]] = icmp ne i32 [[XTRAITER_EPIL_2]], 0
; FORCED-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD1_EPIL_2]])
; FORCED-NEXT:    br label %[[LOOP_EPIL_EPIL_2:.*]]
; FORCED:       [[LOOP_EPIL_EPIL_2]]:
; FORCED-NEXT:    [[PX_EPIL_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[I_EPIL_INIT_EPIL_2]]
; FORCED-NEXT:    [[CUR_EPIL_EPIL_2:%.*]] = load i32, ptr [[PX_EPIL_EPIL_2]], align 4
; FORCED-NEXT:    [[PREV3_EPIL_EPIL_2:%.*]] = mul i32 [[PREV_EPIL_INIT_EPIL_2]], 3
; FORCED-NEXT:    [[SUM_EPIL_EPIL_2:%.*]] = add i32 [[CUR_EPIL_EPIL_2]], [[PREV3_EPIL_EPIL_2]]
; FORCED-NEXT:    [[PY_EPIL_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[Y]], i32 [[I_EPIL_INIT_EPIL_2]]
; FORCED-NEXT:    store i32 [[SUM_EPIL_EPIL_2]], ptr [[PY_EPIL_EPIL_2]], align 4
; FORCED-NEXT:    br label %[[OUTER_LATCH_EPIL_2]]
; FORCED:       [[OUTER_LATCH_EPIL_2]]:
; FORCED-NEXT:    br label %[[EXIT_EPILOG_LCSSA]]
; FORCED:       [[EXIT_EPILOG_LCSSA]]:
; FORCED-NEXT:    br label %[[EXIT]]
; FORCED:       [[EXIT]]:
; FORCED-NEXT:    ret void
;
entry:
  br label %outer

outer:
  %j = phi i32 [ 1, %entry ], [ %j.next, %outer.latch ]
  br label %loop

loop:
  %i = phi i32 [ 0, %outer ], [ %i.next, %loop ]
  %prev = phi i32 [ 0, %outer ], [ %cur, %loop ]
  %px = getelementptr inbounds i32, ptr %x, i32 %i
  %cur = load i32, ptr %px
  %prev3 = mul i32 %prev, 3
  %sum = add i32 %cur, %prev3
  %py = getelementptr inbounds i32, ptr %y, i32 %i
  store i32 %sum, ptr %py
  %i.next = add nuw nsw i32 %i, 1
  %inner.done = icmp eq i32 %i.next, %j
  br i1 %inner.done, label %outer.latch, label %loop

outer.latch:
  %j.next = add nuw nsw i32 %j, 1
  %done = icmp eq i32 %j.next, %n
  br i1 %done, label %exit, label %outer

exit:
  ret void
}

; Rotating three values: a cycle that needs a multiple of three, where runtime
; unrolling alone would pick four.
define void @rotate(ptr %p, ptr %q, ptr %r, ptr %out) {
; DEFAULT-LABEL: define void @rotate(
; DEFAULT-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; DEFAULT-NEXT:  [[ENTRY:.*:]]
; DEFAULT-NEXT:    br label %[[LOOP:.*]]
; DEFAULT:       [[LOOP]]:
; DEFAULT-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; DEFAULT-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; DEFAULT-NEXT:    [[DONE:%.*]] = icmp eq i32 [[V]], 0
; DEFAULT-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; DEFAULT:       [[LOOP_1]]:
; DEFAULT-NEXT:    [[V_1:%.*]] = load i32, ptr [[Q]], align 4
; DEFAULT-NEXT:    store i32 [[V_1]], ptr [[OUT]], align 4
; DEFAULT-NEXT:    [[DONE_1:%.*]] = icmp eq i32 [[V_1]], 0
; DEFAULT-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2:.*]]
; DEFAULT:       [[LOOP_2]]:
; DEFAULT-NEXT:    [[V_2:%.*]] = load i32, ptr [[R]], align 4
; DEFAULT-NEXT:    store i32 [[V_2]], ptr [[OUT]], align 4
; DEFAULT-NEXT:    [[DONE_2:%.*]] = icmp eq i32 [[V_2]], 0
; DEFAULT-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; DEFAULT:       [[EXIT]]:
; DEFAULT-NEXT:    ret void
;
; FORCED-LABEL: define void @rotate(
; FORCED-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], ptr [[R:%.*]], ptr [[OUT:%.*]]) #[[ATTR0]] {
; FORCED-NEXT:  [[ENTRY:.*:]]
; FORCED-NEXT:    br label %[[LOOP:.*]]
; FORCED:       [[LOOP]]:
; FORCED-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; FORCED-NEXT:    store i32 [[V]], ptr [[OUT]], align 4
; FORCED-NEXT:    [[DONE:%.*]] = icmp eq i32 [[V]], 0
; FORCED-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LOOP_1:.*]]
; FORCED:       [[LOOP_1]]:
; FORCED-NEXT:    [[V_1:%.*]] = load i32, ptr [[Q]], align 4
; FORCED-NEXT:    store i32 [[V_1]], ptr [[OUT]], align 4
; FORCED-NEXT:    [[DONE_1:%.*]] = icmp eq i32 [[V_1]], 0
; FORCED-NEXT:    br i1 [[DONE_1]], label %[[EXIT]], label %[[LOOP_2:.*]]
; FORCED:       [[LOOP_2]]:
; FORCED-NEXT:    [[V_2:%.*]] = load i32, ptr [[R]], align 4
; FORCED-NEXT:    store i32 [[V_2]], ptr [[OUT]], align 4
; FORCED-NEXT:    [[DONE_2:%.*]] = icmp eq i32 [[V_2]], 0
; FORCED-NEXT:    br i1 [[DONE_2]], label %[[EXIT]], label %[[LOOP]]
; FORCED:       [[EXIT]]:
; FORCED-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %a = phi ptr [ %p, %entry ], [ %b, %loop ]
  %b = phi ptr [ %q, %entry ], [ %c, %loop ]
  %c = phi ptr [ %r, %entry ], [ %a, %loop ]
  %v = load i32, ptr %a
  store i32 %v, ptr %out
  %done = icmp eq i32 %v, 0
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

declare <4 x i1> @llvm.arm.mve.vctp32(i32)
declare <4 x i32> @llvm.masked.load.v4i32.p0(ptr, i32, <4 x i1>, <4 x i32>)
declare void @llvm.masked.store.v4i32.p0(<4 x i32>, ptr, i32, <4 x i1>)

