; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; The slot a guarded case leaves in the table is never loaded, but when inlining
; has replicated a dispatch, each copy guards a different case, so a slot that
; differs between copies leaves tables that are alike everywhere except in the
; byte nothing reads -- and therefore cannot be merged. Where the case's own
; value can be recovered, it goes in the slot and the copies stay identical.

; RUN: opt < %s -passes='simplifycfg<switch-to-lookup>' -S \
; RUN:   -simplifycfg-require-and-preserve-domtree=1 | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

declare i64 @h0(ptr)
declare i64 @h1(ptr)
declare i64 @h2(ptr)
declare i64 @h3(ptr)
declare i64 @h4(ptr)
declare i64 @h5(ptr)
declare i64 @hd(ptr)
declare void @sideeffect()

; The guarded case reaches a copy of the common destination in which the phi has
; been replaced by the constant it holds on that path -- the shape indirect call
; promotion and jump threading leave behind. That constant is recovered, so the
; slot holds @h1 rather than the default @hd.

;.
; CHECK: @switch.table.recovered_entry = private unnamed_addr constant [6 x ptr] [ptr @h0, ptr @h1, ptr @h2, ptr @h3, ptr @h4, ptr @h5], align 8
; CHECK: @switch.table.recovered_entry_would_widen = private unnamed_addr constant [6 x i8] c"\0A\0A\0C\0D\0E\0F", align 8
; CHECK: @switch.table.icp_residual_compare = private unnamed_addr constant [6 x ptr] [ptr @h0, ptr @h1, ptr @h2, ptr @h3, ptr @h4, ptr @h5], align 8
; CHECK: @switch.table.unmatched_entry = private unnamed_addr constant [6 x ptr] [ptr @h0, ptr @hd, ptr @h2, ptr @h3, ptr @h4, ptr @h5], align 8
;.
define i64 @recovered_entry(i8 %op, ptr %arg) {
; CHECK-LABEL: define i64 @recovered_entry(
; CHECK-SAME: i8 [[OP:%.*]], ptr [[ARG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[OP]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[DIRECT:.*]], label %[[ENTRY_LOOKUP:.*]]
; CHECK:       [[ENTRY_LOOKUP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i8 [[OP]], 6
; CHECK-NEXT:    br i1 [[TMP0]], label %[[SWITCH_LOOKUP:.*]], label %[[JOIN:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i64 [ [[D:%.*]], %[[DIRECT]] ], [ [[R:%.*]], %[[JOIN]] ]
; CHECK-NEXT:    ret i64 [[COMMON_RET_OP]]
; CHECK:       [[DIRECT]]:
; CHECK-NEXT:    [[D]] = call i64 @h1(ptr [[ARG]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[SWITCH_LOOKUP]]:
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i8 [[OP]] to i64
; CHECK-NEXT:    [[SWITCH_GEP:%.*]] = getelementptr inbounds [6 x ptr], ptr @switch.table.recovered_entry, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[SWITCH_LOAD:%.*]] = load ptr, ptr [[SWITCH_GEP]], align 8
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[H:%.*]] = phi ptr [ [[SWITCH_LOAD]], %[[SWITCH_LOOKUP]] ], [ @hd, %[[ENTRY_LOOKUP]] ]
; CHECK-NEXT:    [[R]] = call i64 [[H]](ptr [[ARG]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  switch i8 %op, label %def [
  i8 0, label %c0
  i8 1, label %direct
  i8 2, label %c2
  i8 3, label %c3
  i8 4, label %c4
  i8 5, label %c5
  ]

c0:
  br label %join
c2:
  br label %join
c3:
  br label %join
c4:
  br label %join
c5:
  br label %join
def:
  br label %join

direct:
  %d = call i64 @h1(ptr %arg)
  ret i64 %d

join:
  %h = phi ptr [ @h0, %c0 ], [ @h2, %c2 ], [ @h3, %c3 ], [ @h4, %c4 ], [ @h5, %c5 ], [ @hd, %def ]
  %r = call i64 %h(ptr %arg)
  ret i64 %r
}

; Here the copy differs from the common destination in a way the match does not
; see through, so nothing is recovered and the slot keeps the filler the guard
; put there. The table is still built.


; A recovered value wider than anything the other cases contribute would widen
; the table's element type to carry a value nothing reads, so it is not taken.

define i64 @recovered_entry_would_widen(i8 %op) {
; CHECK-LABEL: define i64 @recovered_entry_would_widen(
; CHECK-SAME: i8 [[OP:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[OP]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[DIRECT:.*]], label %[[ENTRY_LOOKUP:.*]]
; CHECK:       [[ENTRY_LOOKUP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i8 [[OP]], 6
; CHECK-NEXT:    br i1 [[TMP0]], label %[[SWITCH_LOOKUP:.*]], label %[[JOIN:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i64 [ [[D:%.*]], %[[DIRECT]] ], [ [[R:%.*]], %[[JOIN]] ]
; CHECK-NEXT:    ret i64 [[COMMON_RET_OP]]
; CHECK:       [[DIRECT]]:
; CHECK-NEXT:    [[D]] = call i64 @use(i64 999999)
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[SWITCH_LOOKUP]]:
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i8 [[OP]] to i64
; CHECK-NEXT:    [[SWITCH_GEP:%.*]] = getelementptr inbounds [6 x i8], ptr @switch.table.recovered_entry_would_widen, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[SWITCH_LOAD:%.*]] = load i8, ptr [[SWITCH_GEP]], align 1
; CHECK-NEXT:    [[SWITCH_EXT:%.*]] = zext i8 [[SWITCH_LOAD]] to i64
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[V:%.*]] = phi i64 [ [[SWITCH_EXT]], %[[SWITCH_LOOKUP]] ], [ 16, %[[ENTRY_LOOKUP]] ]
; CHECK-NEXT:    [[R]] = call i64 @use(i64 [[V]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  switch i8 %op, label %def [
  i8 0, label %c0
  i8 1, label %direct
  i8 2, label %c2
  i8 3, label %c3
  i8 4, label %c4
  i8 5, label %c5
  ]

c0:
  br label %join
c2:
  br label %join
c3:
  br label %join
c4:
  br label %join
c5:
  br label %join
def:
  br label %join

direct:
  %d = call i64 @use(i64 999999)
  ret i64 %d

join:
  %v = phi i64 [ 10, %c0 ], [ 12, %c2 ], [ 13, %c3 ], [ 14, %c4 ], [ 15, %c5 ], [ 16, %def ]
  %r = call i64 @use(i64 %v)
  ret i64 %r
}

; Indirect call promotion does not leave the common destination as a bare
; indirect call: it leaves it testing the phi against the target it promoted,
; and the specialized case reaches a copy of the side that test selects. The phi
; is already gone there, so the value it would have held is the one the test
; names. Without this the slot keeps a filler, and copies of one dispatch that
; guard different cases produce tables that differ only in the byte nothing
; reads -- which is exactly what stops them merging.

define i64 @icp_residual_compare(i8 %op, ptr %arg) {
; CHECK-LABEL: define i64 @icp_residual_compare(
; CHECK-SAME: i8 [[OP:%.*]], ptr [[ARG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[OP]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[DIRECT:.*]], label %[[ENTRY_LOOKUP:.*]]
; CHECK:       [[ENTRY_LOOKUP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i8 [[OP]], 6
; CHECK-NEXT:    br i1 [[TMP0]], label %[[SWITCH_LOOKUP:.*]], label %[[JOIN:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i64 [ [[D:%.*]], %[[DIRECT]] ], [ [[R1:%.*]], %[[ICP_DIRECT:.*]] ], [ [[R2:%.*]], %[[ICP_INDIRECT:.*]] ]
; CHECK-NEXT:    ret i64 [[COMMON_RET_OP]]
; CHECK:       [[DIRECT]]:
; CHECK-NEXT:    [[D]] = call i64 @h1(ptr [[ARG]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[SWITCH_LOOKUP]]:
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i8 [[OP]] to i64
; CHECK-NEXT:    [[SWITCH_GEP:%.*]] = getelementptr inbounds [6 x ptr], ptr @switch.table.icp_residual_compare, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[SWITCH_LOAD:%.*]] = load ptr, ptr [[SWITCH_GEP]], align 8
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[H:%.*]] = phi ptr [ [[SWITCH_LOAD]], %[[SWITCH_LOOKUP]] ], [ @hd, %[[ENTRY_LOOKUP]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[H]], @h1
; CHECK-NEXT:    br i1 [[CMP]], label %[[ICP_DIRECT]], label %[[ICP_INDIRECT]]
; CHECK:       [[ICP_DIRECT]]:
; CHECK-NEXT:    [[R1]] = call i64 @h1(ptr [[ARG]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[ICP_INDIRECT]]:
; CHECK-NEXT:    [[R2]] = call i64 [[H]](ptr [[ARG]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  switch i8 %op, label %def [
  i8 0, label %c0
  i8 1, label %direct
  i8 2, label %c2
  i8 3, label %c3
  i8 4, label %c4
  i8 5, label %c5
  ]

c0:
  br label %join
c2:
  br label %join
c3:
  br label %join
c4:
  br label %join
c5:
  br label %join
def:
  br label %join

direct:
  %d = call i64 @h1(ptr %arg)
  ret i64 %d

join:
  %h = phi ptr [ @h0, %c0 ], [ @h2, %c2 ], [ @h3, %c3 ], [ @h4, %c4 ], [ @h5, %c5 ], [ @hd, %def ]
  %cmp = icmp eq ptr %h, @h1
  br i1 %cmp, label %icp.direct, label %icp.indirect

icp.direct:
  %r1 = call i64 @h1(ptr %arg)
  ret i64 %r1

icp.indirect:
  %r2 = call i64 %h(ptr %arg)
  ret i64 %r2
}

declare i64 @use(i64)



declare void @f0()
declare void @f1()
declare void @f3()
declare void @f4()



; A case whose destination is not a copy of the common one keeps the stand-in
; value chosen for its slot: nothing is guessed in its place.
define i64 @unmatched_entry(i8 %op, ptr %arg) {
; CHECK-LABEL: define i64 @unmatched_entry(
; CHECK-SAME: i8 [[OP:%.*]], ptr [[ARG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i8 [[OP]], 1
; CHECK-NEXT:    br i1 [[COND]], label %[[DIRECT:.*]], label %[[ENTRY_LOOKUP:.*]]
; CHECK:       [[ENTRY_LOOKUP]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i8 [[OP]], 6
; CHECK-NEXT:    br i1 [[TMP0]], label %[[SWITCH_LOOKUP:.*]], label %[[JOIN:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i64 [ [[D:%.*]], %[[DIRECT]] ], [ [[R:%.*]], %[[JOIN]] ]
; CHECK-NEXT:    ret i64 [[COMMON_RET_OP]]
; CHECK:       [[DIRECT]]:
; CHECK-NEXT:    call void @sideeffect()
; CHECK-NEXT:    [[D]] = call i64 @h1(ptr [[ARG]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[SWITCH_LOOKUP]]:
; CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i8 [[OP]] to i64
; CHECK-NEXT:    [[SWITCH_GEP:%.*]] = getelementptr inbounds [6 x ptr], ptr @switch.table.unmatched_entry, i64 0, i64 [[TMP1]]
; CHECK-NEXT:    [[SWITCH_LOAD:%.*]] = load ptr, ptr [[SWITCH_GEP]], align 8
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[H:%.*]] = phi ptr [ [[SWITCH_LOAD]], %[[SWITCH_LOOKUP]] ], [ @hd, %[[ENTRY_LOOKUP]] ]
; CHECK-NEXT:    [[R]] = call i64 [[H]](ptr [[ARG]])
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  switch i8 %op, label %def [
  i8 0, label %c0
  i8 1, label %direct
  i8 2, label %c2
  i8 3, label %c3
  i8 4, label %c4
  i8 5, label %c5
  ]

c0:
  br label %join
c2:
  br label %join
c3:
  br label %join
c4:
  br label %join
c5:
  br label %join
def:
  br label %join

direct:
  call void @sideeffect()
  %d = call i64 @h1(ptr %arg)
  ret i64 %d

join:
  %h = phi ptr [ @h0, %c0 ], [ @h2, %c2 ], [ @h3, %c3 ], [ @h4, %c4 ], [ @h5, %c5 ], [ @hd, %def ]
  %r = call i64 %h(ptr %arg)
  ret i64 %r
}
