; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -constraint-elimination-max-inductive-bound-checks=1 -S %s | FileCheck %s

declare void @use(i1)
declare i1 @cond()

; Only a single constraint system may be built to check if bounds are
; inductive, so only the bound of %n.0 is proven.
define void @two_counters() {
; CHECK-LABEL: define void @two_counters() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N_0:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_0_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[N_1:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_1_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_1:%.*]] = icmp ult i64 [[N_1]], 1000
; CHECK-NEXT:    call void @use(i1 [[C_1]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC_0:%.*]] = add nuw nsw i64 [[N_0]], 1
; CHECK-NEXT:    [[INC_1:%.*]] = add nuw nsw i64 [[N_1]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC_0]], 1000
; CHECK-NEXT:    [[FULL_1:%.*]] = icmp eq i64 [[INC_1]], 1000
; CHECK-NEXT:    [[OR:%.*]] = or i1 [[FULL]], [[FULL_1]]
; CHECK-NEXT:    br i1 [[OR]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_0_NEXT]] = phi i64 [ [[INC_0]], %[[THEN]] ], [ [[N_0]], %[[HEADER]] ]
; CHECK-NEXT:    [[N_1_NEXT]] = phi i64 [ [[INC_1]], %[[THEN]] ], [ [[N_1]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n.0 = phi i64 [ 0, %entry ], [ %n.0.next, %latch ]
  %n.1 = phi i64 [ 0, %entry ], [ %n.1.next, %latch ]
  %t.0 = icmp ult i64 %n.0, 1000
  call void @use(i1 %t.0)
  %c.1 = icmp ult i64 %n.1, 1000
  call void @use(i1 %c.1)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc.0 = add nuw nsw i64 %n.0, 1
  %inc.1 = add nuw nsw i64 %n.1, 1
  %full = icmp eq i64 %inc.0, 1000
  %full.1 = icmp eq i64 %inc.1, 1000
  %or = or i1 %full, %full.1
  br i1 %or, label %exit, label %latch

latch:
  %n.0.next = phi i64 [ %inc.0, %then ], [ %n.0, %header ]
  %n.1.next = phi i64 [ %inc.1, %then ], [ %n.1, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}
