; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=constraint-elimination -S %s | FileCheck %s

declare void @use(i1)
declare i1 @cond()
declare i64 @get()
declare void @llvm.assume(i1)

; A counter that is only incremented on some paths, with the loop exiting once
; the incremented value reaches the bound, cannot exceed the bound. Both the
; in-loop and the post-loop checks can be removed.
define i64 @inc_exit_on_eq(ptr %c, i64 %len, ptr %out) {
; CHECK-LABEL: define i64 @inc_exit_on_eq(
; CHECK-SAME: ptr [[C:%.*]], i64 [[LEN:%.*]], ptr [[OUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[IV]], [[LEN]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT_CHECK:.*]], label %[[BODY:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[C_GEP:%.*]] = getelementptr inbounds nuw i8, ptr [[C]], i64 [[IV]]
; CHECK-NEXT:    [[C_V:%.*]] = load i1, ptr [[C_GEP]], align 1
; CHECK-NEXT:    br i1 [[C_V]], label %[[CHECK:.*]], label %[[LATCH]]
; CHECK:       [[CHECK]]:
; CHECK-NEXT:    br i1 true, label %[[THEN:.*]], label %[[TRAP:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[OUT]], i64 [[N]]
; CHECK-NEXT:    store i32 1, ptr [[GEP]], align 4
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[BODY]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i64 [[IV]], 1
; CHECK-NEXT:    br label %[[HEADER]]
; CHECK:       [[TRAP]]:
; CHECK-NEXT:    call void @use(i1 false)
; CHECK-NEXT:    unreachable
; CHECK:       [[EXIT_CHECK]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT]], label %[[TRAP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RES:%.*]] = phi i64 [ [[N]], %[[EXIT_CHECK]] ], [ 1000, %[[THEN]] ]
; CHECK-NEXT:    ret i64 [[RES]]
;
entry:
  br label %header

header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %done = icmp eq i64 %iv, %len
  br i1 %done, label %exit.check, label %body

body:
  %c.gep = getelementptr inbounds nuw i8, ptr %c, i64 %iv
  %c.v = load i1, ptr %c.gep, align 1
  br i1 %c.v, label %check, label %latch

check:
  %in.bounds = icmp ult i64 %n, 1000
  br i1 %in.bounds, label %then, label %trap

then:
  %gep = getelementptr inbounds nuw i32, ptr %out, i64 %n
  store i32 1, ptr %gep, align 4
  %inc = add nuw nsw i64 %n, 1
  %full = icmp eq i64 %inc, 1000
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %body ]
  %iv.next = add nuw i64 %iv, 1
  br label %header

trap:
  call void @use(i1 false)
  unreachable

exit.check:
  %slice.ok = icmp ule i64 %n, 1000
  br i1 %slice.ok, label %exit, label %trap

exit:
  %res = phi i64 [ %n, %exit.check ], [ 1000, %then ]
  ret i64 %res
}

; The counter itself is not compared against the bound, so the bound has to be
; taken from the compare of the increment.
define void @inc_exit_on_eq_only_post_loop_use() {
; CHECK-LABEL: define void @inc_exit_on_eq_only_post_loop_use() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[N_1:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 1
  %full = icmp eq i64 %inc, 1000
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  %n.1 = add nuw i64 %n, 1
  %t.0 = icmp ule i64 %n.1, 1000
  call void @use(i1 %t.0)
  ret void
}

; The loop exits once the increment reaches the bound.
define void @inc_exit_on_uge() {
; CHECK-LABEL: define void @inc_exit_on_uge() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp uge i64 [[INC]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %t.0 = icmp ult i64 %n, 1000
  call void @use(i1 %t.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 1
  %full = icmp uge i64 %inc, 1000
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; The loop continues while the increment is at most the bound, so the counter
; is at most the bound, but may be equal to it.
define void @inc_exit_on_ugt() {
; CHECK-LABEL: define void @inc_exit_on_ugt() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], 1000
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp ugt i64 [[INC]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %t.0 = icmp ule i64 %n, 1000
  call void @use(i1 %t.0)
  %c.0 = icmp ult i64 %n, 1000
  call void @use(i1 %c.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 1
  %full = icmp ugt i64 %inc, 1000
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; The exit condition is on the counter rather than the increment, as
; InstCombine produces for `inc >= 1000` when `n < 1000` is known.
define void @inc_exit_on_phi_eq() {
; CHECK-LABEL: define void @inc_exit_on_phi_eq() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[CHECK:.*]], label %[[LATCH]]
; CHECK:       [[CHECK]]:
; CHECK-NEXT:    br i1 true, label %[[THEN:.*]], label %[[EXIT:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[N]], 999
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c = call i1 @cond()
  br i1 %c, label %check, label %latch

check:
  %in.bounds = icmp samesign ult i64 %n, 1000
  br i1 %in.bounds, label %then, label %exit

then:
  %inc = add nuw nsw i64 %n, 1
  %full = icmp eq i64 %n, 999
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  %t.0 = icmp ult i64 %n, 1001
  call void @use(i1 %t.0)
  ret void
}

; The loop exits when the counter reaches the bound before incrementing it.
define void @inc_exit_on_phi_eq_before_inc() {
; CHECK-LABEL: define void @inc_exit_on_phi_eq_before_inc() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[CHECK:.*]], label %[[LATCH]]
; CHECK:       [[CHECK]]:
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[N]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[THEN:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c = call i1 @cond()
  br i1 %c, label %check, label %latch

check:
  %full = icmp eq i64 %n, 1000
  br i1 %full, label %exit, label %then

then:
  %t.0 = icmp ult i64 %n, 1000
  call void @use(i1 %t.0)
  %inc = add nuw nsw i64 %n, 1
  br label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  %t.1 = icmp ule i64 %n, 1000
  call void @use(i1 %t.1)
  ret void
}

; The counter is only incremented while it is below the bound, so it is at most
; the bound, but may be equal to it.
define void @inc_guarded_by_ult() {
; CHECK-LABEL: define void @inc_guarded_by_ult() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    [[ROOM:%.*]] = icmp ult i64 [[N]], 1000
; CHECK-NEXT:    [[AND:%.*]] = select i1 [[C]], i1 [[ROOM]], i1 false
; CHECK-NEXT:    br i1 [[AND]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], 1000
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c = call i1 @cond()
  %room = icmp ult i64 %n, 1000
  %and = select i1 %c, i1 %room, i1 false
  br i1 %and, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 1
  br label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  %t.0 = icmp ule i64 %n, 1000
  call void @use(i1 %t.0)
  %c.0 = icmp ult i64 %n, 1000
  call void @use(i1 %c.0)
  ret void
}

; The counter may be incremented in two different places, and reset to zero.
define void @inc_multiple_paths() {
; CHECK-LABEL: define void @inc_multiple_paths() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_0:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C_0]], label %[[THEN_0:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN_0]]:
; CHECK-NEXT:    [[INC_0:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL_0:%.*]] = icmp eq i64 [[INC_0]], 16
; CHECK-NEXT:    br i1 [[FULL_0]], label %[[EXIT:.*]], label %[[MERGE:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    [[C_1:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C_1]], label %[[THEN_1:.*]], label %[[RESET:.*]]
; CHECK:       [[THEN_1]]:
; CHECK-NEXT:    [[INC_1:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL_1:%.*]] = icmp ult i64 [[INC_1]], 16
; CHECK-NEXT:    br i1 [[FULL_1]], label %[[MERGE]], label %[[RESET]]
; CHECK:       [[RESET]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[N_MERGE:%.*]] = phi i64 [ [[INC_0]], %[[THEN_0]] ], [ [[INC_1]], %[[THEN_1]] ], [ 0, %[[RESET]] ]
; CHECK-NEXT:    [[C_2:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C_2]], label %[[LATCH]], label %[[SKIP:.*]]
; CHECK:       [[SKIP]]:
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[N_MERGE]], %[[MERGE]] ], [ [[N]], %[[SKIP]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %t.0 = icmp ult i64 %n, 16
  call void @use(i1 %t.0)
  %c.0 = call i1 @cond()
  br i1 %c.0, label %then.0, label %else

then.0:
  %inc.0 = add nuw i64 %n, 1
  %full.0 = icmp eq i64 %inc.0, 16
  br i1 %full.0, label %exit, label %merge

else:
  %c.1 = call i1 @cond()
  br i1 %c.1, label %then.1, label %reset

then.1:
  %inc.1 = add nuw i64 %n, 1
  %full.1 = icmp ult i64 %inc.1, 16
  br i1 %full.1, label %merge, label %reset

reset:
  br label %merge

merge:
  %n.merge = phi i64 [ %inc.0, %then.0 ], [ %inc.1, %then.1 ], [ 0, %reset ]
  %c.2 = call i1 @cond()
  br i1 %c.2, label %latch, label %skip

skip:
  br label %latch

latch:
  %n.next = phi i64 [ %n.merge, %merge ], [ %n, %skip ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Signed counter with a negative start value, bounded by an unsigned compare of
; the increment. Only the signed bound holds for the start value.
define void @inc_signed_bounded_by_unsigned_compare() {
; CHECK-LABEL: define void @inc_signed_bounded_by_unsigned_compare() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i32 [ -5, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i32 [[N]], 100
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[N]], 1
; CHECK-NEXT:    [[ROOM:%.*]] = icmp ult i32 [[INC]], 100
; CHECK-NEXT:    br i1 [[ROOM]], label %[[LATCH]], label %[[EXIT:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i32 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i32 [ -5, %entry ], [ %n.next, %latch ]
  %t.0 = icmp slt i32 %n, 100
  call void @use(i1 %t.0)
  %c.0 = icmp ult i32 %n, 100
  call void @use(i1 %c.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nsw i32 %n, 1
  %room = icmp ult i32 %inc, 100
  br i1 %room, label %latch, label %exit

latch:
  %n.next = phi i32 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Narrow counter without no-wrap flags on the increment.
define void @inc_i8_no_wrap_flags() {
; CHECK-LABEL: define void @inc_i8_no_wrap_flags() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i8 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i8 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i8 [[INC]], 100
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i8 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i8 [ 0, %entry ], [ %n.next, %latch ]
  %t.0 = icmp ult i8 %n, 100
  call void @use(i1 %t.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add i8 %n, 1
  %full = icmp eq i8 %inc, 100
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i8 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; A loop-invariant bound, which is only known to be larger than the start
; value due to the loop guard.
define void @inc_symbolic_bound(i64 %bound) {
; CHECK-LABEL: define void @inc_symbolic_bound(
; CHECK-SAME: i64 [[BOUND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ugt i64 [[BOUND]], 0
; CHECK-NEXT:    br i1 [[PRE]], label %[[HEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], [[BOUND]]
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ugt i64 %bound, 0
  br i1 %pre, label %header, label %exit

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %t.0 = icmp ult i64 %n, %bound
  call void @use(i1 %t.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw i64 %n, 1
  %full = icmp eq i64 %inc, %bound
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; The counter is set to values below the bound. Both the strict and the
; non-strict bounds are inductive, but the start value may be equal to the
; bound, so only the non-strict bound holds.
define void @set_below_bound_start_may_equal_bound(i64 %start, i64 %bound) {
; CHECK-LABEL: define void @set_below_bound_start_may_equal_bound(
; CHECK-SAME: i64 [[START:%.*]], i64 [[BOUND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[PRE:%.*]] = icmp ule i64 [[START]], [[BOUND]]
; CHECK-NEXT:    br i1 [[PRE]], label %[[HEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ [[START]], %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], [[BOUND]]
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[X:%.*]] = call i64 @get()
; CHECK-NEXT:    [[SMALL:%.*]] = icmp ult i64 [[X]], [[BOUND]]
; CHECK-NEXT:    br i1 [[SMALL]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[X]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %pre = icmp ule i64 %start, %bound
  br i1 %pre, label %header, label %exit

header:
  %n = phi i64 [ %start, %entry ], [ %n.next, %latch ]
  %t.0 = icmp ule i64 %n, %bound
  call void @use(i1 %t.0)
  %c.0 = icmp ult i64 %n, %bound
  call void @use(i1 %c.0)
  %x = call i64 @get()
  %small = icmp ult i64 %x, %bound
  br i1 %small, label %then, label %latch

then:
  br label %latch

latch:
  %n.next = phi i64 [ %x, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; The values flowing into the backedge value pass through the header phi of an
; inner loop.
define void @set_in_inner_loop() {
; CHECK-LABEL: define void @set_in_inner_loop() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[M_LCSSA:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[M:%.*]] = phi i64 [ [[N]], %[[HEADER]] ], [ [[M_NEXT:%.*]], %[[INNER_LATCH:.*]] ]
; CHECK-NEXT:    [[X:%.*]] = call i64 @get()
; CHECK-NEXT:    [[SMALL:%.*]] = icmp ult i64 [[X]], 1000
; CHECK-NEXT:    br i1 [[SMALL]], label %[[INNER_THEN:.*]], label %[[INNER_LATCH]]
; CHECK:       [[INNER_THEN]]:
; CHECK-NEXT:    br label %[[INNER_LATCH]]
; CHECK:       [[INNER_LATCH]]:
; CHECK-NEXT:    [[M_NEXT]] = phi i64 [ [[X]], %[[INNER_THEN]] ], [ [[M]], %[[INNER]] ]
; CHECK-NEXT:    [[INNER_C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[INNER_C]], label %[[INNER]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[M_LCSSA]] = phi i64 [ [[M_NEXT]], %[[INNER_LATCH]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %m.lcssa, %latch ]
  %t.0 = icmp ult i64 %n, 1000
  call void @use(i1 %t.0)
  br label %inner

inner:
  %m = phi i64 [ %n, %header ], [ %m.next, %inner.latch ]
  %x = call i64 @get()
  %small = icmp ult i64 %x, 1000
  br i1 %small, label %inner.then, label %inner.latch

inner.then:
  br label %inner.latch

inner.latch:
  %m.next = phi i64 [ %x, %inner.then ], [ %m, %inner ]
  %inner.c = call i1 @cond()
  br i1 %inner.c, label %inner, label %latch

latch:
  %m.lcssa = phi i64 [ %m.next, %inner.latch ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; A value flowing into the backedge value from an unreachable block is ignored.
define void @incoming_from_unreachable_block() {
; CHECK-LABEL: define void @incoming_from_unreachable_block() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    call void @use(i1 true)
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[DEAD:.*]]:
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ], [ 2000, %[[DEAD]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %t.0 = icmp ult i64 %n, 1000
  call void @use(i1 %t.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 1
  %full = icmp eq i64 %inc, 1000
  br i1 %full, label %exit, label %latch

dead:
  br label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ], [ 2000, %dead ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; TODO: The counter is incremented in an inner loop. Bounding it requires also
; bounding the phi of the inner loop.
define void @inc_in_inner_loop() {
; CHECK-LABEL: define void @inc_in_inner_loop() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[M_LCSSA:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[T_0:%.*]] = icmp ult i64 [[N]], 1000
; CHECK-NEXT:    call void @use(i1 [[T_0]])
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[M:%.*]] = phi i64 [ [[N]], %[[HEADER]] ], [ [[M_NEXT:%.*]], %[[INNER_LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[INNER_THEN:.*]], label %[[INNER_LATCH]]
; CHECK:       [[INNER_THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[M]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[INNER_LATCH]]
; CHECK:       [[INNER_LATCH]]:
; CHECK-NEXT:    [[M_NEXT]] = phi i64 [ [[INC]], %[[INNER_THEN]] ], [ [[M]], %[[INNER]] ]
; CHECK-NEXT:    [[INNER_C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[INNER_C]], label %[[INNER]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[M_LCSSA]] = phi i64 [ [[M_NEXT]], %[[INNER_LATCH]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %m.lcssa, %latch ]
  %t.0 = icmp ult i64 %n, 1000
  call void @use(i1 %t.0)
  br label %inner

inner:
  %m = phi i64 [ %n, %header ], [ %m.next, %inner.latch ]
  %c = call i1 @cond()
  br i1 %c, label %inner.then, label %inner.latch

inner.then:
  %inc = add nuw nsw i64 %m, 1
  %full = icmp eq i64 %inc, 1000
  br i1 %full, label %exit, label %inner.latch

inner.latch:
  %m.next = phi i64 [ %inc, %inner.then ], [ %m, %inner ]
  %inner.c = call i1 @cond()
  br i1 %inner.c, label %inner, label %latch

latch:
  %m.lcssa = phi i64 [ %m.next, %inner.latch ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Negative test: without the loop guard, the start value may not be below the
; bound.
define void @inc_symbolic_bound_no_guard(i64 %bound) {
; CHECK-LABEL: define void @inc_symbolic_bound_no_guard(
; CHECK-SAME: i64 [[BOUND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], [[BOUND]]
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw i64 [[N]], 1
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], [[BOUND]]
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c.0 = icmp ult i64 %n, %bound
  call void @use(i1 %c.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw i64 %n, 1
  %full = icmp eq i64 %inc, %bound
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Negative test: stepping by 2 may step over the bound.
define void @inc_by_2_exit_on_eq() {
; CHECK-LABEL: define void @inc_by_2_exit_on_eq() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], 999
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 2
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], 999
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c.0 = icmp ult i64 %n, 999
  call void @use(i1 %c.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 2
  %full = icmp eq i64 %inc, 999
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Negative test: the increment also flows into the backedge value without
; being checked.
define void @inc_check_not_dominating() {
; CHECK-LABEL: define void @inc_check_not_dominating() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], 1000
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[CHECK:.*]], label %[[LATCH]]
; CHECK:       [[CHECK]]:
; CHECK-NEXT:    [[FULL:%.*]] = icmp eq i64 [[INC]], 1000
; CHECK-NEXT:    br i1 [[FULL]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[CHECK]] ], [ [[INC]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c.0 = icmp ult i64 %n, 1000
  call void @use(i1 %c.0)
  %inc = add nuw nsw i64 %n, 1
  %c = call i1 @cond()
  br i1 %c, label %check, label %latch

check:
  %full = icmp eq i64 %inc, 1000
  br i1 %full, label %exit, label %latch

latch:
  %n.next = phi i64 [ %inc, %check ], [ %inc, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Negative test: the condition on the edge from %body only holds when the
; increment is not reached through %other.
define void @inc_edge_not_dominating() {
; CHECK-LABEL: define void @inc_edge_not_dominating() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], 1000
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[SMALL:%.*]] = icmp ult i64 [[N]], 999
; CHECK-NEXT:    br i1 [[SMALL]], label %[[THEN:.*]], label %[[OTHER:.*]]
; CHECK:       [[OTHER]]:
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[OTHER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c.0 = icmp ult i64 %n, 1000
  call void @use(i1 %c.0)
  br label %body

body:
  %small = icmp ult i64 %n, 999
  br i1 %small, label %then, label %other

other:
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 1
  br label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %other ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Negative test: both successors of the branch are the same block, so its
; condition holds on neither edge.
define void @branch_with_same_successors() {
; CHECK-LABEL: define void @branch_with_same_successors() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C_0:%.*]] = icmp ult i64 [[N]], 1000
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[X:%.*]] = call i64 @get()
; CHECK-NEXT:    [[SMALL:%.*]] = icmp ult i64 [[X]], 1000
; CHECK-NEXT:    br i1 [[SMALL]], label %[[LATCH]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[X]], %[[HEADER]] ], [ [[X]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c.0 = icmp ult i64 %n, 1000
  call void @use(i1 %c.0)
  %x = call i64 @get()
  %small = icmp ult i64 %x, 1000
  br i1 %small, label %latch, label %latch

latch:
  %n.next = phi i64 [ %x, %header ], [ %x, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Negative test: the bound is not loop-invariant.
define void @inc_bound_not_invariant() {
; CHECK-LABEL: define void @inc_bound_not_invariant() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[BOUND:%.*]] = call i64 @get()
; CHECK-NEXT:    [[C_0:%.*]] = icmp ule i64 [[N]], [[BOUND]]
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    [[ROOM:%.*]] = icmp ult i64 [[N]], [[BOUND]]
; CHECK-NEXT:    [[AND:%.*]] = select i1 [[C]], i1 [[ROOM]], i1 false
; CHECK-NEXT:    br i1 [[AND]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[N]], 1
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %bound = call i64 @get()
  %c.0 = icmp ule i64 %n, %bound
  call void @use(i1 %c.0)
  %c = call i1 @cond()
  %room = icmp ult i64 %n, %bound
  %and = select i1 %c, i1 %room, i1 false
  br i1 %and, label %then, label %latch

then:
  %inc = add nuw nsw i64 %n, 1
  br label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void
}

; Negative test: the bound is defined after the loop, in terms of a value that
; changes in each iteration.
define i1 @bound_defined_after_loop() {
; CHECK-LABEL: define i1 @bound_defined_after_loop() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[PN:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[PN_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[OTHER:%.*]] = phi i64 [ 1, %[[ENTRY]] ], [ [[OTHER_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[SMALL:%.*]] = icmp ult i64 [[OTHER]], 100
; CHECK-NEXT:    call void @llvm.assume(i1 [[SMALL]])
; CHECK-NEXT:    [[C_0:%.*]] = icmp ule i64 [[PN]], [[OTHER]]
; CHECK-NEXT:    call void @use(i1 [[C_0]])
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[PN_NEXT]] = phi i64 [ [[OTHER]], %[[THEN]] ], [ [[PN]], %[[HEADER]] ]
; CHECK-NEXT:    [[OTHER_NEXT]] = call i64 @get()
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[B:%.*]] = add nuw nsw i64 [[OTHER]], 1
; CHECK-NEXT:    [[R:%.*]] = icmp ult i64 [[PN]], [[B]]
; CHECK-NEXT:    ret i1 [[R]]
;
entry:
  br label %header

header:
  %pn = phi i64 [ 0, %entry ], [ %pn.next, %latch ]
  %other = phi i64 [ 1, %entry ], [ %other.next, %latch ]
  %small = icmp ult i64 %other, 100
  call void @llvm.assume(i1 %small)
  %c.0 = icmp ule i64 %pn, %other
  call void @use(i1 %c.0)
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  br label %latch

latch:
  %pn.next = phi i64 [ %other, %then ], [ %pn, %header ]
  %other.next = call i64 @get()
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  %b = add nuw i64 %other, 1
  %r = icmp ult i64 %pn, %b
  ret i1 %r
}

; Make sure compares in unreachable code are not used as bounds.
define void @bound_in_unreachable_block() {
; CHECK-LABEL: define void @bound_in_unreachable_block() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[N:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[C]], label %[[THEN:.*]], label %[[LATCH]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw i64 [[N]], 1
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[N_NEXT]] = phi i64 [ [[INC]], %[[THEN]] ], [ [[N]], %[[HEADER]] ]
; CHECK-NEXT:    [[CONT:%.*]] = call i1 @cond()
; CHECK-NEXT:    br i1 [[CONT]], label %[[HEADER]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
; CHECK:       [[DEAD:.*]]:
; CHECK-NEXT:    [[B:%.*]] = add nuw i64 [[B]], 1
; CHECK-NEXT:    [[R:%.*]] = icmp ult i64 [[N]], [[B]]
; CHECK-NEXT:    br label %[[DEAD]]
;
entry:
  br label %header

header:
  %n = phi i64 [ 0, %entry ], [ %n.next, %latch ]
  %c = call i1 @cond()
  br i1 %c, label %then, label %latch

then:
  %inc = add nuw i64 %n, 1
  br label %latch

latch:
  %n.next = phi i64 [ %inc, %then ], [ %n, %header ]
  %cont = call i1 @cond()
  br i1 %cont, label %header, label %exit

exit:
  ret void

dead:
  %b = add nuw i64 %b, 1
  %r = icmp ult i64 %n, %b
  br label %dead
}

