; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s

define i1000 @square(i1000 %A) nounwind {
; CHECK-LABEL: square:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    movq %rdx, %rbp
; CHECK-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %r14
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %r15
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rbx
; CHECK-NEXT:    bswapq %rbx
; CHECK-NEXT:    movq %rbx, %r10
; CHECK-NEXT:    shrq $4, %r10
; CHECK-NEXT:    movabsq $1085102592571150095, %r11 # imm = 0xF0F0F0F0F0F0F0F
; CHECK-NEXT:    andq %r11, %r10
; CHECK-NEXT:    andq %r11, %rbx
; CHECK-NEXT:    shlq $4, %rbx
; CHECK-NEXT:    orq %r10, %rbx
; CHECK-NEXT:    movabsq $3689348814741910323, %r10 # imm = 0x3333333333333333
; CHECK-NEXT:    movq %rbx, %r12
; CHECK-NEXT:    andq %r10, %r12
; CHECK-NEXT:    shrq $2, %rbx
; CHECK-NEXT:    andq %r10, %rbx
; CHECK-NEXT:    leaq (%rbx,%r12,4), %r12
; CHECK-NEXT:    movabsq $6148914691236517205, %rbx # imm = 0x5555555555555555
; CHECK-NEXT:    movq %r12, %r13
; CHECK-NEXT:    andq %rbx, %r13
; CHECK-NEXT:    shrq %r12
; CHECK-NEXT:    andq %rbx, %r12
; CHECK-NEXT:    leaq (%r12,%r13,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %r15
; CHECK-NEXT:    movq %r15, %r12
; CHECK-NEXT:    shrq $4, %r12
; CHECK-NEXT:    andq %r11, %r12
; CHECK-NEXT:    andq %r11, %r15
; CHECK-NEXT:    shlq $4, %r15
; CHECK-NEXT:    orq %r12, %r15
; CHECK-NEXT:    movq %r15, %r12
; CHECK-NEXT:    andq %r10, %r12
; CHECK-NEXT:    shrq $2, %r15
; CHECK-NEXT:    andq %r10, %r15
; CHECK-NEXT:    leaq (%r15,%r12,4), %r15
; CHECK-NEXT:    movabsq $6148914691230924800, %r12 # imm = 0x5555555555000000
; CHECK-NEXT:    movq %r15, %r13
; CHECK-NEXT:    andq %r12, %r13
; CHECK-NEXT:    shrq %r15
; CHECK-NEXT:    andq %r12, %r15
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %r12
; CHECK-NEXT:    leaq (%r15,%r13,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %r12
; CHECK-NEXT:    movq %r12, %r15
; CHECK-NEXT:    shrq $4, %r15
; CHECK-NEXT:    andq %r11, %r15
; CHECK-NEXT:    andq %r11, %r12
; CHECK-NEXT:    shlq $4, %r12
; CHECK-NEXT:    orq %r15, %r12
; CHECK-NEXT:    movq %r12, %r15
; CHECK-NEXT:    andq %r10, %r15
; CHECK-NEXT:    shrq $2, %r12
; CHECK-NEXT:    andq %r10, %r12
; CHECK-NEXT:    leaq (%r12,%r15,4), %r15
; CHECK-NEXT:    movq %r15, %r12
; CHECK-NEXT:    andq %rbx, %r12
; CHECK-NEXT:    shrq %r15
; CHECK-NEXT:    andq %rbx, %r15
; CHECK-NEXT:    leaq (%r15,%r12,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %r14
; CHECK-NEXT:    movq %r14, %r15
; CHECK-NEXT:    shrq $4, %r15
; CHECK-NEXT:    andq %r11, %r15
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    shlq $4, %r14
; CHECK-NEXT:    orq %r15, %r14
; CHECK-NEXT:    movq %r14, %r15
; CHECK-NEXT:    andq %r10, %r15
; CHECK-NEXT:    shrq $2, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    leaq (%r14,%r15,4), %r14
; CHECK-NEXT:    movq %r14, %r15
; CHECK-NEXT:    andq %rbx, %r15
; CHECK-NEXT:    shrq %r14
; CHECK-NEXT:    andq %rbx, %r14
; CHECK-NEXT:    leaq (%r14,%r15,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    andq %r11, %rdi
; CHECK-NEXT:    shlq $4, %rdi
; CHECK-NEXT:    orq %r14, %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    shrq $2, %rdi
; CHECK-NEXT:    andq %r10, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,4), %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %rbx, %r14
; CHECK-NEXT:    shrq %rdi
; CHECK-NEXT:    andq %rbx, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    bswapq %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    andq %r11, %rdi
; CHECK-NEXT:    shlq $4, %rdi
; CHECK-NEXT:    orq %r14, %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    shrq $2, %rdi
; CHECK-NEXT:    andq %r10, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,4), %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %rbx, %r14
; CHECK-NEXT:    shrq %rdi
; CHECK-NEXT:    andq %rbx, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,2), %r12
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    bswapq %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    andq %r11, %rdi
; CHECK-NEXT:    shlq $4, %rdi
; CHECK-NEXT:    orq %r14, %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    shrq $2, %rdi
; CHECK-NEXT:    andq %r10, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,4), %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %rbx, %r14
; CHECK-NEXT:    shrq %rdi
; CHECK-NEXT:    andq %rbx, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    bswapq %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    andq %r11, %rdi
; CHECK-NEXT:    shlq $4, %rdi
; CHECK-NEXT:    orq %r14, %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    shrq $2, %rdi
; CHECK-NEXT:    andq %r10, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,4), %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %rbx, %r14
; CHECK-NEXT:    shrq %rdi
; CHECK-NEXT:    andq %rbx, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    bswapq %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    andq %r11, %rdi
; CHECK-NEXT:    shlq $4, %rdi
; CHECK-NEXT:    orq %r14, %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    shrq $2, %rdi
; CHECK-NEXT:    andq %r10, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,4), %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %rbx, %r14
; CHECK-NEXT:    shrq %rdi
; CHECK-NEXT:    andq %rbx, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    bswapq %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    andq %r11, %rdi
; CHECK-NEXT:    shlq $4, %rdi
; CHECK-NEXT:    orq %r14, %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    shrq $2, %rdi
; CHECK-NEXT:    andq %r10, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,4), %rdi
; CHECK-NEXT:    movq %rdi, %r14
; CHECK-NEXT:    andq %rbx, %r14
; CHECK-NEXT:    shrq %rdi
; CHECK-NEXT:    andq %rbx, %rdi
; CHECK-NEXT:    leaq (%rdi,%r14,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    bswapq %rdi
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    andq %r11, %rdi
; CHECK-NEXT:    shlq $4, %rdi
; CHECK-NEXT:    orq %rax, %rdi
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shrq $2, %rdi
; CHECK-NEXT:    andq %r10, %rdi
; CHECK-NEXT:    leaq (%rdi,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %rdi
; CHECK-NEXT:    andq %rbx, %rdi
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %rbx, %rax
; CHECK-NEXT:    leaq (%rax,%rdi,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %r9
; CHECK-NEXT:    movq %r9, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    andq %r11, %r9
; CHECK-NEXT:    shlq $4, %r9
; CHECK-NEXT:    orq %rax, %r9
; CHECK-NEXT:    movq %r9, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shrq $2, %r9
; CHECK-NEXT:    andq %r10, %r9
; CHECK-NEXT:    leaq (%r9,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %r9
; CHECK-NEXT:    andq %rbx, %r9
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %rbx, %rax
; CHECK-NEXT:    leaq (%rax,%r9,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %r8
; CHECK-NEXT:    movq %r8, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    andq %r11, %r8
; CHECK-NEXT:    shlq $4, %r8
; CHECK-NEXT:    orq %rax, %r8
; CHECK-NEXT:    movq %r8, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shrq $2, %r8
; CHECK-NEXT:    andq %r10, %r8
; CHECK-NEXT:    leaq (%r8,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %r8
; CHECK-NEXT:    andq %rbx, %r8
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %rbx, %rax
; CHECK-NEXT:    leaq (%rax,%r8,2), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %rcx
; CHECK-NEXT:    movq %rcx, %r8
; CHECK-NEXT:    shrq $4, %r8
; CHECK-NEXT:    andq %r11, %r8
; CHECK-NEXT:    andq %r11, %rcx
; CHECK-NEXT:    shlq $4, %rcx
; CHECK-NEXT:    orq %r8, %rcx
; CHECK-NEXT:    movq %rcx, %r8
; CHECK-NEXT:    andq %r10, %r8
; CHECK-NEXT:    shrq $2, %rcx
; CHECK-NEXT:    andq %r10, %rcx
; CHECK-NEXT:    leaq (%rcx,%r8,4), %rcx
; CHECK-NEXT:    movq %rcx, %r8
; CHECK-NEXT:    andq %rbx, %r8
; CHECK-NEXT:    shrq %rcx
; CHECK-NEXT:    andq %rbx, %rcx
; CHECK-NEXT:    leaq (%rcx,%r8,2), %r14
; CHECK-NEXT:    bswapq %rbp
; CHECK-NEXT:    movq %rbp, %r8
; CHECK-NEXT:    shrq $4, %r8
; CHECK-NEXT:    andq %r11, %r8
; CHECK-NEXT:    andq %r11, %rbp
; CHECK-NEXT:    shlq $4, %rbp
; CHECK-NEXT:    orq %r8, %rbp
; CHECK-NEXT:    movq %rbp, %r8
; CHECK-NEXT:    andq %r10, %r8
; CHECK-NEXT:    shrq $2, %rbp
; CHECK-NEXT:    andq %r10, %rbp
; CHECK-NEXT:    leaq (%rbp,%r8,4), %r8
; CHECK-NEXT:    movq %r8, %rbp
; CHECK-NEXT:    andq %rbx, %rbp
; CHECK-NEXT:    shrq %r8
; CHECK-NEXT:    andq %rbx, %r8
; CHECK-NEXT:    leaq (%r8,%rbp,2), %r8
; CHECK-NEXT:    bswapq %rsi
; CHECK-NEXT:    movq %rsi, %rbp
; CHECK-NEXT:    shrq $4, %rbp
; CHECK-NEXT:    andq %r11, %rbp
; CHECK-NEXT:    andq %r11, %rsi
; CHECK-NEXT:    shlq $4, %rsi
; CHECK-NEXT:    orq %rbp, %rsi
; CHECK-NEXT:    movq %rsi, %r11
; CHECK-NEXT:    andq %r10, %r11
; CHECK-NEXT:    shrq $2, %rsi
; CHECK-NEXT:    andq %r10, %rsi
; CHECK-NEXT:    leaq (%rsi,%r11,4), %rsi
; CHECK-NEXT:    movq %rsi, %r10
; CHECK-NEXT:    andq %rbx, %r10
; CHECK-NEXT:    shrq %rsi
; CHECK-NEXT:    andq %rbx, %rsi
; CHECK-NEXT:    leaq (%rsi,%r10,2), %rsi
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %rax, %r11
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %rcx, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %rbp, %rcx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %r13, %rbp
; CHECK-NEXT:    shrdq $24, %r12, %r13
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %r15, %r12
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %rbx, %r15
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %r10, %rbx
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %r9, %r10
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %rdi, %r9
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %rdx, %rdi
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    shrdq $24, %rax, %rdx
; CHECK-NEXT:    shrdq $24, %r14, %rax
; CHECK-NEXT:    movq %rax, %rcx
; CHECK-NEXT:    shrdq $24, %r8, %r14
; CHECK-NEXT:    shrdq $24, %rsi, %r8
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %r8, 112(%rax)
; CHECK-NEXT:    movq %r14, 104(%rax)
; CHECK-NEXT:    movq %rcx, 96(%rax)
; CHECK-NEXT:    movq %rdx, 88(%rax)
; CHECK-NEXT:    movq %rdi, 80(%rax)
; CHECK-NEXT:    movq %r9, 72(%rax)
; CHECK-NEXT:    movq %r10, 64(%rax)
; CHECK-NEXT:    movq %rbx, 56(%rax)
; CHECK-NEXT:    movq %r15, 48(%rax)
; CHECK-NEXT:    movq %r12, 40(%rax)
; CHECK-NEXT:    movq %r13, 32(%rax)
; CHECK-NEXT:    movq %rbp, 24(%rax)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, 16(%rax)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, 8(%rax)
; CHECK-NEXT:    movq %r11, (%rax)
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $56, %rsi
; CHECK-NEXT:    movb %sil, 124(%rax)
; CHECK-NEXT:    shrq $24, %rcx
; CHECK-NEXT:    movl %ecx, 120(%rax)
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    retq
  %Z = call i1000 @llvm.bitreverse.i1000(i1000 %A)
  ret i1000 %Z
}

declare i1000 @llvm.bitreverse.i1000(i1000)
